#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: SiScLab_AiiDa_Installation_Notes
#+DATE: <2018-11-11 Sun>
#+AUTHOR: Johannes Wasmer
#+EMAIL: johannes@joe-9470m
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.2.2 (Org mode 9.1.13)

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+LATEX_COMPILER: pdflatex
#+DATE: \today

* [[file:SiScLab_Notes.org][Master File]]
* <2018-11-30 Fr> Installation of AiiDa on own system Kubuntu18.04

* <2018-11-11 Sun> STALLED 'Installation' of Quantum Mobile VM [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.10.0RC1][v18.10.0RC1]], [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.06.0][v18.6.0]] 
- version [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.10.0RC1][v18.10.0RC1]] is a release candidate, see [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.10.0RC1][qm vm releases]]. If not working, try
  [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.06.0][v18.6.0]] instead.
  - Rationale for trying out the newer unstable version first: has aiida-fleur
    v0.6.2, older version has aiida-fleur v0.6.0.
** DONE Install VirtualBox current version under (K)Ubuntu 18.04
   CLOSED: [2018-11-11 Sun 15:52]
*** Intro, Instruction URLs
- Problem: system VirtualBox is version 5.2.10, but qm vm [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.10.0RC1][v18.10.0RC1]] needs
  version 5.2.18, [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.06.0][v18.6.0]] needs version 5.2.12.
- Sidenote JW: did this on <2018-11-11 Sun>, worked. the process installed VB
  version 5.2.22.
- Instructions used for installing current version on Ubuntu 18.04/16:
  [[https://linuxize.com/post/how-to-install-virtualbox-on-ubuntu-18-04/][instructionA]], [[https://websiteforstudents.com/install-the-latest-virtualbox-on-ubuntu-18-04-lts/][instructionB]]. The [[https://github.com/marvel-nccr/quantum-mobile/wiki/Frequently-Asked-Questions][instructionC=qm vm FAQ]] has also some (shorter)
  instructions.
- Sidenote JW: for my computer, VMs are stored on a separate HD partition
  [[file:/media/sams250g/johannes/VirtualBox%20VMs/][/media/sams250g/johannes/VirtualBox 20VMs]]
*** Execution
- import GPG keys of Orcacle VB repo. Should return 'OK'.
  #+BEGIN_SRC shell
  wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -  
  #+END_SRC
- add the VirtualBox repository with the add-apt-repository command as shown below:
  - instructionA says:
    #+BEGIN_SRC shell
    sudo add-apt-repository "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib"
    #+END_SRC
  - instructionB says:
    #+BEGIN_SRC shell
    sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list.d/virtualbox.list'
    #+END_SRC
  - seems that both do the same. used instructionA. ~arch=amd64~ is okay, even
    if your ~uname -m~ returns =x86_64=.
- instructionB has an additional step here: "you may want to remove older
  versions of the software if you’re still running it… to do that, run the
  commands below:"
  #+BEGIN_SRC shell
  sudo apt remove virtualbox virtualbox-5.1
  #+END_SRC
  - JW Sidenote: ~apt~ offers just =virtualbox=. Es gab dabei ein paar Fehler.
    Komischerweise steht da auch version 5.2.22. Im VB GUI stand aber 5.2.10???
    Naja, egal, jedenfalls ist =virtualbox= nicht mehr auf dem Pfad.
    #+BEGIN_EXAMPLE
    johannes@joe-9470m:~$ sudo apt remove virtualbox
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      dkms libgsoap-2.8.60 libsdl-ttf2.0-0 libvncserver1 virtualbox-5.2 virtualbox-dkms
    Use 'sudo apt autoremove' to remove them.
    The following additional packages will be installed:
      libsdl-ttf2.0-0 virtualbox-5.2
    The following packages will be REMOVED:
      virtualbox virtualbox-ext-pack virtualbox-guest-additions-iso virtualbox-qt
    The following NEW packages will be installed:
      libsdl-ttf2.0-0 virtualbox-5.2
    0 upgraded, 2 newly installed, 4 to remove and 0 not upgraded.
    Need to get 68.2 MB of archives.
    After this operation, 1236 kB of additional disk space will be used.
    Do you want to continue? [Y/n] y
    Get:1 http://download.virtualbox.org/virtualbox/debian bionic/contrib amd64 virtualbox-5.2 amd64 5.2.22-126460~Ubuntu~bionic [68.1 MB]
    Get:2 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 libsdl-ttf2.0-0 amd64 2.0.11-4 [15.0 kB]
    Fetched 68.2 MB in 6s (11.3 MB/s)                                                                                                                                                              
    Preconfiguring packages ...
    (Reading database ... 498238 files and directories currently installed.)
    Removing virtualbox-qt (5.2.10-dfsg-6ubuntu18.04.1) ...
    Removing virtualbox-ext-pack (5.2.10-3ubuntu18.04.1) ...
    0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    Successfully uninstalled "Oracle VM VirtualBox Extension Pack".
    Successfully performed extension pack cleanup
    Removing virtualbox (5.2.10-dfsg-6ubuntu18.04.1) ...
    Removing virtualbox-guest-additions-iso (5.2.11-122181-1) ...
    Selecting previously unselected package virtualbox-5.2.
    (Reading database ... 497919 files and directories currently installed.)
    Preparing to unpack .../virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb ...
    dpkg: error processing archive /var/cache/apt/archives/virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb (--unpack):
     new virtualbox-5.2 package pre-installation script subprocess returned error exit status 1
    Selecting previously unselected package libsdl-ttf2.0-0:amd64.
    Preparing to unpack .../libsdl-ttf2.0-0_2.0.11-4_amd64.deb ...
    Unpacking libsdl-ttf2.0-0:amd64 (2.0.11-4) ...
    Errors were encountered while processing:
     /var/cache/apt/archives/virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)    
    #+END_EXAMPLE
- install new version =virtualbox-5.2= is now from the installed repo, while
  =virtualbox= is the older ubuntu version as before.
  #+BEGIN_SRC shell
  sudo apt update #preinstall required packages, no action if installed:
  sudo apt-get -y install gcc make linux-headers-$(uname -r) dkms
  sudo apt update #install the newest version from new repo:
  sudo apt install virtualbox-5.2
  #+END_SRC
  - JW output:
    #+BEGIN_EXAMPLE
    johannes@joe-9470m:~$ sudo apt-get install virtualbox-5.2
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libgsoap-2.8.60 libvncserver1 virtualbox-dkms
    Use 'sudo apt autoremove' to remove them.
    The following NEW packages will be installed:
      virtualbox-5.2
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 0 B/68.1 MB of archives.
    After this operation, 167 MB of additional disk space will be used.
    Preconfiguring packages ...
    (Reading database ... 497926 files and directories currently installed.)
    Preparing to unpack .../virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb ...
    Unpacking virtualbox-5.2 (5.2.22-126460~Ubuntu~bionic) ...
    Setting up virtualbox-5.2 (5.2.22-126460~Ubuntu~bionic) ...
    addgroup: The group `vboxusers' already exists as a system group. Exiting.
    Processing triggers for mime-support (3.60ubuntu1) ...
    Processing triggers for ureadahead (0.100.0-20) ...
    Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.1) ...
    Processing triggers for systemd (237-3ubuntu10.4) ...
    Processing triggers for shared-mime-info (1.9-2) ...
    Unknown media type in type 'all/all'
    Unknown media type in type 'all/allfiles'
    Processing triggers for hicolor-icon-theme (0.17-2) ...
    #+END_EXAMPLE
*** Result
- JW Sidenotes: Results:
  - the installed version is now 5.2.22.
  - new version automatically found my old VMs
    [[file:/media/sams250g/johannes/VirtualBox%20VMs/][/media/sams250g/johannes/VirtualBox 20VMs]]
    
*** Installation of Extension Pack
- from instructionA
- [[https://www.virtualbox.org/wiki/Downloads][check]] for current version:
  https://download.virtualbox.org/virtualbox/5.2.22/Oracle_VM_VirtualBox_Extension_Pack-5.2.22.vbox-extpack
- do:
  #+BEGIN_SRC shell
  wget https://download.virtualbox.org/virtualbox/5.2.22/Oracle_VM_VirtualBox_Extension_Pack-5.2.22.vbox-extpack
  #+END_SRC
- import extension pack:
  #+BEGIN_SRC shell
  sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.2.20.vbox-extpack
  # ... should end with:
  # Successfully installed "Oracle VM VirtualBox Extension Pack".
  #+END_SRC

** Import virtual machine in VB, setup shared folder
- from qm vm release notes:
  - Import virtual machine image into Virtualbox (12G): File => Import Appliance
- from instructionC:
  - Stop the VM
  - Add your folder in Machine => Settings => Shared Folders => Add Folder Icon
  - tick "Automount"
  - Start VM. The folder will appear in /media/sf_<folder_name>
** Start Quantum Mobile VM

- username: max, password: moritz

