# -*- coding: utf-8 -*-
__inp_version__ = '0.27'
schema_dict = {'attrib_types': {'Gmax': 'float',
                  'GmaxXC': 'float',
                  'J': 'float',
                  'Kmax': 'float',
                  'M': 'float',
                  'MM': 'int',
                  'U': 'float',
                  'alpha': 'float',
                  'atomicNumber': 'int',
                  'autocomp': 'switch',
                  'b_cons_x': 'float',
                  'b_cons_y': 'float',
                  'band': 'switch',
                  'beta': 'float',
                  'bmt': 'switch',
                  'calculate': 'switch',
                  'cdinf': 'switch',
                  'chi': 'int',
                  'chng': 'float',
                  'coreStates': 'int',
                  'count': 'int',
                  'ctail': 'switch',
                  'd': 'int',
                  'd1': 'switch',
                  'dTilda': 'float',
                  'dVac': 'float',
                  'dirichlet': 'switch',
                  'disp': 'switch',
                  'dos': 'switch',
                  'eDeriv': 'int',
                  'eV': 'switch',
                  'eig66': 'switch',
                  'element': 'string',
                  'ellow': 'float',
                  'elup': 'float',
                  'eonly': 'switch',
                  'epsdisp': 'float',
                  'epsforce': 'float',
                  'f': 'int',
                  'fermiSmearingEnergy': 'float',
                  'fermiSmearingTemp': 'float',
                  'filename': 'string',
                  'fleurInputVersion': 'string',
                  'flipSpin': 'switch',
                  'form66': 'switch',
                  'frcor': 'switch',
                  'gamma': 'switch',
                  'gridPoints': 'int',
                  'gw': 'int',
                  'idsprs': 'int',
                  'idsprs0': 'int',
                  'idsprsi': 'int',
                  'idsprsl': 'int',
                  'idsprsv': 'float',
                  'iggachk': 'int',
                  'igrd': 'int',
                  'imix': 'string',
                  'integ': 'switch',
                  'invs': 'switch',
                  'invs1': 'switch',
                  'iplot': 'switch',
                  'isec1': 'int',
                  'itmax': 'int',
                  'jspins': 'int',
                  'kcrel': 'int',
                  'l': 'int',
                  'l_J': 'switch',
                  'l_amf': 'switch',
                  'l_constr': 'switch',
                  'l_disp': 'switch',
                  'l_f': 'switch',
                  'l_magn': 'switch',
                  'l_mperp': 'switch',
                  'l_noco': 'switch',
                  'l_relax': 'switch',
                  'l_soc': 'switch',
                  'l_ss': 'switch',
                  'latnam': 'string',
                  'layers': 'int',
                  'lflip': 'switch',
                  'lmax': 'int',
                  'lmaxAPW': 'int',
                  'lnonsphr': 'int',
                  'locx1': 'float',
                  'locx2': 'float',
                  'locy1': 'float',
                  'locy2': 'float',
                  'logIncrement': 'float',
                  'lpr': 'int',
                  'lwb': 'switch',
                  'm_cyl': 'int',
                  'magField': 'float',
                  'magMom': 'float',
                  'maxEigenval': 'float',
                  'maxEnergy': 'float',
                  'maxIterBroyd': 'int',
                  'maxTimeToStartIter': 'float',
                  'minDistance': 'float',
                  'minEigenval': 'float',
                  'minEnergy': 'float',
                  'mix_b': 'float',
                  'mode': 'string',
                  'n': 'int',
                  'name': 'string',
                  'ndir': 'int',
                  'ndvgrd': 'int',
                  'nnne': 'int',
                  'nsh': 'int',
                  'nstars': 'int',
                  'nstm': 'int',
                  'numbands': ['int', 'string'],
                  'numkpt': 'int',
                  'nx': 'int',
                  'ny': 'int',
                  'nz': 'int',
                  'off': 'switch',
                  'orbcomp': 'switch',
                  'p': 'int',
                  'pallst': 'switch',
                  'phi': 'float',
                  'plot_charge': 'switch',
                  'plot_rho': 'switch',
                  'plplot': 'switch',
                  'posScale': 'float',
                  'pot8': 'switch',
                  'qfix': 'switch',
                  'qx': 'int',
                  'qy': 'int',
                  'qz': 'int',
                  'radius': 'float',
                  'relativisticCorrections': 'switch',
                  'relaxXYZ': 'string',
                  'rot': 'int',
                  's': 'int',
                  'scale': 'float',
                  'score': 'switch',
                  'secvar': 'switch',
                  'sig_b_1': 'float',
                  'sig_b_2': 'float',
                  'sigma': 'float',
                  'slice': 'switch',
                  'soc66': 'switch',
                  'spav': 'switch',
                  'species': 'string',
                  'spgrp': 'string',
                  'spinDown': 'float',
                  'spinUp': 'float',
                  'spinf': 'float',
                  'sso_opt': 'string',
                  'star': 'switch',
                  'state': 'string',
                  'swsp': 'switch',
                  'theta': 'float',
                  'thetaJ': 'float',
                  'thetad': 'float',
                  'tworkf': 'float',
                  'type': 'string',
                  'vM': 'int',
                  'vacdos': 'switch',
                  'vacuum': 'int',
                  'valenceElectrons': 'float',
                  'value': 'string',
                  'vcaAddCharge': 'float',
                  'vchk': 'switch',
                  'weight': 'float',
                  'weightScale': 'float',
                  'xa': 'float',
                  'zrfs': 'switch',
                  'zrfs1': 'switch',
                  'zsigma': 'float'},
 'basic_types': {'BZIntegrationModeEnum': {'base_types': ['string'],
                                           'length': 1},
                 'CoreConfigEnum': {'base_types': ['string'], 'length': 1},
                 'CoreStateListType': {'base_types': ['string'],
                                       'length': 'unbounded'},
                 'Double3DVecType': {'base_types': ['float'], 'length': 3},
                 'Double4DVecType': {'base_types': ['float'], 'length': 4},
                 'DoubleVecType': {'base_types': ['float'],
                                   'length': 'unbounded'},
                 'EParamSelectionEnum': {'base_types': ['string'], 'length': 1},
                 'ElectronStateEnum': {'base_types': ['string'], 'length': 1},
                 'FleurVersionType': {'base_types': ['string'], 'length': 1},
                 'KPointType': {'base_types': ['float'], 'length': 3},
                 'LatnamEnum': {'base_types': ['string'], 'length': 1},
                 'MixingEnum': {'base_types': ['string'], 'length': 1},
                 'NobleGasConfigEnum': {'base_types': ['string'], 'length': 1},
                 'NumBandsType': {'base_types': ['int', 'string'], 'length': 1},
                 'PositionType': {'base_types': ['float'], 'length': 3},
                 'SpecialPointType': {'base_types': ['float'], 'length': 3},
                 'SpgrpEnum': {'base_types': ['string'], 'length': 1},
                 'SpinNumberType': {'base_types': ['int'], 'length': 1},
                 'String2DVecType': {'base_types': ['string'], 'length': 2},
                 'String3DVecType': {'base_types': ['string'], 'length': 3},
                 'StringVecType': {'base_types': ['string'],
                                   'length': 'unbounded'},
                 'TripleFleurBool': {'base_types': ['string'], 'length': 1},
                 'ValenceStateListType': {'base_types': ['string'],
                                          'length': 'unbounded'},
                 'XCFunctionalEnum': {'base_types': ['string'], 'length': 1}},
 'omitt_contained_tags': ['constants',
                          'atomSpecies',
                          'atomGroups',
                          'symmetryOperations'],
 'settable_attribs': {'Gmax': '/fleurInput/calculationSetup/cutoffs',
                      'GmaxXC': '/fleurInput/calculationSetup/cutoffs',
                      'Kmax': '/fleurInput/calculationSetup/cutoffs',
                      'MM': '/fleurInput/calculationSetup/oneDParams',
                      'alpha': '/fleurInput/calculationSetup/scfLoop',
                      'autocomp': '/fleurInput/calculationSetup/eField',
                      'band': '/fleurInput/output',
                      'bmt': '/fleurInput/output/specialOutput',
                      'c': '/fleurInput/cell/bulkLattice/c',
                      'cdinf': '/fleurInput/output/checks',
                      'chi': '/fleurInput/calculationSetup/oneDParams',
                      'chng': '/fleurInput/xcFunctional/xcParams',
                      'comment': '/fleurInput/comment',
                      'ctail': '/fleurInput/calculationSetup/coreElectrons',
                      'd1': '/fleurInput/calculationSetup/oneDParams',
                      'dTilda': '/fleurInput/cell/filmLattice',
                      'dVac': '/fleurInput/cell/filmLattice',
                      'dirichlet': '/fleurInput/calculationSetup/eField',
                      'disp': '/fleurInput/output/checks',
                      'dos': '/fleurInput/output',
                      'eV': '/fleurInput/calculationSetup/eField',
                      'eig66': '/fleurInput/calculationSetup/expertModes',
                      'ellow': '/fleurInput/calculationSetup/energyParameterLimits',
                      'elup': '/fleurInput/calculationSetup/energyParameterLimits',
                      'eonly': '/fleurInput/output/specialOutput',
                      'epsdisp': '/fleurInput/calculationSetup/geometryOptimization',
                      'epsforce': '/fleurInput/calculationSetup/geometryOptimization',
                      'fermiSmearingEnergy': '/fleurInput/calculationSetup/bzIntegration',
                      'fermiSmearingTemp': '/fleurInput/calculationSetup/bzIntegration',
                      'filename': '/fleurInput/cell/symmetryFile',
                      'fleurInputVersion': '/fleurInput',
                      'form66': '/fleurInput/output/specialOutput',
                      'frcor': '/fleurInput/calculationSetup/coreElectrons',
                      'gw': '/fleurInput/calculationSetup/expertModes',
                      'idsprs': '/fleurInput/xcFunctional/xcParams',
                      'idsprs0': '/fleurInput/xcFunctional/ggaPrinting',
                      'idsprsi': '/fleurInput/xcFunctional/ggaPrinting',
                      'idsprsl': '/fleurInput/xcFunctional/ggaPrinting',
                      'idsprsv': '/fleurInput/xcFunctional/ggaPrinting',
                      'iggachk': '/fleurInput/xcFunctional/ggaPrinting',
                      'igrd': '/fleurInput/xcFunctional/xcParams',
                      'imix': '/fleurInput/calculationSetup/scfLoop',
                      'integ': '/fleurInput/output/vacuumDOS',
                      'invs': '/fleurInput/cell/symmetry',
                      'invs1': '/fleurInput/calculationSetup/oneDParams',
                      'iplot': '/fleurInput/output/plotting',
                      'isec1': '/fleurInput/calculationSetup/expertModes',
                      'itmax': '/fleurInput/calculationSetup/scfLoop',
                      'jspins': '/fleurInput/calculationSetup/magnetism',
                      'kcrel': '/fleurInput/calculationSetup/coreElectrons',
                      'l_J': '/fleurInput/calculationSetup/magnetism',
                      'l_constr': '/fleurInput/calculationSetup/nocoParams',
                      'l_disp': '/fleurInput/calculationSetup/nocoParams',
                      'l_f': '/fleurInput/calculationSetup/geometryOptimization',
                      'l_mperp': '/fleurInput/calculationSetup/nocoParams',
                      'l_noco': '/fleurInput/calculationSetup/magnetism',
                      'l_soc': '/fleurInput/calculationSetup/soc',
                      'l_ss': '/fleurInput/calculationSetup/nocoParams',
                      'layers': '/fleurInput/output/vacuumDOS',
                      'lflip': '/fleurInput/calculationSetup/magnetism',
                      'locx1': '/fleurInput/output/vacuumDOS',
                      'locx2': '/fleurInput/output/vacuumDOS',
                      'locy1': '/fleurInput/output/vacuumDOS',
                      'locy2': '/fleurInput/output/vacuumDOS',
                      'lpr': '/fleurInput/calculationSetup/expertModes',
                      'lwb': '/fleurInput/xcFunctional/xcParams',
                      'm_cyl': '/fleurInput/calculationSetup/oneDParams',
                      'maxEigenval': '/fleurInput/output/chargeDensitySlicing',
                      'maxEnergy': '/fleurInput/output/densityOfStates',
                      'maxIterBroyd': '/fleurInput/calculationSetup/scfLoop',
                      'maxTimeToStartIter': '/fleurInput/calculationSetup/scfLoop',
                      'minDistance': '/fleurInput/calculationSetup/scfLoop',
                      'minEigenval': '/fleurInput/output/chargeDensitySlicing',
                      'minEnergy': '/fleurInput/output/densityOfStates',
                      'mix_b': '/fleurInput/calculationSetup/nocoParams',
                      'mode': '/fleurInput/calculationSetup/bzIntegration',
                      'name': '/fleurInput/xcFunctional',
                      'ndir': '/fleurInput/output/densityOfStates',
                      'ndvgrd': '/fleurInput/xcFunctional/xcParams',
                      'nnne': '/fleurInput/output/chargeDensitySlicing',
                      'nsh': '/fleurInput/calculationSetup/nocoParams',
                      'nstars': '/fleurInput/output/vacuumDOS',
                      'nstm': '/fleurInput/output/vacuumDOS',
                      'numbands': '/fleurInput/calculationSetup/cutoffs',
                      'numkpt': '/fleurInput/output/chargeDensitySlicing',
                      'nx': '/fleurInput/calculationSetup/bzIntegration/kPointMesh',
                      'ny': '/fleurInput/calculationSetup/bzIntegration/kPointMesh',
                      'nz': '/fleurInput/calculationSetup/bzIntegration/kPointMesh',
                      'off': '/fleurInput/calculationSetup/soc',
                      'pallst': '/fleurInput/output/chargeDensitySlicing',
                      'phi': '/fleurInput/calculationSetup/soc',
                      'plot_charge': '/fleurInput/calculationSetup/eField',
                      'plot_rho': '/fleurInput/calculationSetup/eField',
                      'plplot': '/fleurInput/output/plotting',
                      'posScale': '/fleurInput/calculationSetup/bzIntegration/kPointList',
                      'pot8': '/fleurInput/calculationSetup/expertModes',
                      'qfix': '/fleurInput/calculationSetup/geometryOptimization',
                      'qsc': '/fleurInput/calculationSetup/nocoParams/qsc',
                      'qss': '/fleurInput/calculationSetup/nocoParams/qss',
                      'qx': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
                      'qy': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
                      'qz': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
                      'relativisticCorrections': '/fleurInput/xcFunctional',
                      'rot': '/fleurInput/calculationSetup/oneDParams',
                      'score': '/fleurInput/output/plotting',
                      'secvar': '/fleurInput/calculationSetup/expertModes',
                      'sig_b_1': '/fleurInput/calculationSetup/eField',
                      'sig_b_2': '/fleurInput/calculationSetup/eField',
                      'sigma': '/fleurInput/output/densityOfStates',
                      'slice': '/fleurInput/output',
                      'soc66': '/fleurInput/calculationSetup/soc',
                      'spav': '/fleurInput/calculationSetup/soc',
                      'spgrp': '/fleurInput/cell/symmetry',
                      'spinf': '/fleurInput/calculationSetup/scfLoop',
                      'sso_opt': '/fleurInput/calculationSetup/nocoParams',
                      'star': '/fleurInput/output/vacuumDOS',
                      'swsp': '/fleurInput/calculationSetup/magnetism',
                      'theta': '/fleurInput/calculationSetup/soc',
                      'thetaJ': '/fleurInput/calculationSetup/nocoParams',
                      'thetad': '/fleurInput/calculationSetup/geometryOptimization',
                      'tworkf': '/fleurInput/output/vacuumDOS',
                      'vM': '/fleurInput/calculationSetup/oneDParams',
                      'vacdos': '/fleurInput/output',
                      'valenceElectrons': '/fleurInput/calculationSetup/bzIntegration',
                      'vchk': '/fleurInput/output/checks',
                      'weightScale': '/fleurInput/calculationSetup/bzIntegration/kPointList',
                      'xa': '/fleurInput/calculationSetup/geometryOptimization',
                      'zrfs': '/fleurInput/cell/symmetry',
                      'zrfs1': '/fleurInput/calculationSetup/oneDParams',
                      'zsigma': '/fleurInput/calculationSetup/eField'},
 'settable_contains_attribs': {'a1': ['/fleurInput/cell/bulkLattice/a1',
                                      '/fleurInput/cell/filmLattice/a1'],
                               'a2': ['/fleurInput/cell/bulkLattice/a2',
                                      '/fleurInput/cell/filmLattice/a2'],
                               'count': ['/fleurInput/calculationSetup/bzIntegration/kPointCount',
                                         '/fleurInput/calculationSetup/bzIntegration/kPointList'],
                               'gamma': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh',
                                         '/fleurInput/calculationSetup/bzIntegration/kPointCount'],
                               'latnam': ['/fleurInput/cell/bulkLattice',
                                          '/fleurInput/cell/filmLattice'],
                               'row-1': ['/fleurInput/cell/bulkLattice/row-1',
                                         '/fleurInput/cell/filmLattice/row-1',
                                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-1',
                                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-1'],
                               'row-2': ['/fleurInput/cell/bulkLattice/row-2',
                                         '/fleurInput/cell/filmLattice/row-2',
                                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-2',
                                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-2'],
                               'row-3': ['/fleurInput/cell/bulkLattice/bravaisMatrix/row-3',
                                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-3'],
                               'scale': ['/fleurInput/cell/bulkLattice',
                                         '/fleurInput/cell/filmLattice']},
 'simple_elements': {'a1': {'length': 1, 'type': ['float']},
                     'a2': {'length': 1, 'type': ['float']},
                     'absPos': {'length': 3, 'type': ['string']},
                     'c': {'length': 1, 'type': ['float']},
                     'comment': {'length': 1, 'type': ['string']},
                     'coreConfig': {'length': 'unbounded', 'type': ['string']},
                     'filmPos': {'length': 3, 'type': ['string']},
                     'kPoint': {'length': 3, 'type': ['float']},
                     'orbcomprot': {'length': 3, 'type': ['float']},
                     'qsc': {'length': 3, 'type': ['float']},
                     'qss': {'length': 3, 'type': ['float']},
                     'relPos': {'length': 3, 'type': ['string']},
                     'row-1': [{'length': 2, 'type': ['string']},
                               {'length': 3, 'type': ['string']},
                               {'length': 4, 'type': ['float']}],
                     'row-2': [{'length': 2, 'type': ['string']},
                               {'length': 3, 'type': ['string']},
                               {'length': 4, 'type': ['float']}],
                     'row-3': [{'length': 3, 'type': ['string']},
                               {'length': 4, 'type': ['float']}],
                     'specialPoint': {'length': 3, 'type': ['float']},
                     'valenceConfig': {'length': 'unbounded',
                                       'type': ['string']}},
 'tag_attribs': {'/fleurInput': ['fleurInputVersion'],
                 '/fleurInput/atomGroups/atomGroup': ['species',
                                                      'orbcomp',
                                                      'magField',
                                                      'vcaAddCharge'],
                 '/fleurInput/atomGroups/atomGroup/atomicCutoffs': ['lmax',
                                                                    'lnonsphr',
                                                                    'lmaxAPW'],
                 '/fleurInput/atomGroups/atomGroup/energyParameters': ['s',
                                                                       'p',
                                                                       'd',
                                                                       'f'],
                 '/fleurInput/atomGroups/atomGroup/force': ['calculate',
                                                            'relaxXYZ'],
                 '/fleurInput/atomGroups/atomGroup/ldaU': ['l',
                                                           'U',
                                                           'J',
                                                           'l_amf'],
                 '/fleurInput/atomGroups/atomGroup/lo': ['type',
                                                         'l',
                                                         'n',
                                                         'eDeriv'],
                 '/fleurInput/atomGroups/atomGroup/mtSphere': ['radius',
                                                               'gridPoints',
                                                               'logIncrement'],
                 '/fleurInput/atomGroups/atomGroup/nocoParams': ['l_relax',
                                                                 'l_magn',
                                                                 'M',
                                                                 'alpha',
                                                                 'beta',
                                                                 'b_cons_x',
                                                                 'b_cons_y'],
                 '/fleurInput/atomSpecies/species': ['name',
                                                     'element',
                                                     'atomicNumber',
                                                     'coreStates',
                                                     'magMom',
                                                     'flipSpin',
                                                     'magField',
                                                     'vcaAddCharge'],
                 '/fleurInput/atomSpecies/species/atomicCutoffs': ['lmax',
                                                                   'lnonsphr',
                                                                   'lmaxAPW'],
                 '/fleurInput/atomSpecies/species/electronConfig/stateOccupation': ['state',
                                                                                    'spinUp',
                                                                                    'spinDown'],
                 '/fleurInput/atomSpecies/species/energyParameters': ['s',
                                                                      'p',
                                                                      'd',
                                                                      'f'],
                 '/fleurInput/atomSpecies/species/force': ['calculate',
                                                           'relaxXYZ'],
                 '/fleurInput/atomSpecies/species/ldaU': ['l',
                                                          'U',
                                                          'J',
                                                          'l_amf'],
                 '/fleurInput/atomSpecies/species/lo': ['type',
                                                        'l',
                                                        'n',
                                                        'eDeriv'],
                 '/fleurInput/atomSpecies/species/mtSphere': ['radius',
                                                              'gridPoints',
                                                              'logIncrement'],
                 '/fleurInput/atomSpecies/species/nocoParams': ['l_relax',
                                                                'l_magn',
                                                                'M',
                                                                'alpha',
                                                                'beta',
                                                                'b_cons_x',
                                                                'b_cons_y'],
                 '/fleurInput/calculationSetup/bzIntegration': ['valenceElectrons',
                                                                'mode',
                                                                'fermiSmearingEnergy',
                                                                'fermiSmearingTemp'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointCount': ['count',
                                                                            'gamma'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointCount/specialPoint': ['name'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointList': ['posScale',
                                                                           'weightScale',
                                                                           'count'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointList/kPoint': ['weight'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointMesh': ['nx',
                                                                           'ny',
                                                                           'nz',
                                                                           'gamma'],
                 '/fleurInput/calculationSetup/coreElectrons': ['ctail',
                                                                'frcor',
                                                                'kcrel'],
                 '/fleurInput/calculationSetup/cutoffs': ['Kmax',
                                                          'Gmax',
                                                          'GmaxXC',
                                                          'numbands'],
                 '/fleurInput/calculationSetup/eField': ['zsigma',
                                                         'sig_b_1',
                                                         'sig_b_2',
                                                         'plot_charge',
                                                         'plot_rho',
                                                         'autocomp',
                                                         'dirichlet',
                                                         'eV'],
                 '/fleurInput/calculationSetup/energyParameterLimits': ['ellow',
                                                                        'elup'],
                 '/fleurInput/calculationSetup/expertModes': ['gw',
                                                              'pot8',
                                                              'eig66',
                                                              'lpr',
                                                              'isec1',
                                                              'secvar'],
                 '/fleurInput/calculationSetup/geometryOptimization': ['l_f',
                                                                       'xa',
                                                                       'thetad',
                                                                       'epsdisp',
                                                                       'epsforce',
                                                                       'qfix'],
                 '/fleurInput/calculationSetup/magnetism': ['jspins',
                                                            'l_noco',
                                                            'l_J',
                                                            'swsp',
                                                            'lflip'],
                 '/fleurInput/calculationSetup/nocoParams': ['l_ss',
                                                             'l_mperp',
                                                             'l_constr',
                                                             'l_disp',
                                                             'sso_opt',
                                                             'mix_b',
                                                             'thetaJ',
                                                             'nsh'],
                 '/fleurInput/calculationSetup/oneDParams': ['d1',
                                                             'MM',
                                                             'vM',
                                                             'm_cyl',
                                                             'chi',
                                                             'rot',
                                                             'invs1',
                                                             'zrfs1'],
                 '/fleurInput/calculationSetup/scfLoop': ['itmax',
                                                          'maxIterBroyd',
                                                          'imix',
                                                          'alpha',
                                                          'spinf',
                                                          'minDistance',
                                                          'maxTimeToStartIter'],
                 '/fleurInput/calculationSetup/soc': ['theta',
                                                      'phi',
                                                      'l_soc',
                                                      'spav',
                                                      'off',
                                                      'soc66'],
                 '/fleurInput/calculationSetup/spinSpiralQPointMesh': ['qx',
                                                                       'qy',
                                                                       'qz'],
                 '/fleurInput/cell/bulkLattice': ['scale', 'latnam'],
                 '/fleurInput/cell/filmLattice': ['scale',
                                                  'latnam',
                                                  'dVac',
                                                  'dTilda'],
                 '/fleurInput/cell/filmLattice/vacuumEnergyParameters': ['vacuum',
                                                                         'spinUp',
                                                                         'spinDown'],
                 '/fleurInput/cell/symmetry': ['spgrp', 'invs', 'zrfs'],
                 '/fleurInput/cell/symmetryFile': ['filename'],
                 '/fleurInput/constants/constant': ['name', 'value'],
                 '/fleurInput/output': ['dos', 'band', 'vacdos', 'slice'],
                 '/fleurInput/output/chargeDensitySlicing': ['numkpt',
                                                             'minEigenval',
                                                             'maxEigenval',
                                                             'nnne',
                                                             'pallst'],
                 '/fleurInput/output/checks': ['vchk', 'cdinf', 'disp'],
                 '/fleurInput/output/densityOfStates': ['ndir',
                                                        'minEnergy',
                                                        'maxEnergy',
                                                        'sigma'],
                 '/fleurInput/output/plotting': ['iplot', 'score', 'plplot'],
                 '/fleurInput/output/specialOutput': ['form66', 'eonly', 'bmt'],
                 '/fleurInput/output/vacuumDOS': ['layers',
                                                  'integ',
                                                  'star',
                                                  'nstars',
                                                  'locx1',
                                                  'locy1',
                                                  'locx2',
                                                  'locy2',
                                                  'nstm',
                                                  'tworkf'],
                 '/fleurInput/xcFunctional': ['name',
                                              'relativisticCorrections'],
                 '/fleurInput/xcFunctional/ggaPrinting': ['iggachk',
                                                          'idsprs0',
                                                          'idsprsl',
                                                          'idsprsi',
                                                          'idsprsv'],
                 '/fleurInput/xcFunctional/xcParams': ['igrd',
                                                       'lwb',
                                                       'ndvgrd',
                                                       'idsprs',
                                                       'chng']},
 'tag_order': {'atomGroup': [['relPos', 'absPos', 'filmPos'],
                             'mtSphere',
                             'atomicCutoffs',
                             'energyParameters',
                             'force',
                             'nocoParams',
                             'ldaU',
                             'lo',
                             'orbcomprot'],
               'atomGroups': 'atomGroup',
               'atomSpecies': 'species',
               'bravaisMatrix': ['row-1', 'row-2', 'row-3'],
               'bulkLattice': [['a1', 'a2', 'c'],
                               ['row-1', 'row-2', 'c'],
                               'bravaisMatrix'],
               'bzIntegration': ['kPointMesh', 'kPointCount', 'kPointList'],
               'cell': [['symmetry', 'symmetryFile', 'symmetryOperations'],
                        ['bulkLattice', 'filmLattice']],
               'constants': 'constant',
               'electronConfig': ['coreConfig',
                                  'valenceConfig',
                                  'stateOccupation'],
               'filmLattice': [[['a1', 'a2'],
                                ['row-1', 'row-2'],
                                'bravaisMatrix'],
                               'vacuumEnergyParameters'],
               'kPointCount': 'specialPoint',
               'kPointList': 'kPoint',
               'nocoParams': ['qss', 'qsc'],
               'species': ['mtSphere',
                           'atomicCutoffs',
                           'energyParameters',
                           'force',
                           'electronConfig',
                           'nocoParams',
                           'ldaU',
                           'lo'],
               'symOp': ['row-1', 'row-2', 'row-3'],
               'symmetryOperations': 'symOp',
               'xcFunctional': ['xcParams', 'ggaPrinting']},
 'tag_paths': {'a1': ['/fleurInput/cell/bulkLattice/a1',
                      '/fleurInput/cell/filmLattice/a1'],
               'a2': ['/fleurInput/cell/bulkLattice/a2',
                      '/fleurInput/cell/filmLattice/a2'],
               'absPos': '/fleurInput/atomGroups/atomGroup/absPos',
               'atomGroup': '/fleurInput/atomGroups/atomGroup',
               'atomGroups': '/fleurInput/atomGroups',
               'atomSpecies': '/fleurInput/atomSpecies',
               'atomicCutoffs': ['/fleurInput/atomSpecies/species/atomicCutoffs',
                                 '/fleurInput/atomGroups/atomGroup/atomicCutoffs'],
               'bravaisMatrix': ['/fleurInput/cell/bulkLattice/bravaisMatrix',
                                 '/fleurInput/cell/filmLattice/bravaisMatrix'],
               'bulkLattice': '/fleurInput/cell/bulkLattice',
               'bzIntegration': '/fleurInput/calculationSetup/bzIntegration',
               'c': '/fleurInput/cell/bulkLattice/c',
               'calculationSetup': '/fleurInput/calculationSetup',
               'cell': '/fleurInput/cell',
               'chargeDensitySlicing': '/fleurInput/output/chargeDensitySlicing',
               'checks': '/fleurInput/output/checks',
               'comment': '/fleurInput/comment',
               'constant': '/fleurInput/constants/constant',
               'constants': '/fleurInput/constants',
               'coreConfig': '/fleurInput/atomSpecies/species/electronConfig/coreConfig',
               'coreElectrons': '/fleurInput/calculationSetup/coreElectrons',
               'cutoffs': '/fleurInput/calculationSetup/cutoffs',
               'densityOfStates': '/fleurInput/output/densityOfStates',
               'eField': '/fleurInput/calculationSetup/eField',
               'electronConfig': '/fleurInput/atomSpecies/species/electronConfig',
               'energyParameterLimits': '/fleurInput/calculationSetup/energyParameterLimits',
               'energyParameters': ['/fleurInput/atomSpecies/species/energyParameters',
                                    '/fleurInput/atomGroups/atomGroup/energyParameters'],
               'expertModes': '/fleurInput/calculationSetup/expertModes',
               'filmLattice': '/fleurInput/cell/filmLattice',
               'filmPos': '/fleurInput/atomGroups/atomGroup/filmPos',
               'fleurInput': '/fleurInput',
               'force': ['/fleurInput/atomSpecies/species/force',
                         '/fleurInput/atomGroups/atomGroup/force'],
               'geometryOptimization': '/fleurInput/calculationSetup/geometryOptimization',
               'ggaPrinting': '/fleurInput/xcFunctional/ggaPrinting',
               'kPoint': '/fleurInput/calculationSetup/bzIntegration/kPointList/kPoint',
               'kPointCount': '/fleurInput/calculationSetup/bzIntegration/kPointCount',
               'kPointList': '/fleurInput/calculationSetup/bzIntegration/kPointList',
               'kPointMesh': '/fleurInput/calculationSetup/bzIntegration/kPointMesh',
               'ldaU': ['/fleurInput/atomSpecies/species/ldaU',
                        '/fleurInput/atomGroups/atomGroup/ldaU'],
               'lo': ['/fleurInput/atomSpecies/species/lo',
                      '/fleurInput/atomGroups/atomGroup/lo'],
               'magnetism': '/fleurInput/calculationSetup/magnetism',
               'mtSphere': ['/fleurInput/atomSpecies/species/mtSphere',
                            '/fleurInput/atomGroups/atomGroup/mtSphere'],
               'nocoParams': ['/fleurInput/calculationSetup/nocoParams',
                              '/fleurInput/atomSpecies/species/nocoParams',
                              '/fleurInput/atomGroups/atomGroup/nocoParams'],
               'oneDParams': '/fleurInput/calculationSetup/oneDParams',
               'orbcomprot': '/fleurInput/atomGroups/atomGroup/orbcomprot',
               'output': '/fleurInput/output',
               'plotting': '/fleurInput/output/plotting',
               'qsc': '/fleurInput/calculationSetup/nocoParams/qsc',
               'qss': '/fleurInput/calculationSetup/nocoParams/qss',
               'relPos': '/fleurInput/atomGroups/atomGroup/relPos',
               'row-1': ['/fleurInput/cell/bulkLattice/row-1',
                         '/fleurInput/cell/filmLattice/row-1',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-1',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-1',
                         '/fleurInput/cell/symmetryOperations/symOp/row-1'],
               'row-2': ['/fleurInput/cell/bulkLattice/row-2',
                         '/fleurInput/cell/filmLattice/row-2',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-2',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-2',
                         '/fleurInput/cell/symmetryOperations/symOp/row-2'],
               'row-3': ['/fleurInput/cell/bulkLattice/bravaisMatrix/row-3',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-3',
                         '/fleurInput/cell/symmetryOperations/symOp/row-3'],
               'scfLoop': '/fleurInput/calculationSetup/scfLoop',
               'soc': '/fleurInput/calculationSetup/soc',
               'specialOutput': '/fleurInput/output/specialOutput',
               'specialPoint': '/fleurInput/calculationSetup/bzIntegration/kPointCount/specialPoint',
               'species': '/fleurInput/atomSpecies/species',
               'spinSpiralQPointMesh': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
               'stateOccupation': '/fleurInput/atomSpecies/species/electronConfig/stateOccupation',
               'symOp': '/fleurInput/cell/symmetryOperations/symOp',
               'symmetry': '/fleurInput/cell/symmetry',
               'symmetryFile': '/fleurInput/cell/symmetryFile',
               'symmetryOperations': '/fleurInput/cell/symmetryOperations',
               'vacuumDOS': '/fleurInput/output/vacuumDOS',
               'vacuumEnergyParameters': '/fleurInput/cell/filmLattice/vacuumEnergyParameters',
               'valenceConfig': '/fleurInput/atomSpecies/species/electronConfig/valenceConfig',
               'xcFunctional': '/fleurInput/xcFunctional',
               'xcParams': '/fleurInput/xcFunctional/xcParams'},
 'tags_several': ['constant',
                  'symOp',
                  'vacuumEnergyParameters',
                  'species',
                  'ldaU',
                  'lo',
                  'atomGroup',
                  'relPos',
                  'absPos',
                  'filmPos',
                  'specialPoint',
                  'kPoint',
                  'stateOccupation']}
