__inp_version__ = '0.27'
schema_dict = {'attrib_paths': {'Gmax': '/fleurInput/calculationSetup/cutoffs/@Gmax',
                  'GmaxXC': '/fleurInput/calculationSetup/cutoffs/@GmaxXC',
                  'J': ['/fleurInput/atomSpecies/species/ldaU/@J',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@J'],
                  'Kmax': '/fleurInput/calculationSetup/cutoffs/@Kmax',
                  'M': ['/fleurInput/atomSpecies/species/nocoParams/@M',
                        '/fleurInput/atomGroups/atomGroup/nocoParams/@M'],
                  'MM': '/fleurInput/calculationSetup/oneDParams/@MM',
                  'U': ['/fleurInput/atomSpecies/species/ldaU/@U',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@U'],
                  'alpha': ['/fleurInput/atomSpecies/species/nocoParams/@alpha',
                            '/fleurInput/atomGroups/atomGroup/nocoParams/@alpha',
                            '/fleurInput/calculationSetup/scfLoop/@alpha'],
                  'atomicNumber': '/fleurInput/atomSpecies/species/@atomicNumber',
                  'autocomp': '/fleurInput/calculationSetup/eField/@autocomp',
                  'b_cons_x': ['/fleurInput/atomSpecies/species/nocoParams/@b_cons_x',
                               '/fleurInput/atomGroups/atomGroup/nocoParams/@b_cons_x'],
                  'b_cons_y': ['/fleurInput/atomSpecies/species/nocoParams/@b_cons_y',
                               '/fleurInput/atomGroups/atomGroup/nocoParams/@b_cons_y'],
                  'band': '/fleurInput/output/@band',
                  'beta': ['/fleurInput/atomSpecies/species/nocoParams/@beta',
                           '/fleurInput/atomGroups/atomGroup/nocoParams/@beta'],
                  'bmt': '/fleurInput/output/specialOutput/@bmt',
                  'calculate': ['/fleurInput/atomSpecies/species/force/@calculate',
                                '/fleurInput/atomGroups/atomGroup/force/@calculate'],
                  'cdinf': '/fleurInput/output/checks/@cdinf',
                  'chi': '/fleurInput/calculationSetup/oneDParams/@chi',
                  'chng': '/fleurInput/xcFunctional/xcParams/@chng',
                  'coreStates': '/fleurInput/atomSpecies/species/@coreStates',
                  'count': ['/fleurInput/calculationSetup/bzIntegration/kPointCount/@count',
                            '/fleurInput/calculationSetup/bzIntegration/kPointList/@count'],
                  'ctail': '/fleurInput/calculationSetup/coreElectrons/@ctail',
                  'd': ['/fleurInput/atomSpecies/species/energyParameters/@d',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@d'],
                  'd1': '/fleurInput/calculationSetup/oneDParams/@d1',
                  'dTilda': '/fleurInput/cell/filmLattice/@dTilda',
                  'dVac': '/fleurInput/cell/filmLattice/@dVac',
                  'dirichlet': '/fleurInput/calculationSetup/eField/@dirichlet',
                  'disp': '/fleurInput/output/checks/@disp',
                  'dos': '/fleurInput/output/@dos',
                  'eDeriv': ['/fleurInput/atomSpecies/species/lo/@eDeriv',
                             '/fleurInput/atomGroups/atomGroup/lo/@eDeriv'],
                  'eV': '/fleurInput/calculationSetup/eField/@eV',
                  'eig66': '/fleurInput/calculationSetup/expertModes/@eig66',
                  'element': '/fleurInput/atomSpecies/species/@element',
                  'ellow': '/fleurInput/calculationSetup/energyParameterLimits/@ellow',
                  'elup': '/fleurInput/calculationSetup/energyParameterLimits/@elup',
                  'eonly': '/fleurInput/output/specialOutput/@eonly',
                  'epsdisp': '/fleurInput/calculationSetup/geometryOptimization/@epsdisp',
                  'epsforce': '/fleurInput/calculationSetup/geometryOptimization/@epsforce',
                  'f': ['/fleurInput/atomSpecies/species/energyParameters/@f',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@f'],
                  'fermiSmearingEnergy': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingEnergy',
                  'fermiSmearingTemp': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingTemp',
                  'filename': '/fleurInput/cell/symmetryFile/@filename',
                  'fleurInputVersion': '/fleurInput/@fleurInputVersion',
                  'flipSpin': '/fleurInput/atomSpecies/species/@flipSpin',
                  'form66': '/fleurInput/output/specialOutput/@form66',
                  'frcor': '/fleurInput/calculationSetup/coreElectrons/@frcor',
                  'gamma': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/kPointCount/@gamma'],
                  'gridPoints': ['/fleurInput/atomSpecies/species/mtSphere/@gridPoints',
                                 '/fleurInput/atomGroups/atomGroup/mtSphere/@gridPoints'],
                  'gw': '/fleurInput/calculationSetup/expertModes/@gw',
                  'idsprs': '/fleurInput/xcFunctional/xcParams/@idsprs',
                  'idsprs0': '/fleurInput/xcFunctional/ggaPrinting/@idsprs0',
                  'idsprsi': '/fleurInput/xcFunctional/ggaPrinting/@idsprsi',
                  'idsprsl': '/fleurInput/xcFunctional/ggaPrinting/@idsprsl',
                  'idsprsv': '/fleurInput/xcFunctional/ggaPrinting/@idsprsv',
                  'iggachk': '/fleurInput/xcFunctional/ggaPrinting/@iggachk',
                  'igrd': '/fleurInput/xcFunctional/xcParams/@igrd',
                  'imix': '/fleurInput/calculationSetup/scfLoop/@imix',
                  'integ': '/fleurInput/output/vacuumDOS/@integ',
                  'invs': '/fleurInput/cell/symmetry/@invs',
                  'invs1': '/fleurInput/calculationSetup/oneDParams/@invs1',
                  'iplot': '/fleurInput/output/plotting/@iplot',
                  'isec1': '/fleurInput/calculationSetup/expertModes/@isec1',
                  'itmax': '/fleurInput/calculationSetup/scfLoop/@itmax',
                  'jspins': '/fleurInput/calculationSetup/magnetism/@jspins',
                  'kcrel': '/fleurInput/calculationSetup/coreElectrons/@kcrel',
                  'l': ['/fleurInput/atomSpecies/species/ldaU/@l',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@l',
                        '/fleurInput/atomSpecies/species/lo/@l',
                        '/fleurInput/atomGroups/atomGroup/lo/@l'],
                  'l_J': '/fleurInput/calculationSetup/magnetism/@l_J',
                  'l_amf': ['/fleurInput/atomSpecies/species/ldaU/@l_amf',
                            '/fleurInput/atomGroups/atomGroup/ldaU/@l_amf'],
                  'l_constr': '/fleurInput/calculationSetup/nocoParams/@l_constr',
                  'l_disp': '/fleurInput/calculationSetup/nocoParams/@l_disp',
                  'l_f': '/fleurInput/calculationSetup/geometryOptimization/@l_f',
                  'l_magn': ['/fleurInput/atomSpecies/species/nocoParams/@l_magn',
                             '/fleurInput/atomGroups/atomGroup/nocoParams/@l_magn'],
                  'l_mperp': '/fleurInput/calculationSetup/nocoParams/@l_mperp',
                  'l_noco': '/fleurInput/calculationSetup/magnetism/@l_noco',
                  'l_relax': ['/fleurInput/atomSpecies/species/nocoParams/@l_relax',
                              '/fleurInput/atomGroups/atomGroup/nocoParams/@l_relax'],
                  'l_soc': '/fleurInput/calculationSetup/soc/@l_soc',
                  'l_ss': '/fleurInput/calculationSetup/nocoParams/@l_ss',
                  'latnam': ['/fleurInput/cell/bulkLattice/@latnam',
                             '/fleurInput/cell/filmLattice/@latnam'],
                  'layers': '/fleurInput/output/vacuumDOS/@layers',
                  'lflip': '/fleurInput/calculationSetup/magnetism/@lflip',
                  'lmax': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lmax',
                           '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lmax'],
                  'lmaxAPW': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lmaxAPW',
                              '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lmaxAPW'],
                  'lnonsphr': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lnonsphr',
                               '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lnonsphr'],
                  'locx1': '/fleurInput/output/vacuumDOS/@locx1',
                  'locx2': '/fleurInput/output/vacuumDOS/@locx2',
                  'locy1': '/fleurInput/output/vacuumDOS/@locy1',
                  'locy2': '/fleurInput/output/vacuumDOS/@locy2',
                  'logIncrement': ['/fleurInput/atomSpecies/species/mtSphere/@logIncrement',
                                   '/fleurInput/atomGroups/atomGroup/mtSphere/@logIncrement'],
                  'lpr': '/fleurInput/calculationSetup/expertModes/@lpr',
                  'lwb': '/fleurInput/xcFunctional/xcParams/@lwb',
                  'm_cyl': '/fleurInput/calculationSetup/oneDParams/@m_cyl',
                  'magField': ['/fleurInput/atomSpecies/species/@magField',
                               '/fleurInput/atomGroups/atomGroup/@magField'],
                  'magMom': '/fleurInput/atomSpecies/species/@magMom',
                  'maxEigenval': '/fleurInput/output/chargeDensitySlicing/@maxEigenval',
                  'maxEnergy': '/fleurInput/output/densityOfStates/@maxEnergy',
                  'maxIterBroyd': '/fleurInput/calculationSetup/scfLoop/@maxIterBroyd',
                  'maxTimeToStartIter': '/fleurInput/calculationSetup/scfLoop/@maxTimeToStartIter',
                  'minDistance': '/fleurInput/calculationSetup/scfLoop/@minDistance',
                  'minEigenval': '/fleurInput/output/chargeDensitySlicing/@minEigenval',
                  'minEnergy': '/fleurInput/output/densityOfStates/@minEnergy',
                  'mix_b': '/fleurInput/calculationSetup/nocoParams/@mix_b',
                  'mode': '/fleurInput/calculationSetup/bzIntegration/@mode',
                  'n': ['/fleurInput/atomSpecies/species/lo/@n',
                        '/fleurInput/atomGroups/atomGroup/lo/@n'],
                  'name': ['/fleurInput/constants/constant/@name',
                           '/fleurInput/xcFunctional/@name',
                           '/fleurInput/atomSpecies/species/@name',
                           '/fleurInput/calculationSetup/bzIntegration/kPointCount/specialPoint/@name'],
                  'ndir': '/fleurInput/output/densityOfStates/@ndir',
                  'ndvgrd': '/fleurInput/xcFunctional/xcParams/@ndvgrd',
                  'nnne': '/fleurInput/output/chargeDensitySlicing/@nnne',
                  'nsh': '/fleurInput/calculationSetup/nocoParams/@nsh',
                  'nstars': '/fleurInput/output/vacuumDOS/@nstars',
                  'nstm': '/fleurInput/output/vacuumDOS/@nstm',
                  'numbands': '/fleurInput/calculationSetup/cutoffs/@numbands',
                  'numkpt': '/fleurInput/output/chargeDensitySlicing/@numkpt',
                  'nx': '/fleurInput/calculationSetup/bzIntegration/kPointMesh/@nx',
                  'ny': '/fleurInput/calculationSetup/bzIntegration/kPointMesh/@ny',
                  'nz': '/fleurInput/calculationSetup/bzIntegration/kPointMesh/@nz',
                  'off': '/fleurInput/calculationSetup/soc/@off',
                  'orbcomp': '/fleurInput/atomGroups/atomGroup/@orbcomp',
                  'p': ['/fleurInput/atomSpecies/species/energyParameters/@p',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@p'],
                  'pallst': '/fleurInput/output/chargeDensitySlicing/@pallst',
                  'phi': '/fleurInput/calculationSetup/soc/@phi',
                  'plot_charge': '/fleurInput/calculationSetup/eField/@plot_charge',
                  'plot_rho': '/fleurInput/calculationSetup/eField/@plot_rho',
                  'plplot': '/fleurInput/output/plotting/@plplot',
                  'posScale': '/fleurInput/calculationSetup/bzIntegration/kPointList/@posScale',
                  'pot8': '/fleurInput/calculationSetup/expertModes/@pot8',
                  'qfix': '/fleurInput/calculationSetup/geometryOptimization/@qfix',
                  'qx': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qx',
                  'qy': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qy',
                  'qz': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qz',
                  'radius': ['/fleurInput/atomSpecies/species/mtSphere/@radius',
                             '/fleurInput/atomGroups/atomGroup/mtSphere/@radius'],
                  'relativisticCorrections': '/fleurInput/xcFunctional/@relativisticCorrections',
                  'relaxXYZ': ['/fleurInput/atomSpecies/species/force/@relaxXYZ',
                               '/fleurInput/atomGroups/atomGroup/force/@relaxXYZ'],
                  'rot': '/fleurInput/calculationSetup/oneDParams/@rot',
                  's': ['/fleurInput/atomSpecies/species/energyParameters/@s',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@s'],
                  'scale': ['/fleurInput/cell/bulkLattice/@scale',
                            '/fleurInput/cell/filmLattice/@scale'],
                  'score': '/fleurInput/output/plotting/@score',
                  'secvar': '/fleurInput/calculationSetup/expertModes/@secvar',
                  'sig_b_1': '/fleurInput/calculationSetup/eField/@sig_b_1',
                  'sig_b_2': '/fleurInput/calculationSetup/eField/@sig_b_2',
                  'sigma': '/fleurInput/output/densityOfStates/@sigma',
                  'slice': '/fleurInput/output/@slice',
                  'soc66': '/fleurInput/calculationSetup/soc/@soc66',
                  'spav': '/fleurInput/calculationSetup/soc/@spav',
                  'species': '/fleurInput/atomGroups/atomGroup/@species',
                  'spgrp': '/fleurInput/cell/symmetry/@spgrp',
                  'spinDown': ['/fleurInput/cell/filmLattice/vacuumEnergyParameters/@spinDown',
                               '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@spinDown'],
                  'spinUp': ['/fleurInput/cell/filmLattice/vacuumEnergyParameters/@spinUp',
                             '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@spinUp'],
                  'spinf': '/fleurInput/calculationSetup/scfLoop/@spinf',
                  'sso_opt': '/fleurInput/calculationSetup/nocoParams/@sso_opt',
                  'star': '/fleurInput/output/vacuumDOS/@star',
                  'state': '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@state',
                  'swsp': '/fleurInput/calculationSetup/magnetism/@swsp',
                  'theta': '/fleurInput/calculationSetup/soc/@theta',
                  'thetaJ': '/fleurInput/calculationSetup/nocoParams/@thetaJ',
                  'thetad': '/fleurInput/calculationSetup/geometryOptimization/@thetad',
                  'tworkf': '/fleurInput/output/vacuumDOS/@tworkf',
                  'type': ['/fleurInput/atomSpecies/species/lo/@type',
                           '/fleurInput/atomGroups/atomGroup/lo/@type'],
                  'vM': '/fleurInput/calculationSetup/oneDParams/@vM',
                  'vacdos': '/fleurInput/output/@vacdos',
                  'vacuum': '/fleurInput/cell/filmLattice/vacuumEnergyParameters/@vacuum',
                  'valenceElectrons': '/fleurInput/calculationSetup/bzIntegration/@valenceElectrons',
                  'value': '/fleurInput/constants/constant/@value',
                  'vcaAddCharge': ['/fleurInput/atomSpecies/species/@vcaAddCharge',
                                   '/fleurInput/atomGroups/atomGroup/@vcaAddCharge'],
                  'vchk': '/fleurInput/output/checks/@vchk',
                  'weight': '/fleurInput/calculationSetup/bzIntegration/kPointList/kPoint/@weight',
                  'weightScale': '/fleurInput/calculationSetup/bzIntegration/kPointList/@weightScale',
                  'xa': '/fleurInput/calculationSetup/geometryOptimization/@xa',
                  'zrfs': '/fleurInput/cell/symmetry/@zrfs',
                  'zrfs1': '/fleurInput/calculationSetup/oneDParams/@zrfs1',
                  'zsigma': '/fleurInput/calculationSetup/eField/@zsigma'},
 'attrib_types': {'float': ['ellow',
                            'elup',
                            'zsigma',
                            'sig_b_1',
                            'sig_b_2',
                            'mix_b',
                            'thetaJ',
                            'scale',
                            'dVac',
                            'dTilda',
                            'spinUp',
                            'spinDown',
                            'chng',
                            'idsprsv',
                            'magMom',
                            'magField',
                            'vcaAddCharge',
                            'M',
                            'alpha',
                            'beta',
                            'b_cons_x',
                            'b_cons_y',
                            'radius',
                            'logIncrement',
                            'U',
                            'J',
                            'Kmax',
                            'Gmax',
                            'GmaxXC',
                            'valenceElectrons',
                            'fermiSmearingEnergy',
                            'fermiSmearingTemp',
                            'theta',
                            'phi',
                            'spinf',
                            'minDistance',
                            'maxTimeToStartIter',
                            'locx1',
                            'locy1',
                            'locx2',
                            'locy2',
                            'tworkf',
                            'minEigenval',
                            'maxEigenval',
                            'xa',
                            'thetad',
                            'epsdisp',
                            'epsforce',
                            'minEnergy',
                            'maxEnergy',
                            'sigma',
                            'posScale',
                            'weightScale',
                            'weight'],
                  'int': ['nsh',
                          'MM',
                          'vM',
                          'm_cyl',
                          'chi',
                          'rot',
                          'kcrel',
                          'jspins',
                          'vacuum',
                          'igrd',
                          'ndvgrd',
                          'idsprs',
                          'iggachk',
                          'idsprs0',
                          'idsprsl',
                          'idsprsi',
                          'atomicNumber',
                          'coreStates',
                          'gridPoints',
                          'lmax',
                          'lnonsphr',
                          'lmaxAPW',
                          's',
                          'p',
                          'd',
                          'f',
                          'l',
                          'n',
                          'eDeriv',
                          'itmax',
                          'maxIterBroyd',
                          'layers',
                          'nstars',
                          'nstm',
                          'numkpt',
                          'nnne',
                          'ndir',
                          'nx',
                          'ny',
                          'nz',
                          'count',
                          'qx',
                          'qy',
                          'qz',
                          'gw',
                          'lpr',
                          'isec1'],
                  'other': [],
                  'string': ['fleurInputVersion',
                             'name',
                             'value',
                             'sso_opt',
                             'spgrp',
                             'filename',
                             'latnam',
                             'element',
                             'species',
                             'relaxXYZ',
                             'type',
                             'numbands',
                             'mode',
                             'imix',
                             'state'],
                  'switch': ['plot_charge',
                             'plot_rho',
                             'autocomp',
                             'dirichlet',
                             'eV',
                             'l_ss',
                             'l_mperp',
                             'l_constr',
                             'l_disp',
                             'd1',
                             'invs1',
                             'zrfs1',
                             'ctail',
                             'frcor',
                             'invs',
                             'zrfs',
                             'l_noco',
                             'l_J',
                             'swsp',
                             'lflip',
                             'relativisticCorrections',
                             'lwb',
                             'flipSpin',
                             'orbcomp',
                             'l_relax',
                             'l_magn',
                             'l_amf',
                             'calculate',
                             'l_soc',
                             'spav',
                             'off',
                             'soc66',
                             'integ',
                             'star',
                             'iplot',
                             'score',
                             'plplot',
                             'pallst',
                             'l_f',
                             'qfix',
                             'gamma',
                             'pot8',
                             'eig66',
                             'secvar',
                             'vchk',
                             'cdinf',
                             'disp',
                             'form66',
                             'eonly',
                             'bmt',
                             'dos',
                             'band',
                             'vacdos',
                             'slice']},
 'settable_attribs': {'Gmax': '/fleurInput/calculationSetup/cutoffs/@Gmax',
                      'GmaxXC': '/fleurInput/calculationSetup/cutoffs/@GmaxXC',
                      'Kmax': '/fleurInput/calculationSetup/cutoffs/@Kmax',
                      'MM': '/fleurInput/calculationSetup/oneDParams/@MM',
                      'autocomp': '/fleurInput/calculationSetup/eField/@autocomp',
                      'band': '/fleurInput/output/@band',
                      'bmt': '/fleurInput/output/specialOutput/@bmt',
                      'cdinf': '/fleurInput/output/checks/@cdinf',
                      'chi': '/fleurInput/calculationSetup/oneDParams/@chi',
                      'chng': '/fleurInput/xcFunctional/xcParams/@chng',
                      'ctail': '/fleurInput/calculationSetup/coreElectrons/@ctail',
                      'd1': '/fleurInput/calculationSetup/oneDParams/@d1',
                      'dTilda': '/fleurInput/cell/filmLattice/@dTilda',
                      'dVac': '/fleurInput/cell/filmLattice/@dVac',
                      'dirichlet': '/fleurInput/calculationSetup/eField/@dirichlet',
                      'disp': '/fleurInput/output/checks/@disp',
                      'dos': '/fleurInput/output/@dos',
                      'eV': '/fleurInput/calculationSetup/eField/@eV',
                      'eig66': '/fleurInput/calculationSetup/expertModes/@eig66',
                      'ellow': '/fleurInput/calculationSetup/energyParameterLimits/@ellow',
                      'elup': '/fleurInput/calculationSetup/energyParameterLimits/@elup',
                      'eonly': '/fleurInput/output/specialOutput/@eonly',
                      'epsdisp': '/fleurInput/calculationSetup/geometryOptimization/@epsdisp',
                      'epsforce': '/fleurInput/calculationSetup/geometryOptimization/@epsforce',
                      'fermiSmearingEnergy': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingEnergy',
                      'fermiSmearingTemp': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingTemp',
                      'filename': '/fleurInput/cell/symmetryFile/@filename',
                      'fleurInputVersion': '/fleurInput/@fleurInputVersion',
                      'form66': '/fleurInput/output/specialOutput/@form66',
                      'frcor': '/fleurInput/calculationSetup/coreElectrons/@frcor',
                      'gw': '/fleurInput/calculationSetup/expertModes/@gw',
                      'idsprs': '/fleurInput/xcFunctional/xcParams/@idsprs',
                      'idsprs0': '/fleurInput/xcFunctional/ggaPrinting/@idsprs0',
                      'idsprsi': '/fleurInput/xcFunctional/ggaPrinting/@idsprsi',
                      'idsprsl': '/fleurInput/xcFunctional/ggaPrinting/@idsprsl',
                      'idsprsv': '/fleurInput/xcFunctional/ggaPrinting/@idsprsv',
                      'iggachk': '/fleurInput/xcFunctional/ggaPrinting/@iggachk',
                      'igrd': '/fleurInput/xcFunctional/xcParams/@igrd',
                      'imix': '/fleurInput/calculationSetup/scfLoop/@imix',
                      'integ': '/fleurInput/output/vacuumDOS/@integ',
                      'invs': '/fleurInput/cell/symmetry/@invs',
                      'invs1': '/fleurInput/calculationSetup/oneDParams/@invs1',
                      'iplot': '/fleurInput/output/plotting/@iplot',
                      'isec1': '/fleurInput/calculationSetup/expertModes/@isec1',
                      'itmax': '/fleurInput/calculationSetup/scfLoop/@itmax',
                      'jspins': '/fleurInput/calculationSetup/magnetism/@jspins',
                      'kcrel': '/fleurInput/calculationSetup/coreElectrons/@kcrel',
                      'l_J': '/fleurInput/calculationSetup/magnetism/@l_J',
                      'l_constr': '/fleurInput/calculationSetup/nocoParams/@l_constr',
                      'l_disp': '/fleurInput/calculationSetup/nocoParams/@l_disp',
                      'l_f': '/fleurInput/calculationSetup/geometryOptimization/@l_f',
                      'l_mperp': '/fleurInput/calculationSetup/nocoParams/@l_mperp',
                      'l_noco': '/fleurInput/calculationSetup/magnetism/@l_noco',
                      'l_soc': '/fleurInput/calculationSetup/soc/@l_soc',
                      'l_ss': '/fleurInput/calculationSetup/nocoParams/@l_ss',
                      'layers': '/fleurInput/output/vacuumDOS/@layers',
                      'lflip': '/fleurInput/calculationSetup/magnetism/@lflip',
                      'locx1': '/fleurInput/output/vacuumDOS/@locx1',
                      'locx2': '/fleurInput/output/vacuumDOS/@locx2',
                      'locy1': '/fleurInput/output/vacuumDOS/@locy1',
                      'locy2': '/fleurInput/output/vacuumDOS/@locy2',
                      'lpr': '/fleurInput/calculationSetup/expertModes/@lpr',
                      'lwb': '/fleurInput/xcFunctional/xcParams/@lwb',
                      'm_cyl': '/fleurInput/calculationSetup/oneDParams/@m_cyl',
                      'maxEigenval': '/fleurInput/output/chargeDensitySlicing/@maxEigenval',
                      'maxEnergy': '/fleurInput/output/densityOfStates/@maxEnergy',
                      'maxIterBroyd': '/fleurInput/calculationSetup/scfLoop/@maxIterBroyd',
                      'maxTimeToStartIter': '/fleurInput/calculationSetup/scfLoop/@maxTimeToStartIter',
                      'minDistance': '/fleurInput/calculationSetup/scfLoop/@minDistance',
                      'minEigenval': '/fleurInput/output/chargeDensitySlicing/@minEigenval',
                      'minEnergy': '/fleurInput/output/densityOfStates/@minEnergy',
                      'mix_b': '/fleurInput/calculationSetup/nocoParams/@mix_b',
                      'mode': '/fleurInput/calculationSetup/bzIntegration/@mode',
                      'ndir': '/fleurInput/output/densityOfStates/@ndir',
                      'ndvgrd': '/fleurInput/xcFunctional/xcParams/@ndvgrd',
                      'nnne': '/fleurInput/output/chargeDensitySlicing/@nnne',
                      'nsh': '/fleurInput/calculationSetup/nocoParams/@nsh',
                      'nstars': '/fleurInput/output/vacuumDOS/@nstars',
                      'nstm': '/fleurInput/output/vacuumDOS/@nstm',
                      'numbands': '/fleurInput/calculationSetup/cutoffs/@numbands',
                      'numkpt': '/fleurInput/output/chargeDensitySlicing/@numkpt',
                      'nx': '/fleurInput/calculationSetup/bzIntegration/kPointMesh/@nx',
                      'ny': '/fleurInput/calculationSetup/bzIntegration/kPointMesh/@ny',
                      'nz': '/fleurInput/calculationSetup/bzIntegration/kPointMesh/@nz',
                      'off': '/fleurInput/calculationSetup/soc/@off',
                      'pallst': '/fleurInput/output/chargeDensitySlicing/@pallst',
                      'phi': '/fleurInput/calculationSetup/soc/@phi',
                      'plot_charge': '/fleurInput/calculationSetup/eField/@plot_charge',
                      'plot_rho': '/fleurInput/calculationSetup/eField/@plot_rho',
                      'plplot': '/fleurInput/output/plotting/@plplot',
                      'posScale': '/fleurInput/calculationSetup/bzIntegration/kPointList/@posScale',
                      'pot8': '/fleurInput/calculationSetup/expertModes/@pot8',
                      'qfix': '/fleurInput/calculationSetup/geometryOptimization/@qfix',
                      'qx': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qx',
                      'qy': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qy',
                      'qz': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qz',
                      'relativisticCorrections': '/fleurInput/xcFunctional/@relativisticCorrections',
                      'rot': '/fleurInput/calculationSetup/oneDParams/@rot',
                      'score': '/fleurInput/output/plotting/@score',
                      'secvar': '/fleurInput/calculationSetup/expertModes/@secvar',
                      'sig_b_1': '/fleurInput/calculationSetup/eField/@sig_b_1',
                      'sig_b_2': '/fleurInput/calculationSetup/eField/@sig_b_2',
                      'sigma': '/fleurInput/output/densityOfStates/@sigma',
                      'slice': '/fleurInput/output/@slice',
                      'soc66': '/fleurInput/calculationSetup/soc/@soc66',
                      'spav': '/fleurInput/calculationSetup/soc/@spav',
                      'spgrp': '/fleurInput/cell/symmetry/@spgrp',
                      'spinf': '/fleurInput/calculationSetup/scfLoop/@spinf',
                      'sso_opt': '/fleurInput/calculationSetup/nocoParams/@sso_opt',
                      'star': '/fleurInput/output/vacuumDOS/@star',
                      'swsp': '/fleurInput/calculationSetup/magnetism/@swsp',
                      'theta': '/fleurInput/calculationSetup/soc/@theta',
                      'thetaJ': '/fleurInput/calculationSetup/nocoParams/@thetaJ',
                      'thetad': '/fleurInput/calculationSetup/geometryOptimization/@thetad',
                      'tworkf': '/fleurInput/output/vacuumDOS/@tworkf',
                      'vM': '/fleurInput/calculationSetup/oneDParams/@vM',
                      'vacdos': '/fleurInput/output/@vacdos',
                      'valenceElectrons': '/fleurInput/calculationSetup/bzIntegration/@valenceElectrons',
                      'vchk': '/fleurInput/output/checks/@vchk',
                      'weightScale': '/fleurInput/calculationSetup/bzIntegration/kPointList/@weightScale',
                      'xa': '/fleurInput/calculationSetup/geometryOptimization/@xa',
                      'zrfs': '/fleurInput/cell/symmetry/@zrfs',
                      'zrfs1': '/fleurInput/calculationSetup/oneDParams/@zrfs1',
                      'zsigma': '/fleurInput/calculationSetup/eField/@zsigma'},
 'simple_elements': {'a1': {'length': 1, 'type': 'float'},
                     'a2': {'length': 1, 'type': 'float'},
                     'absPos': {'length': 3, 'type': 'string'},
                     'c': {'length': 1, 'type': 'float'},
                     'comment': {'length': 1, 'type': 'string'},
                     'coreConfig': {'length': 'unbounded', 'type': 'string'},
                     'filmPos': {'length': 3, 'type': 'string'},
                     'kPoint': {'length': 3, 'type': 'float'},
                     'orbcomprot': {'length': 3, 'type': 'float'},
                     'qsc': {'length': 3, 'type': 'float'},
                     'qss': {'length': 3, 'type': 'float'},
                     'relPos': {'length': 3, 'type': 'string'},
                     'row-1': [{'length': 2, 'type': 'string'},
                               {'length': 3, 'type': 'string'},
                               {'length': 4, 'type': 'float'}],
                     'row-2': [{'length': 2, 'type': 'string'},
                               {'length': 3, 'type': 'string'},
                               {'length': 4, 'type': 'float'}],
                     'row-3': [{'length': 3, 'type': 'string'},
                               {'length': 4, 'type': 'float'}],
                     'specialPoint': {'length': 3, 'type': 'float'},
                     'valenceConfig': {'length': 'unbounded',
                                       'type': 'string'}},
 'tag_order': {'atomGroup': [['relPos', 'absPos', 'filmPos'],
                             'mtSphere',
                             'atomicCutoffs',
                             'energyParameters',
                             'force',
                             'nocoParams',
                             'ldaU',
                             'lo',
                             'orbcomprot'],
               'atomGroups': 'atomGroup',
               'atomSpecies': 'species',
               'bravaisMatrix': ['row-1', 'row-2', 'row-3'],
               'bulkLattice': [['a1', 'a2', 'c'],
                               ['row-1', 'row-2', 'c'],
                               'bravaisMatrix'],
               'bzIntegration': ['kPointMesh', 'kPointCount', 'kPointList'],
               'cell': [['symmetry', 'symmetryFile', 'symmetryOperations'],
                        ['bulkLattice', 'filmLattice']],
               'constants': 'constant',
               'electronConfig': ['coreConfig',
                                  'valenceConfig',
                                  'stateOccupation'],
               'filmLattice': [[['a1', 'a2'],
                                ['row-1', 'row-2'],
                                'bravaisMatrix'],
                               'vacuumEnergyParameters'],
               'kPointCount': 'specialPoint',
               'kPointList': 'kPoint',
               'nocoParams': ['qss', 'qsc'],
               'species': ['mtSphere',
                           'atomicCutoffs',
                           'energyParameters',
                           'force',
                           'electronConfig',
                           'nocoParams',
                           'ldaU',
                           'lo'],
               'symOp': ['row-1', 'row-2', 'row-3'],
               'symmetryOperations': 'symOp',
               'xcFunctional': ['xcParams', 'ggaPrinting']},
 'tag_paths': {'a1': ['/fleurInput/cell/bulkLattice/a1',
                      '/fleurInput/cell/filmLattice/a1'],
               'a2': ['/fleurInput/cell/bulkLattice/a2',
                      '/fleurInput/cell/filmLattice/a2'],
               'absPos': '/fleurInput/atomGroups/atomGroup/absPos',
               'atomGroup': '/fleurInput/atomGroups/atomGroup',
               'atomGroups': '/fleurInput/atomGroups',
               'atomSpecies': '/fleurInput/atomSpecies',
               'atomicCutoffs': ['/fleurInput/atomSpecies/species/atomicCutoffs',
                                 '/fleurInput/atomGroups/atomGroup/atomicCutoffs'],
               'bravaisMatrix': ['/fleurInput/cell/bulkLattice/bravaisMatrix',
                                 '/fleurInput/cell/filmLattice/bravaisMatrix'],
               'bulkLattice': '/fleurInput/cell/bulkLattice',
               'bzIntegration': '/fleurInput/calculationSetup/bzIntegration',
               'c': ['/fleurInput/cell/bulkLattice/c',
                     '/fleurInput/cell/bulkLattice/c'],
               'calculationSetup': '/fleurInput/calculationSetup',
               'cell': '/fleurInput/cell',
               'chargeDensitySlicing': '/fleurInput/output/chargeDensitySlicing',
               'checks': '/fleurInput/output/checks',
               'comment': '/fleurInput/comment',
               'constant': '/fleurInput/constants/constant',
               'constants': '/fleurInput/constants',
               'coreConfig': '/fleurInput/atomSpecies/species/electronConfig/coreConfig',
               'coreElectrons': '/fleurInput/calculationSetup/coreElectrons',
               'cutoffs': '/fleurInput/calculationSetup/cutoffs',
               'densityOfStates': '/fleurInput/output/densityOfStates',
               'eField': '/fleurInput/calculationSetup/eField',
               'electronConfig': '/fleurInput/atomSpecies/species/electronConfig',
               'energyParameterLimits': '/fleurInput/calculationSetup/energyParameterLimits',
               'energyParameters': ['/fleurInput/atomSpecies/species/energyParameters',
                                    '/fleurInput/atomGroups/atomGroup/energyParameters'],
               'expertModes': '/fleurInput/calculationSetup/expertModes',
               'filmLattice': '/fleurInput/cell/filmLattice',
               'filmPos': '/fleurInput/atomGroups/atomGroup/filmPos',
               'fleurInput': '/fleurInput',
               'force': ['/fleurInput/atomSpecies/species/force',
                         '/fleurInput/atomGroups/atomGroup/force'],
               'geometryOptimization': '/fleurInput/calculationSetup/geometryOptimization',
               'ggaPrinting': '/fleurInput/xcFunctional/ggaPrinting',
               'kPoint': '/fleurInput/calculationSetup/bzIntegration/kPointList/kPoint',
               'kPointCount': '/fleurInput/calculationSetup/bzIntegration/kPointCount',
               'kPointList': '/fleurInput/calculationSetup/bzIntegration/kPointList',
               'kPointMesh': '/fleurInput/calculationSetup/bzIntegration/kPointMesh',
               'ldaU': ['/fleurInput/atomSpecies/species/ldaU',
                        '/fleurInput/atomGroups/atomGroup/ldaU'],
               'lo': ['/fleurInput/atomSpecies/species/lo',
                      '/fleurInput/atomGroups/atomGroup/lo'],
               'magnetism': '/fleurInput/calculationSetup/magnetism',
               'mtSphere': ['/fleurInput/atomSpecies/species/mtSphere',
                            '/fleurInput/atomGroups/atomGroup/mtSphere'],
               'nocoParams': ['/fleurInput/calculationSetup/nocoParams',
                              '/fleurInput/atomSpecies/species/nocoParams',
                              '/fleurInput/atomGroups/atomGroup/nocoParams'],
               'oneDParams': '/fleurInput/calculationSetup/oneDParams',
               'orbcomprot': '/fleurInput/atomGroups/atomGroup/orbcomprot',
               'output': '/fleurInput/output',
               'plotting': '/fleurInput/output/plotting',
               'qsc': '/fleurInput/calculationSetup/nocoParams/qsc',
               'qss': '/fleurInput/calculationSetup/nocoParams/qss',
               'relPos': '/fleurInput/atomGroups/atomGroup/relPos',
               'row-1': ['/fleurInput/cell/bulkLattice/row-1',
                         '/fleurInput/cell/filmLattice/row-1',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-1',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-1',
                         '/fleurInput/cell/symmetryOperations/symOp/row-1'],
               'row-2': ['/fleurInput/cell/bulkLattice/row-2',
                         '/fleurInput/cell/filmLattice/row-2',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-2',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-2',
                         '/fleurInput/cell/symmetryOperations/symOp/row-2'],
               'row-3': ['/fleurInput/cell/bulkLattice/bravaisMatrix/row-3',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-3',
                         '/fleurInput/cell/symmetryOperations/symOp/row-3'],
               'scfLoop': '/fleurInput/calculationSetup/scfLoop',
               'soc': '/fleurInput/calculationSetup/soc',
               'specialOutput': '/fleurInput/output/specialOutput',
               'specialPoint': '/fleurInput/calculationSetup/bzIntegration/kPointCount/specialPoint',
               'species': '/fleurInput/atomSpecies/species',
               'spinSpiralQPointMesh': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
               'stateOccupation': '/fleurInput/atomSpecies/species/electronConfig/stateOccupation',
               'symOp': '/fleurInput/cell/symmetryOperations/symOp',
               'symmetry': '/fleurInput/cell/symmetry',
               'symmetryFile': '/fleurInput/cell/symmetryFile',
               'symmetryOperations': '/fleurInput/cell/symmetryOperations',
               'vacuumDOS': '/fleurInput/output/vacuumDOS',
               'vacuumEnergyParameters': '/fleurInput/cell/filmLattice/vacuumEnergyParameters',
               'valenceConfig': '/fleurInput/atomSpecies/species/electronConfig/valenceConfig',
               'xcFunctional': '/fleurInput/xcFunctional',
               'xcParams': '/fleurInput/xcFunctional/xcParams'},
 'tags_several': ['constant',
                  'symOp',
                  'vacuumEnergyParameters',
                  'species',
                  'ldaU',
                  'lo',
                  'atomGroup',
                  'specialPoint',
                  'kPoint',
                  'stateOccupation']}
