#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: SiScLab_AiiDa_Installation_Notes
#+DATE: <2018-11-11 Sun>
#+AUTHOR: Johannes Wasmer
#+EMAIL: johannes@joe-9470m
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.2.2 (Org mode 9.1.13)

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+LATEX_COMPILER: pdflatex
#+DATE: \today

* [[file:SiScLab_Notes.org][Master File]]
* <2019-02-15 Fri> PyPi Install of [[https://pypi.org/project/aiidalab/][aiidalab]]

#+BEGIN_SRC shell
# create a conda env for trying out aiidalab
conda create -n masci-tools-deploy python=2.7.15 pip
conda activate masci-tools-deploy
pip install aiidalab
# some version warnings; see install_log output below

# from quantum mobile virtual machine,
# copy the folder /project to the host to /project
# (needed cause aiidalab scripts are hardcoded for that folder)
sudo cp -R ~/ownCloud/SiSc/18W/SiScLab/project/ /
sudo chown -R $USER /project
# start aiidalab/hub server/notebook
/project/apps/start.sh 
history
#+END_SRC

:aiidalab_install_log:
some version warnings; if problems, try reinstall with versions specified here
#+BEGIN_EXAMPLE
Successfully built bokeh functools32 nglview dulwich aiida-fleur tornado
aiida-raspa pycifrw aiida-siesta aiida-cp2k pandocfilters PyYAML future
subprocess32 pymatgen pgtest sympy masci-tools simplegeneric psutil alembic
SQLAlchemy validate-email ete3 click-plugins aldjemy billiard tabulate ujson
tzlocal click-spinner anyjson SQLAlchemy-Utils itsdangerous Pattern Flask-Cache
prometheus-client Send2Trash monty pydispatcher networkx mpmath scandir Mako
frozendict Tempita pycparser

aiida-core 0.12.2 has requirement click==6.7, but you'll have click 7.0 which is incompatible.
aiida-core 0.12.2 has requirement future==0.16.0, but you'll have future 0.17.1 which is incompatible.
aiida-core 0.12.2 has requirement numpy==1.14.3, but you'll have numpy 1.15.4 which is incompatible.
aiida-core 0.12.2 has requirement paramiko==2.4.1, but you'll have paramiko 2.4.2 which is incompatible.
aiida-core 0.12.2 has requirement pathlib2==2.3.0, but you'll have pathlib2 2.3.3 which is incompatible.
aiida-core 0.12.2 has requirement python-dateutil==2.7.2, but you'll have python-dateutil 2.7.3 which is incompatible.
aiida-core 0.12.2 has requirement PyYAML==3.12, but you'll have pyyaml 3.13 which is incompatible.
aiida-core 0.12.2 has requirement reentry==1.2.0, but you'll have reentry 1.2.2 which is incompatible.
aiida-core 0.12.2 has requirement voluptuous==0.11.1, but you'll have voluptuous 0.11.5 which is incompatible.
Installing collected packages: PyYAML, MarkupSafe, Jinja2, pillow, pyparsing, packaging, singledispatch, backports-abc, tornado, futures, bokeh, functools32, jsonschema, enum34, ipython-genutils, decorator, traitlets, jupyter-core, nbformat, pyzmq, jupyter-client, future, psutil, chainmap, click, voluptuous, django, django-extensions, scandir, pathlib2, reentry, SQLAlchemy, Mako, python-editor, alembic, python-mimeparse, ecdsa, pytz, validate-email, ete3, click-plugins, aldjemy, billiard, tabulate, passlib, backports.shutil-get-terminal-size, simplegeneric, ptyprocess, pexpect, wcwidth, prompt-toolkit, pickleshare, ipython, frozendict, plumpy, psycopg2-binary, amqp, anyjson, kombu, celery, ujson, tzlocal, portalocker, click-spinner, asn1crypto, pycparser, cffi, ipaddress, cryptography, pynacl, pyasn1, bcrypt, paramiko, SQLAlchemy-Utils, meld3, uritools, spglib, seekpath, urllib3, chardet, idna, requests, ruamel.ordereddict, ruamel.yaml, monty, pydispatcher, networkx, subprocess32, cycler, backports.functools-lru-cache, kiwisolver, matplotlib, palettable, mpmath, sympy, pymatgen, pycifrw, PyMySQL, qe-tools, Werkzeug, itsdangerous, Flask, ase, Flask-HTTPAuth, python-memcached, aniso8601, Flask-RESTful, marshmallow, flask-marshmallow, sqlparse, pbr, Tempita, sqlalchemy-migrate, Flask-Cors, Flask-SQLAlchemy, Pattern, marshmallow-sqlalchemy, Flask-Cache, aiida-core, aiida-wannier90, ipykernel, terminado, prometheus-client, configparser, entrypoints, webencodings, bleach, pandocfilters, testpath, defusedxml, mistune, nbconvert, Send2Trash, notebook, widgetsnbextension, ipywidgets, nglview, aiida-ase, aiida-quantumespresso, aiida-yambo, dulwich, traittypes, bqplot, markdown, ipympl, poyo, arrow, jinja2-time, whichcraft, binaryornot, cookiecutter, lxml, parsevasp, py, aiida-vasp, aiida-codtools, aiida-nwchem, aiida, aiida-gudhi, coverage, atomicwrites, pluggy, attrs, more-itertools, funcsigs, pytest, pytest-cov, pg8000, pgtest, masci-tools, aiida-fleur, fileupload, aiida-phtools, aiida-raspa, ipydatawidgets, pythreejs, html5lib, aiidalab-widgets-base, appmode-aiidalab, aiida-siesta, aiida-cp2k, pip, aiida-zeopp, aiidalab
  Found existing installation: pytz 2018.5
    Uninstalling pytz-2018.5:
      Successfully uninstalled pytz-2018.5
  Found existing installation: pip 19.0.1
    Uninstalling pip-19.0.1:
      Successfully uninstalled pip-19.0.1
Successfully installed Flask-1.0.2 Flask-Cache-0.13.1 Flask-Cors-3.0.4
Flask-HTTPAuth-3.2.3 Flask-RESTful-0.3.6 Flask-SQLAlchemy-2.3.2 Jinja2-2.10
Mako-1.0.7 MarkupSafe-1.1.0 Pattern-2.6 PyMySQL-0.8.0 PyYAML-3.13
SQLAlchemy-1.0.19 SQLAlchemy-Utils-0.33.0 Send2Trash-1.5.0 Tempita-0.5.2
Werkzeug-0.14.1 aiida-0.12.2 aiida-ase-1.0.1 aiida-codtools-1.0.1
aiida-core-0.12.2 aiida-cp2k-0.9 aiida-fleur-0.6.2 aiida-gudhi-0.1.0a3
aiida-nwchem-1.0.2 aiida-phtools-0.1.0a1 aiida-quantumespresso-2.1.0
aiida-raspa-0.3.1 aiida-siesta-0.9.10 aiida-vasp-0.2.4 aiida-wannier90-1.0.0
aiida-yambo-0.2.5 aiida-zeopp-0.2.0 aiidalab-19.2.0
aiidalab-widgets-base-0.2.0a2 aldjemy-0.8.0 alembic-0.9.9 amqp-1.4.9
aniso8601-4.1.0 anyjson-0.3.3 appmode-aiidalab-0.4.0.1 arrow-0.13.1 ase-3.17.0
asn1crypto-0.24.0 atomicwrites-1.3.0 attrs-18.2.0 backports-abc-0.5
backports.functools-lru-cache-1.5 backports.shutil-get-terminal-size-1.0.0
bcrypt-3.1.6 billiard-3.3.0.23 binaryornot-0.4.4 bleach-3.1.0 bokeh-1.0.4
bqplot-0.11.5 celery-3.1.25 cffi-1.12.0 chainmap-1.0.2 chardet-3.0.4 click-7.0
click-plugins-1.0.3 click-spinner-0.1.7 configparser-3.7.1 cookiecutter-1.6.0
coverage-4.5.2 cryptography-2.5 cycler-0.10.0 decorator-4.3.2 defusedxml-0.5.0
django-1.7.11 django-extensions-1.5.0 dulwich-0.19.11 ecdsa-0.13 entrypoints-0.3
enum34-1.1.6 ete3-3.1.1 fileupload-0.1.5 flask-marshmallow-0.9.0 frozendict-1.2
funcsigs-1.0.2 functools32-3.2.3.post2 future-0.17.1 futures-3.2.0
html5lib-1.0.1 idna-2.8 ipaddress-1.0.22 ipydatawidgets-4.0.0 ipykernel-4.10.0
ipympl-0.2.1 ipython-5.8.0 ipython-genutils-0.2.0 ipywidgets-7.4.2
itsdangerous-0.24 jinja2-time-0.2.0 jsonschema-2.6.0 jupyter-client-5.2.4
jupyter-core-4.4.0 kiwisolver-1.0.1 kombu-3.0.37 lxml-4.3.1 markdown-3.0.1
marshmallow-2.18.0 marshmallow-sqlalchemy-0.13.2 masci-tools-0.2.0
matplotlib-2.2.3 meld3-1.0.2 mistune-0.8.4 monty-1.0.5 more-itertools-5.0.0
mpmath-1.1.0 nbconvert-5.4.1 nbformat-4.4.0 networkx-2.2 nglview-1.1.8
notebook-5.7.4 packaging-19.0 palettable-3.1.1 pandocfilters-1.4.2
paramiko-2.4.2 parsevasp-0.2.22 passlib-1.7.1 pathlib2-2.3.3 pbr-5.1.2
pexpect-4.6.0 pg8000-1.12.5 pgtest-1.1.0 pickleshare-0.7.5 pillow-5.4.1 pip-18.1
pluggy-0.8.1 plumpy-0.7.12 portalocker-1.1.0 poyo-0.4.2 prometheus-client-0.5.0
prompt-toolkit-1.0.15 psutil-5.4.5 psycopg2-binary-2.7.4 ptyprocess-0.6.0
py-1.7.0 pyasn1-0.4.5 pycifrw-4.4 pycparser-2.19 pydispatcher-2.0.5
pymatgen-2019.2.4 pynacl-1.3.0 pyparsing-2.3.1 pytest-4.2.1 pytest-cov-2.6.1
python-editor-1.0.4 python-memcached-1.59 python-mimeparse-1.6.0 pythreejs-2.0.2
pytz-2018.4 pyzmq-17.1.2 qe-tools-1.1.0 reentry-1.2.2 requests-2.21.0
ruamel.ordereddict-0.4.13 ruamel.yaml-0.15.88 scandir-1.9.0 seekpath-1.8.1
simplegeneric-0.8.1 singledispatch-3.4.0.3 spglib-1.10.3.65
sqlalchemy-migrate-0.11.0 sqlparse-0.2.4 subprocess32-3.5.3 sympy-1.3
tabulate-0.8.2 terminado-0.8.1 testpath-0.4.2 tornado-4.5.3 traitlets-4.3.2
traittypes-0.2.1 tzlocal-1.5.1 ujson-1.35 uritools-2.1.0 urllib3-1.24.1
validate-email-1.3 voluptuous-0.11.5 wcwidth-0.1.7 webencodings-0.5.1
whichcraft-0.5.2 widgetsnbextension-3.4.2
#+END_EXAMPLE
:END:

* <2018-11-30 Fr> Installation of AiiDa on own system Kubuntu18.04

* <2018-11-11 Sun> STALLED 'Installation' of Quantum Mobile VM [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.10.0RC1][v18.10.0RC1]], [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.06.0][v18.6.0]] 
- version [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.10.0RC1][v18.10.0RC1]] is a release candidate, see [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.10.0RC1][qm vm releases]]. If not working, try
  [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.06.0][v18.6.0]] instead.
  - Rationale for trying out the newer unstable version first: has aiida-fleur
    v0.6.2, older version has aiida-fleur v0.6.0.
** DONE Install VirtualBox current version under (K)Ubuntu 18.04
   CLOSED: [2018-11-11 Sun 15:52]
*** Intro, Instruction URLs
- Problem: system VirtualBox is version 5.2.10, but qm vm [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.10.0RC1][v18.10.0RC1]] needs
  version 5.2.18, [[https://github.com/marvel-nccr/quantum-mobile/releases/tag/18.06.0][v18.6.0]] needs version 5.2.12.
- Sidenote JW: did this on <2018-11-11 Sun>, worked. the process installed VB
  version 5.2.22.
- Instructions used for installing current version on Ubuntu 18.04/16:
  [[https://linuxize.com/post/how-to-install-virtualbox-on-ubuntu-18-04/][instructionA]], [[https://websiteforstudents.com/install-the-latest-virtualbox-on-ubuntu-18-04-lts/][instructionB]]. The [[https://github.com/marvel-nccr/quantum-mobile/wiki/Frequently-Asked-Questions][instructionC=qm vm FAQ]] has also some (shorter)
  instructions.
- Sidenote JW: for my computer, VMs are stored on a separate HD partition
  [[file:/media/sams250g/johannes/VirtualBox%20VMs/][/media/sams250g/johannes/VirtualBox 20VMs]]
*** Execution
- import GPG keys of Orcacle VB repo. Should return 'OK'.
  #+BEGIN_SRC shell
  wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -  
  #+END_SRC
- add the VirtualBox repository with the add-apt-repository command as shown below:
  - instructionA says:
    #+BEGIN_SRC shell
    sudo add-apt-repository "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib"
    #+END_SRC
  - instructionB says:
    #+BEGIN_SRC shell
    sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list.d/virtualbox.list'
    #+END_SRC
  - seems that both do the same. used instructionA. ~arch=amd64~ is okay, even
    if your ~uname -m~ returns =x86_64=.
- instructionB has an additional step here: "you may want to remove older
  versions of the software if you’re still running it… to do that, run the
  commands below:"
  #+BEGIN_SRC shell
  sudo apt remove virtualbox virtualbox-5.1
  #+END_SRC
  - JW Sidenote: ~apt~ offers just =virtualbox=. Es gab dabei ein paar Fehler.
    Komischerweise steht da auch version 5.2.22. Im VB GUI stand aber 5.2.10???
    Naja, egal, jedenfalls ist =virtualbox= nicht mehr auf dem Pfad.
    #+BEGIN_EXAMPLE
    johannes@joe-9470m:~$ sudo apt remove virtualbox
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      dkms libgsoap-2.8.60 libsdl-ttf2.0-0 libvncserver1 virtualbox-5.2 virtualbox-dkms
    Use 'sudo apt autoremove' to remove them.
    The following additional packages will be installed:
      libsdl-ttf2.0-0 virtualbox-5.2
    The following packages will be REMOVED:
      virtualbox virtualbox-ext-pack virtualbox-guest-additions-iso virtualbox-qt
    The following NEW packages will be installed:
      libsdl-ttf2.0-0 virtualbox-5.2
    0 upgraded, 2 newly installed, 4 to remove and 0 not upgraded.
    Need to get 68.2 MB of archives.
    After this operation, 1236 kB of additional disk space will be used.
    Do you want to continue? [Y/n] y
    Get:1 http://download.virtualbox.org/virtualbox/debian bionic/contrib amd64 virtualbox-5.2 amd64 5.2.22-126460~Ubuntu~bionic [68.1 MB]
    Get:2 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 libsdl-ttf2.0-0 amd64 2.0.11-4 [15.0 kB]
    Fetched 68.2 MB in 6s (11.3 MB/s)                                                                                                                                                              
    Preconfiguring packages ...
    (Reading database ... 498238 files and directories currently installed.)
    Removing virtualbox-qt (5.2.10-dfsg-6ubuntu18.04.1) ...
    Removing virtualbox-ext-pack (5.2.10-3ubuntu18.04.1) ...
    0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    Successfully uninstalled "Oracle VM VirtualBox Extension Pack".
    Successfully performed extension pack cleanup
    Removing virtualbox (5.2.10-dfsg-6ubuntu18.04.1) ...
    Removing virtualbox-guest-additions-iso (5.2.11-122181-1) ...
    Selecting previously unselected package virtualbox-5.2.
    (Reading database ... 497919 files and directories currently installed.)
    Preparing to unpack .../virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb ...
    dpkg: error processing archive /var/cache/apt/archives/virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb (--unpack):
     new virtualbox-5.2 package pre-installation script subprocess returned error exit status 1
    Selecting previously unselected package libsdl-ttf2.0-0:amd64.
    Preparing to unpack .../libsdl-ttf2.0-0_2.0.11-4_amd64.deb ...
    Unpacking libsdl-ttf2.0-0:amd64 (2.0.11-4) ...
    Errors were encountered while processing:
     /var/cache/apt/archives/virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)    
    #+END_EXAMPLE
- install new version =virtualbox-5.2= is now from the installed repo, while
  =virtualbox= is the older ubuntu version as before.
  #+BEGIN_SRC shell
  sudo apt update #preinstall required packages, no action if installed:
  sudo apt-get -y install gcc make linux-headers-$(uname -r) dkms
  sudo apt update #install the newest version from new repo:
  sudo apt install virtualbox-5.2
  #+END_SRC
  - JW output:
    #+BEGIN_EXAMPLE
    johannes@joe-9470m:~$ sudo apt-get install virtualbox-5.2
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libgsoap-2.8.60 libvncserver1 virtualbox-dkms
    Use 'sudo apt autoremove' to remove them.
    The following NEW packages will be installed:
      virtualbox-5.2
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 0 B/68.1 MB of archives.
    After this operation, 167 MB of additional disk space will be used.
    Preconfiguring packages ...
    (Reading database ... 497926 files and directories currently installed.)
    Preparing to unpack .../virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb ...
    Unpacking virtualbox-5.2 (5.2.22-126460~Ubuntu~bionic) ...
    Setting up virtualbox-5.2 (5.2.22-126460~Ubuntu~bionic) ...
    addgroup: The group `vboxusers' already exists as a system group. Exiting.
    Processing triggers for mime-support (3.60ubuntu1) ...
    Processing triggers for ureadahead (0.100.0-20) ...
    Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.1) ...
    Processing triggers for systemd (237-3ubuntu10.4) ...
    Processing triggers for shared-mime-info (1.9-2) ...
    Unknown media type in type 'all/all'
    Unknown media type in type 'all/allfiles'
    Processing triggers for hicolor-icon-theme (0.17-2) ...
    #+END_EXAMPLE
*** Result
- JW Sidenotes: Results:
  - the installed version is now 5.2.22.
  - new version automatically found my old VMs
    [[file:/media/sams250g/johannes/VirtualBox%20VMs/][/media/sams250g/johannes/VirtualBox 20VMs]]
    
*** Installation of Extension Pack
- from instructionA
- [[https://www.virtualbox.org/wiki/Downloads][check]] for current version:
  https://download.virtualbox.org/virtualbox/5.2.22/Oracle_VM_VirtualBox_Extension_Pack-5.2.22.vbox-extpack
- do:
  #+BEGIN_SRC shell
  wget https://download.virtualbox.org/virtualbox/5.2.22/Oracle_VM_VirtualBox_Extension_Pack-5.2.22.vbox-extpack
  #+END_SRC
- import extension pack:
  #+BEGIN_SRC shell
  sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.2.20.vbox-extpack
  # ... should end with:
  # Successfully installed "Oracle VM VirtualBox Extension Pack".
  #+END_SRC

** Import virtual machine in VB, setup shared folder
- from qm vm release notes:
  - Import virtual machine image into Virtualbox (12G): File => Import Appliance
- from instructionC:
  - Stop the VM
  - Add your folder in Machine => Settings => Shared Folders => Add Folder Icon
  - tick "Automount"
  - Start VM. The folder will appear in /media/sf_<folder_name>
** Start Quantum Mobile VM

- username: max, password: moritz

