__inp_version__ = '0.31'
schema_dict = {'attrib_paths': {'Gmax': '/fleurInput/calculationSetup/cutoffs/@Gmax',
                  'GmaxXC': '/fleurInput/calculationSetup/cutoffs/@GmaxXC',
                  'I_initial': '/fleurInput/output/coreSpectrum/@I_initial',
                  'J': ['/fleurInput/atomSpecies/species/ldaU/@J',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@J'],
                  'Kmax': '/fleurInput/calculationSetup/cutoffs/@Kmax',
                  'M': ['/fleurInput/atomSpecies/species/nocoParams/@M',
                        '/fleurInput/atomGroups/atomGroup/nocoParams/@M'],
                  'MM': '/fleurInput/calculationSetup/oneDParams/@MM',
                  'U': ['/fleurInput/atomSpecies/species/ldaU/@U',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@U'],
                  'alpha': ['/fleurInput/atomSpecies/species/nocoParams/@alpha',
                            '/fleurInput/atomGroups/atomGroup/nocoParams/@alpha',
                            '/fleurInput/calculationSetup/scfLoop/@alpha'],
                  'alpha_Ex': '/fleurInput/output/coreSpectrum/@alpha_Ex',
                  'atomList': '/fleurInput/output/wannier/@atomList',
                  'atomType': '/fleurInput/output/coreSpectrum/@atomType',
                  'atomicNumber': '/fleurInput/atomSpecies/species/@atomicNumber',
                  'autocomp': '/fleurInput/calculationSetup/fields/@autocomp',
                  'b_cons_x': ['/fleurInput/atomSpecies/species/nocoParams/@b_cons_x',
                               '/fleurInput/atomGroups/atomGroup/nocoParams/@b_cons_x'],
                  'b_cons_y': ['/fleurInput/atomSpecies/species/nocoParams/@b_cons_y',
                               '/fleurInput/atomGroups/atomGroup/nocoParams/@b_cons_y'],
                  'b_field': '/fleurInput/calculationSetup/fields/@b_field',
                  'b_field_mt': '/fleurInput/atomSpecies/species/special/@b_field_mt',
                  'band': '/fleurInput/output/@band',
                  'bands': '/fleurInput/calculationSetup/prodBasis/@bands',
                  'beta': ['/fleurInput/atomSpecies/species/nocoParams/@beta',
                           '/fleurInput/atomGroups/atomGroup/nocoParams/@beta'],
                  'beta_Ex': '/fleurInput/output/coreSpectrum/@beta_Ex',
                  'bmt': '/fleurInput/output/specialOutput/@bmt',
                  'bsComf': '/fleurInput/output/wannier/@bsComf',
                  'calculate': ['/fleurInput/atomSpecies/species/force/@calculate',
                                '/fleurInput/atomGroups/atomGroup/force/@calculate'],
                  'cdinf': '/fleurInput/output/checks/@cdinf',
                  'chi': '/fleurInput/calculationSetup/oneDParams/@chi',
                  'chng': '/fleurInput/xcFunctional/xcParams/@chng',
                  'coreSpec': '/fleurInput/output/@coreSpec',
                  'coreStates': '/fleurInput/atomSpecies/species/@coreStates',
                  'coretail_lmax': '/fleurInput/calculationSetup/coreElectrons/@coretail_lmax',
                  'correlation': ['/fleurInput/xcFunctional/LibXCID/@correlation',
                                  '/fleurInput/xcFunctional/LibXCName/@correlation'],
                  'count': ['/fleurInput/calculationSetup/bzIntegration/kPointCount/@count',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount/@count',
                            '/fleurInput/calculationSetup/bzIntegration/kPointList/@count',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/@count'],
                  'ctail': '/fleurInput/calculationSetup/coreElectrons/@ctail',
                  'd': ['/fleurInput/atomSpecies/species/energyParameters/@d',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@d'],
                  'd1': '/fleurInput/calculationSetup/oneDParams/@d1',
                  'dTilda': '/fleurInput/cell/filmLattice/@dTilda',
                  'dVac': '/fleurInput/cell/filmLattice/@dVac',
                  'denX': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity/@denX',
                           '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity/@denX'],
                  'denY': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity/@denY',
                           '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity/@denY'],
                  'denZ': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity/@denZ',
                           '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity/@denZ'],
                  'dirichlet': '/fleurInput/calculationSetup/fields/@dirichlet',
                  'disp': '/fleurInput/output/checks/@disp',
                  'dos': '/fleurInput/output/@dos',
                  'eDeriv': ['/fleurInput/atomSpecies/species/lo/@eDeriv',
                             '/fleurInput/atomGroups/atomGroup/lo/@eDeriv'],
                  'eKin': '/fleurInput/output/coreSpectrum/@eKin',
                  'eMax': '/fleurInput/output/coreSpectrum/@eMax',
                  'eMin': '/fleurInput/output/coreSpectrum/@eMin',
                  'eV': '/fleurInput/calculationSetup/fields/@eV',
                  'edgeType': '/fleurInput/output/coreSpectrum/@edgeType',
                  'eig66': '/fleurInput/calculationSetup/expertModes/@eig66',
                  'element': '/fleurInput/atomSpecies/species/@element',
                  'ellow': '/fleurInput/calculationSetup/energyParameterLimits/@ellow',
                  'elup': '/fleurInput/calculationSetup/energyParameterLimits/@elup',
                  'energy': '/fleurInput/relaxation/relaxation-history/step/@energy',
                  'energyLo': '/fleurInput/output/magneticCircularDichroism/@energyLo',
                  'energyUp': '/fleurInput/output/magneticCircularDichroism/@energyUp',
                  'eonly': '/fleurInput/output/specialOutput/@eonly',
                  'epsdisp': '/fleurInput/calculationSetup/geometryOptimization/@epsdisp',
                  'epsforce': '/fleurInput/calculationSetup/geometryOptimization/@epsforce',
                  'etot_correlation': ['/fleurInput/xcFunctional/LibXCID/@etot_correlation',
                                       '/fleurInput/xcFunctional/LibXCName/@etot_correlation'],
                  'etot_exchange': ['/fleurInput/xcFunctional/LibXCID/@etot_exchange',
                                    '/fleurInput/xcFunctional/LibXCName/@etot_exchange'],
                  'ewaldlambda': '/fleurInput/calculationSetup/prodBasis/@ewaldlambda',
                  'exchange': ['/fleurInput/xcFunctional/LibXCID/@exchange',
                               '/fleurInput/xcFunctional/LibXCName/@exchange'],
                  'f': ['/fleurInput/atomSpecies/species/energyParameters/@f',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@f'],
                  'fermiSmearingEnergy': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingEnergy',
                  'fermiSmearingTemp': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingTemp',
                  'filename': ['/fleurInput/cell/symmetryFile/@filename',
                               '/fleurInput/calculationSetup/bzIntegration/kPointListFile/@filename',
                               '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointListFile/@filename'],
                  'fixed_moment': '/fleurInput/calculationSetup/magnetism/@fixed_moment',
                  'fleurInputVersion': '/fleurInput/@fleurInputVersion',
                  'flipSpin': '/fleurInput/atomSpecies/species/@flipSpin',
                  'force_converged': '/fleurInput/calculationSetup/geometryOptimization/@force_converged',
                  'forcealpha': '/fleurInput/calculationSetup/geometryOptimization/@forcealpha',
                  'forcemix': '/fleurInput/calculationSetup/geometryOptimization/@forcemix',
                  'form66': '/fleurInput/output/specialOutput/@form66',
                  'frcor': '/fleurInput/calculationSetup/coreElectrons/@frcor',
                  'functional': '/fleurInput/calculationSetup/rdmft/@functional',
                  'gamma': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/kPointCount/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/kPointDensity/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity/@gamma'],
                  'gcutm': '/fleurInput/calculationSetup/prodBasis/@gcutm',
                  'gridPoints': ['/fleurInput/atomSpecies/species/mtSphere/@gridPoints',
                                 '/fleurInput/atomGroups/atomGroup/mtSphere/@gridPoints'],
                  'gw': '/fleurInput/calculationSetup/expertModes/@gw',
                  'idsprs': '/fleurInput/xcFunctional/xcParams/@idsprs',
                  'idsprs0': '/fleurInput/xcFunctional/ggaPrinting/@idsprs0',
                  'idsprsi': '/fleurInput/xcFunctional/ggaPrinting/@idsprsi',
                  'idsprsl': '/fleurInput/xcFunctional/ggaPrinting/@idsprsl',
                  'idsprsv': '/fleurInput/xcFunctional/ggaPrinting/@idsprsv',
                  'iggachk': '/fleurInput/xcFunctional/ggaPrinting/@iggachk',
                  'igrd': '/fleurInput/xcFunctional/xcParams/@igrd',
                  'imix': '/fleurInput/calculationSetup/scfLoop/@imix',
                  'integ': '/fleurInput/output/vacuumDOS/@integ',
                  'invs': '/fleurInput/cell/symmetry/@invs',
                  'invs1': '/fleurInput/calculationSetup/oneDParams/@invs1',
                  'iplot': '/fleurInput/output/plotting/@iplot',
                  'isec1': '/fleurInput/calculationSetup/expertModes/@isec1',
                  'itmax': '/fleurInput/calculationSetup/scfLoop/@itmax',
                  'jspins': '/fleurInput/calculationSetup/magnetism/@jspins',
                  'kcrel': '/fleurInput/calculationSetup/coreElectrons/@kcrel',
                  'l': ['/fleurInput/atomSpecies/species/ldaU/@l',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@l',
                        '/fleurInput/atomSpecies/species/lo/@l',
                        '/fleurInput/atomGroups/atomGroup/lo/@l'],
                  'l_J': '/fleurInput/calculationSetup/magnetism/@l_J',
                  'l_amf': ['/fleurInput/atomSpecies/species/ldaU/@l_amf',
                            '/fleurInput/atomGroups/atomGroup/ldaU/@l_amf'],
                  'l_constr': '/fleurInput/calculationSetup/nocoParams/@l_constr',
                  'l_disp': '/fleurInput/calculationSetup/nocoParams/@l_disp',
                  'l_f': '/fleurInput/calculationSetup/geometryOptimization/@l_f',
                  'l_linMix': '/fleurInput/calculationSetup/ldaU/@l_linMix',
                  'l_magn': ['/fleurInput/atomSpecies/species/nocoParams/@l_magn',
                             '/fleurInput/atomGroups/atomGroup/nocoParams/@l_magn'],
                  'l_mperp': '/fleurInput/calculationSetup/nocoParams/@l_mperp',
                  'l_mtNocoPot': '/fleurInput/calculationSetup/nocoParams/@l_mtNocoPot',
                  'l_noco': '/fleurInput/calculationSetup/magnetism/@l_noco',
                  'l_rdmft': '/fleurInput/calculationSetup/rdmft/@l_rdmft',
                  'l_relax': ['/fleurInput/atomSpecies/species/nocoParams/@l_relax',
                              '/fleurInput/atomGroups/atomGroup/nocoParams/@l_relax'],
                  'l_soc': '/fleurInput/calculationSetup/soc/@l_soc',
                  'l_ss': '/fleurInput/calculationSetup/nocoParams/@l_ss',
                  'label': ['/fleurInput/atomGroups/atomGroup/relPos/@label',
                            '/fleurInput/atomGroups/atomGroup/absPos/@label',
                            '/fleurInput/atomGroups/atomGroup/filmPos/@label'],
                  'latnam': ['/fleurInput/cell/bulkLattice/@latnam',
                             '/fleurInput/cell/filmLattice/@latnam'],
                  'layers': '/fleurInput/output/vacuumDOS/@layers',
                  'lcutm': '/fleurInput/atomSpecies/species/prodBasis/@lcutm',
                  'lcutwf': '/fleurInput/atomSpecies/species/prodBasis/@lcutwf',
                  'lda': '/fleurInput/atomSpecies/species/special/@lda',
                  'lexp': '/fleurInput/calculationSetup/prodBasis/@lexp',
                  'lflip': '/fleurInput/calculationSetup/magnetism/@lflip',
                  'lmax': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lmax',
                           '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lmax',
                           '/fleurInput/output/coreSpectrum/@lmax'],
                  'lmaxAPW': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lmaxAPW',
                              '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lmaxAPW'],
                  'lnonsphr': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lnonsphr',
                               '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lnonsphr'],
                  'locx1': '/fleurInput/output/vacuumDOS/@locx1',
                  'locx2': '/fleurInput/output/vacuumDOS/@locx2',
                  'locy1': '/fleurInput/output/vacuumDOS/@locy1',
                  'locy2': '/fleurInput/output/vacuumDOS/@locy2',
                  'logIncrement': ['/fleurInput/atomSpecies/species/mtSphere/@logIncrement',
                                   '/fleurInput/atomGroups/atomGroup/mtSphere/@logIncrement'],
                  'lpr': '/fleurInput/calculationSetup/expertModes/@lpr',
                  'lwb': '/fleurInput/xcFunctional/xcParams/@lwb',
                  'm_cyl': '/fleurInput/calculationSetup/oneDParams/@m_cyl',
                  'magField': ['/fleurInput/atomSpecies/species/@magField',
                               '/fleurInput/atomGroups/atomGroup/@magField'],
                  'magMom': '/fleurInput/atomSpecies/species/@magMom',
                  'maxEigenval': '/fleurInput/output/chargeDensitySlicing/@maxEigenval',
                  'maxEnergy': '/fleurInput/output/densityOfStates/@maxEnergy',
                  'maxIterBroyd': '/fleurInput/calculationSetup/scfLoop/@maxIterBroyd',
                  'maxSpinDown': '/fleurInput/output/wannier/bandSelection/@maxSpinDown',
                  'maxSpinUp': '/fleurInput/output/wannier/bandSelection/@maxSpinUp',
                  'maxTimeToStartIter': '/fleurInput/calculationSetup/scfLoop/@maxTimeToStartIter',
                  'mcd': '/fleurInput/output/@mcd',
                  'minDistance': '/fleurInput/calculationSetup/scfLoop/@minDistance',
                  'minEigenval': '/fleurInput/output/chargeDensitySlicing/@minEigenval',
                  'minEnergy': '/fleurInput/output/densityOfStates/@minEnergy',
                  'minSpinDown': '/fleurInput/output/wannier/bandSelection/@minSpinDown',
                  'minSpinUp': '/fleurInput/output/wannier/bandSelection/@minSpinUp',
                  'mixParam': '/fleurInput/calculationSetup/ldaU/@mixParam',
                  'mix_b': '/fleurInput/calculationSetup/nocoParams/@mix_b',
                  'mode': '/fleurInput/calculationSetup/bzIntegration/@mode',
                  'ms': '/fleurInput/output/wannier/@ms',
                  'n': ['/fleurInput/atomSpecies/species/lo/@n',
                        '/fleurInput/atomGroups/atomGroup/lo/@n'],
                  'name': ['/fleurInput/constants/constant/@name',
                           '/fleurInput/xcFunctional/@name',
                           '/fleurInput/atomSpecies/species/@name',
                           '/fleurInput/calculationSetup/bzIntegration/kPointCount/specialPoint/@name',
                           '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount/specialPoint/@name'],
                  'ndir': '/fleurInput/output/densityOfStates/@ndir',
                  'ndvgrd': '/fleurInput/xcFunctional/xcParams/@ndvgrd',
                  'nnne': '/fleurInput/output/chargeDensitySlicing/@nnne',
                  'nqphi': '/fleurInput/output/coreSpectrum/@nqphi',
                  'nqr': '/fleurInput/output/coreSpectrum/@nqr',
                  'nsh': '/fleurInput/calculationSetup/nocoParams/@nsh',
                  'nstars': '/fleurInput/output/vacuumDOS/@nstars',
                  'nstm': '/fleurInput/output/vacuumDOS/@nstm',
                  'numPoints': '/fleurInput/output/coreSpectrum/@numPoints',
                  'numbands': '/fleurInput/calculationSetup/cutoffs/@numbands',
                  'numkpt': '/fleurInput/output/chargeDensitySlicing/@numkpt',
                  'nx': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh/@nx',
                         '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh/@nx'],
                  'ny': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh/@ny',
                         '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh/@ny'],
                  'nz': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh/@nz',
                         '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh/@nz'],
                  'occEps': '/fleurInput/calculationSetup/rdmft/@occEps',
                  'off': '/fleurInput/calculationSetup/soc/@off',
                  'orbcomp': ['/fleurInput/atomGroups/atomGroup/relPos/@orbcomp',
                              '/fleurInput/atomGroups/atomGroup/absPos/@orbcomp',
                              '/fleurInput/atomGroups/atomGroup/filmPos/@orbcomp'],
                  'p': ['/fleurInput/atomSpecies/species/energyParameters/@p',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@p'],
                  'pallst': '/fleurInput/output/chargeDensitySlicing/@pallst',
                  'phi': ['/fleurInput/atomSpecies/species/ldaU/@phi',
                          '/fleurInput/atomGroups/atomGroup/ldaU/@phi',
                          '/fleurInput/calculationSetup/soc/@phi',
                          '/fleurInput/forceTheorem/MAE/@phi',
                          '/fleurInput/forceTheorem/DMI/@phi'],
                  'plot_charge': '/fleurInput/calculationSetup/fields/@plot_charge',
                  'plot_rho': '/fleurInput/calculationSetup/fields/@plot_rho',
                  'plplot': '/fleurInput/output/plotting/@plplot',
                  'posScale': ['/fleurInput/calculationSetup/bzIntegration/kPointList/@posScale',
                               '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/@posScale'],
                  'pot8': '/fleurInput/calculationSetup/expertModes/@pot8',
                  'precondParam': '/fleurInput/calculationSetup/scfLoop/@precondParam',
                  'purpose': '/fleurInput/calculationSetup/bzIntegration/altKPointSet/@purpose',
                  'qfix': '/fleurInput/calculationSetup/geometryOptimization/@qfix',
                  'qx': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qx',
                  'qy': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qy',
                  'qz': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qz',
                  'radius': ['/fleurInput/atomSpecies/species/mtSphere/@radius',
                             '/fleurInput/atomGroups/atomGroup/mtSphere/@radius'],
                  'relativisticCorrections': '/fleurInput/xcFunctional/@relativisticCorrections',
                  'relaxXYZ': ['/fleurInput/atomSpecies/species/force/@relaxXYZ',
                               '/fleurInput/atomGroups/atomGroup/force/@relaxXYZ'],
                  'rot': '/fleurInput/calculationSetup/oneDParams/@rot',
                  's': ['/fleurInput/atomSpecies/species/energyParameters/@s',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@s'],
                  'scale': ['/fleurInput/cell/bulkLattice/@scale',
                            '/fleurInput/cell/filmLattice/@scale',
                            '/fleurInput/cell/bulkLattice/a1/@scale',
                            '/fleurInput/cell/filmLattice/a1/@scale',
                            '/fleurInput/cell/bulkLattice/a2/@scale',
                            '/fleurInput/cell/filmLattice/a2/@scale',
                            '/fleurInput/cell/bulkLattice/c/@scale'],
                  'score': '/fleurInput/output/plotting/@score',
                  'secvar': '/fleurInput/calculationSetup/expertModes/@secvar',
                  'select': '/fleurInput/atomSpecies/species/prodBasis/@select',
                  'sgwf': '/fleurInput/output/wannier/@sgwf',
                  'sig_b_1': '/fleurInput/calculationSetup/fields/@sig_b_1',
                  'sig_b_2': '/fleurInput/calculationSetup/fields/@sig_b_2',
                  'sigma': '/fleurInput/output/densityOfStates/@sigma',
                  'slice': '/fleurInput/output/@slice',
                  'soc66': '/fleurInput/calculationSetup/soc/@soc66',
                  'socgwf': '/fleurInput/output/wannier/@socgwf',
                  'socscale': '/fleurInput/atomSpecies/species/special/@socscale',
                  'spav': '/fleurInput/calculationSetup/soc/@spav',
                  'species': '/fleurInput/atomGroups/atomGroup/@species',
                  'spgrp': '/fleurInput/cell/symmetry/@spgrp',
                  'spinDown': ['/fleurInput/cell/filmLattice/vacuumEnergyParameters/@spinDown',
                               '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@spinDown'],
                  'spinUp': ['/fleurInput/cell/filmLattice/vacuumEnergyParameters/@spinUp',
                             '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@spinUp'],
                  'spinf': ['/fleurInput/calculationSetup/scfLoop/@spinf',
                            '/fleurInput/calculationSetup/ldaU/@spinf'],
                  'sso_opt': '/fleurInput/calculationSetup/nocoParams/@sso_opt',
                  'star': '/fleurInput/output/vacuumDOS/@star',
                  'state': '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@state',
                  'statesAbove': '/fleurInput/calculationSetup/rdmft/@statesAbove',
                  'statesBelow': '/fleurInput/calculationSetup/rdmft/@statesBelow',
                  'supercellX': '/fleurInput/output/unfoldingBand/@supercellX',
                  'supercellY': '/fleurInput/output/unfoldingBand/@supercellY',
                  'supercellZ': '/fleurInput/output/unfoldingBand/@supercellZ',
                  'swsp': '/fleurInput/calculationSetup/magnetism/@swsp',
                  'theta': ['/fleurInput/atomSpecies/species/ldaU/@theta',
                            '/fleurInput/atomGroups/atomGroup/ldaU/@theta',
                            '/fleurInput/calculationSetup/soc/@theta',
                            '/fleurInput/forceTheorem/MAE/@theta',
                            '/fleurInput/forceTheorem/DMI/@theta'],
                  'thetaJ': '/fleurInput/calculationSetup/nocoParams/@thetaJ',
                  'thetaj': '/fleurInput/forceTheorem/Jij/@thetaj',
                  'tolerance': '/fleurInput/calculationSetup/prodBasis/@tolerance',
                  'tworkf': '/fleurInput/output/vacuumDOS/@tworkf',
                  'type': ['/fleurInput/atomSpecies/species/lo/@type',
                           '/fleurInput/atomGroups/atomGroup/lo/@type'],
                  'unfoldBand': '/fleurInput/output/unfoldingBand/@unfoldBand',
                  'vM': '/fleurInput/calculationSetup/oneDParams/@vM',
                  'vacdos': '/fleurInput/output/@vacdos',
                  'vacuum': '/fleurInput/cell/filmLattice/vacuumEnergyParameters/@vacuum',
                  'valenceElectrons': '/fleurInput/calculationSetup/bzIntegration/@valenceElectrons',
                  'value': '/fleurInput/constants/constant/@value',
                  'vcaAddCharge': ['/fleurInput/atomSpecies/species/@vcaAddCharge',
                                   '/fleurInput/atomGroups/atomGroup/@vcaAddCharge'],
                  'vca_charge': '/fleurInput/atomSpecies/species/special/@vca_charge',
                  'vchk': '/fleurInput/output/checks/@vchk',
                  'verbose': '/fleurInput/output/coreSpectrum/@verbose',
                  'wannier': ['/fleurInput/atomGroups/atomGroup/relPos/@wannier',
                              '/fleurInput/atomGroups/atomGroup/absPos/@wannier',
                              '/fleurInput/atomGroups/atomGroup/filmPos/@wannier',
                              '/fleurInput/output/@wannier'],
                  'weight': ['/fleurInput/calculationSetup/bzIntegration/kPointList/kPoint/@weight',
                             '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/kPoint/@weight'],
                  'weightScale': ['/fleurInput/calculationSetup/bzIntegration/kPointList/@weightScale',
                                  '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/@weightScale'],
                  'zrfs': '/fleurInput/cell/symmetry/@zrfs',
                  'zrfs1': '/fleurInput/calculationSetup/oneDParams/@zrfs1',
                  'zsigma': '/fleurInput/calculationSetup/fields/@zsigma'},
 'attrib_types': {'float': ['gcutm',
                            'tolerance',
                            'chng',
                            'idsprsv',
                            'socscale',
                            'magField',
                            'vcaAddCharge',
                            'mixParam',
                            'spinf',
                            'occEps',
                            'denX',
                            'denY',
                            'denZ',
                            'eKin',
                            'eMin',
                            'eMax',
                            'alpha_Ex',
                            'beta_Ex',
                            'I_initial',
                            'energyLo',
                            'energyUp'],
                  'int': ['nsh',
                          'MM',
                          'vM',
                          'm_cyl',
                          'chi',
                          'rot',
                          'kcrel',
                          'coretail_lmax',
                          'jspins',
                          'vacuum',
                          'bands',
                          'lexp',
                          'ewaldlambda',
                          'exchange',
                          'correlation',
                          'etot_exchange',
                          'etot_correlation',
                          'igrd',
                          'ndvgrd',
                          'idsprs',
                          'iggachk',
                          'idsprs0',
                          'idsprsl',
                          'idsprsi',
                          'lcutm',
                          'lcutwf',
                          'atomicNumber',
                          'coreStates',
                          'gridPoints',
                          'lmax',
                          'lnonsphr',
                          'lmaxAPW',
                          's',
                          'p',
                          'd',
                          'f',
                          'l',
                          'n',
                          'eDeriv',
                          'itmax',
                          'maxIterBroyd',
                          'layers',
                          'nstars',
                          'nstm',
                          'iplot',
                          'numkpt',
                          'nnne',
                          'qfix',
                          'statesBelow',
                          'statesAbove',
                          'ndir',
                          'nx',
                          'ny',
                          'nz',
                          'count',
                          'qx',
                          'qy',
                          'qz',
                          'gw',
                          'lpr',
                          'isec1',
                          'atomType',
                          'numPoints',
                          'nqphi',
                          'nqr',
                          'minSpinUp',
                          'maxSpinUp',
                          'minSpinDown',
                          'maxSpinDown',
                          'supercellX',
                          'supercellY',
                          'supercellZ'],
                  'other': ['spgrp', 'latnam', 'purpose'],
                  'string': ['fleurInputVersion',
                             'name',
                             'value',
                             'ellow',
                             'elup',
                             'b_field',
                             'zsigma',
                             'sig_b_1',
                             'sig_b_2',
                             'sso_opt',
                             'mix_b',
                             'thetaJ',
                             'filename',
                             'fixed_moment',
                             'scale',
                             'dVac',
                             'dTilda',
                             'spinUp',
                             'spinDown',
                             'exchange',
                             'correlation',
                             'etot_exchange',
                             'etot_correlation',
                             'select',
                             'b_field_mt',
                             'vca_charge',
                             'element',
                             'magMom',
                             'species',
                             'label',
                             'M',
                             'alpha',
                             'beta',
                             'b_cons_x',
                             'b_cons_y',
                             'radius',
                             'logIncrement',
                             'U',
                             'J',
                             'phi',
                             'theta',
                             'relaxXYZ',
                             'type',
                             'Kmax',
                             'Gmax',
                             'GmaxXC',
                             'numbands',
                             'valenceElectrons',
                             'mode',
                             'fermiSmearingEnergy',
                             'fermiSmearingTemp',
                             'imix',
                             'precondParam',
                             'spinf',
                             'minDistance',
                             'maxTimeToStartIter',
                             'locx1',
                             'locy1',
                             'locx2',
                             'locy2',
                             'tworkf',
                             'minEigenval',
                             'maxEigenval',
                             'forcealpha',
                             'epsdisp',
                             'epsforce',
                             'forcemix',
                             'force_converged',
                             'functional',
                             'minEnergy',
                             'maxEnergy',
                             'sigma',
                             'posScale',
                             'weightScale',
                             'weight',
                             'edgeType',
                             'energy',
                             'thetaj',
                             'state'],
                  'switch': ['plot_charge',
                             'plot_rho',
                             'autocomp',
                             'dirichlet',
                             'eV',
                             'l_ss',
                             'l_mperp',
                             'l_constr',
                             'l_disp',
                             'l_mtNocoPot',
                             'd1',
                             'invs1',
                             'zrfs1',
                             'ctail',
                             'frcor',
                             'invs',
                             'zrfs',
                             'l_noco',
                             'l_J',
                             'swsp',
                             'lflip',
                             'relativisticCorrections',
                             'lwb',
                             'lda',
                             'flipSpin',
                             'wannier',
                             'orbcomp',
                             'l_relax',
                             'l_magn',
                             'l_amf',
                             'calculate',
                             'l_soc',
                             'spav',
                             'off',
                             'soc66',
                             'integ',
                             'star',
                             'score',
                             'plplot',
                             'pallst',
                             'l_f',
                             'l_linMix',
                             'l_rdmft',
                             'gamma',
                             'pot8',
                             'eig66',
                             'secvar',
                             'vchk',
                             'cdinf',
                             'disp',
                             'form66',
                             'eonly',
                             'bmt',
                             'verbose',
                             'ms',
                             'sgwf',
                             'socgwf',
                             'bsComf',
                             'atomList',
                             'unfoldBand',
                             'dos',
                             'band',
                             'vacdos',
                             'slice',
                             'coreSpec',
                             'mcd']},
 'settable_attribs': {'Gmax': '/fleurInput/calculationSetup/cutoffs/@Gmax',
                      'GmaxXC': '/fleurInput/calculationSetup/cutoffs/@GmaxXC',
                      'I_initial': '/fleurInput/output/coreSpectrum/@I_initial',
                      'Kmax': '/fleurInput/calculationSetup/cutoffs/@Kmax',
                      'MM': '/fleurInput/calculationSetup/oneDParams/@MM',
                      'alpha_Ex': '/fleurInput/output/coreSpectrum/@alpha_Ex',
                      'atomList': '/fleurInput/output/wannier/@atomList',
                      'atomType': '/fleurInput/output/coreSpectrum/@atomType',
                      'autocomp': '/fleurInput/calculationSetup/fields/@autocomp',
                      'b_field': '/fleurInput/calculationSetup/fields/@b_field',
                      'band': '/fleurInput/output/@band',
                      'bands': '/fleurInput/calculationSetup/prodBasis/@bands',
                      'beta_Ex': '/fleurInput/output/coreSpectrum/@beta_Ex',
                      'bmt': '/fleurInput/output/specialOutput/@bmt',
                      'bsComf': '/fleurInput/output/wannier/@bsComf',
                      'cdinf': '/fleurInput/output/checks/@cdinf',
                      'chi': '/fleurInput/calculationSetup/oneDParams/@chi',
                      'chng': '/fleurInput/xcFunctional/xcParams/@chng',
                      'coreSpec': '/fleurInput/output/@coreSpec',
                      'coretail_lmax': '/fleurInput/calculationSetup/coreElectrons/@coretail_lmax',
                      'ctail': '/fleurInput/calculationSetup/coreElectrons/@ctail',
                      'd1': '/fleurInput/calculationSetup/oneDParams/@d1',
                      'dTilda': '/fleurInput/cell/filmLattice/@dTilda',
                      'dVac': '/fleurInput/cell/filmLattice/@dVac',
                      'dirichlet': '/fleurInput/calculationSetup/fields/@dirichlet',
                      'disp': '/fleurInput/output/checks/@disp',
                      'dos': '/fleurInput/output/@dos',
                      'eKin': '/fleurInput/output/coreSpectrum/@eKin',
                      'eMax': '/fleurInput/output/coreSpectrum/@eMax',
                      'eMin': '/fleurInput/output/coreSpectrum/@eMin',
                      'eV': '/fleurInput/calculationSetup/fields/@eV',
                      'edgeType': '/fleurInput/output/coreSpectrum/@edgeType',
                      'eig66': '/fleurInput/calculationSetup/expertModes/@eig66',
                      'ellow': '/fleurInput/calculationSetup/energyParameterLimits/@ellow',
                      'elup': '/fleurInput/calculationSetup/energyParameterLimits/@elup',
                      'energyLo': '/fleurInput/output/magneticCircularDichroism/@energyLo',
                      'energyUp': '/fleurInput/output/magneticCircularDichroism/@energyUp',
                      'eonly': '/fleurInput/output/specialOutput/@eonly',
                      'epsdisp': '/fleurInput/calculationSetup/geometryOptimization/@epsdisp',
                      'epsforce': '/fleurInput/calculationSetup/geometryOptimization/@epsforce',
                      'ewaldlambda': '/fleurInput/calculationSetup/prodBasis/@ewaldlambda',
                      'fermiSmearingEnergy': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingEnergy',
                      'fermiSmearingTemp': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingTemp',
                      'fixed_moment': '/fleurInput/calculationSetup/magnetism/@fixed_moment',
                      'fleurInputVersion': '/fleurInput/@fleurInputVersion',
                      'force_converged': '/fleurInput/calculationSetup/geometryOptimization/@force_converged',
                      'forcealpha': '/fleurInput/calculationSetup/geometryOptimization/@forcealpha',
                      'forcemix': '/fleurInput/calculationSetup/geometryOptimization/@forcemix',
                      'form66': '/fleurInput/output/specialOutput/@form66',
                      'frcor': '/fleurInput/calculationSetup/coreElectrons/@frcor',
                      'functional': '/fleurInput/calculationSetup/rdmft/@functional',
                      'gcutm': '/fleurInput/calculationSetup/prodBasis/@gcutm',
                      'gw': '/fleurInput/calculationSetup/expertModes/@gw',
                      'idsprs': '/fleurInput/xcFunctional/xcParams/@idsprs',
                      'idsprs0': '/fleurInput/xcFunctional/ggaPrinting/@idsprs0',
                      'idsprsi': '/fleurInput/xcFunctional/ggaPrinting/@idsprsi',
                      'idsprsl': '/fleurInput/xcFunctional/ggaPrinting/@idsprsl',
                      'idsprsv': '/fleurInput/xcFunctional/ggaPrinting/@idsprsv',
                      'iggachk': '/fleurInput/xcFunctional/ggaPrinting/@iggachk',
                      'igrd': '/fleurInput/xcFunctional/xcParams/@igrd',
                      'imix': '/fleurInput/calculationSetup/scfLoop/@imix',
                      'integ': '/fleurInput/output/vacuumDOS/@integ',
                      'invs': '/fleurInput/cell/symmetry/@invs',
                      'invs1': '/fleurInput/calculationSetup/oneDParams/@invs1',
                      'iplot': '/fleurInput/output/plotting/@iplot',
                      'isec1': '/fleurInput/calculationSetup/expertModes/@isec1',
                      'itmax': '/fleurInput/calculationSetup/scfLoop/@itmax',
                      'jspins': '/fleurInput/calculationSetup/magnetism/@jspins',
                      'kcrel': '/fleurInput/calculationSetup/coreElectrons/@kcrel',
                      'l_J': '/fleurInput/calculationSetup/magnetism/@l_J',
                      'l_constr': '/fleurInput/calculationSetup/nocoParams/@l_constr',
                      'l_disp': '/fleurInput/calculationSetup/nocoParams/@l_disp',
                      'l_f': '/fleurInput/calculationSetup/geometryOptimization/@l_f',
                      'l_linMix': '/fleurInput/calculationSetup/ldaU/@l_linMix',
                      'l_mperp': '/fleurInput/calculationSetup/nocoParams/@l_mperp',
                      'l_mtNocoPot': '/fleurInput/calculationSetup/nocoParams/@l_mtNocoPot',
                      'l_noco': '/fleurInput/calculationSetup/magnetism/@l_noco',
                      'l_rdmft': '/fleurInput/calculationSetup/rdmft/@l_rdmft',
                      'l_soc': '/fleurInput/calculationSetup/soc/@l_soc',
                      'l_ss': '/fleurInput/calculationSetup/nocoParams/@l_ss',
                      'layers': '/fleurInput/output/vacuumDOS/@layers',
                      'lexp': '/fleurInput/calculationSetup/prodBasis/@lexp',
                      'lflip': '/fleurInput/calculationSetup/magnetism/@lflip',
                      'locx1': '/fleurInput/output/vacuumDOS/@locx1',
                      'locx2': '/fleurInput/output/vacuumDOS/@locx2',
                      'locy1': '/fleurInput/output/vacuumDOS/@locy1',
                      'locy2': '/fleurInput/output/vacuumDOS/@locy2',
                      'lpr': '/fleurInput/calculationSetup/expertModes/@lpr',
                      'lwb': '/fleurInput/xcFunctional/xcParams/@lwb',
                      'm_cyl': '/fleurInput/calculationSetup/oneDParams/@m_cyl',
                      'maxEigenval': '/fleurInput/output/chargeDensitySlicing/@maxEigenval',
                      'maxEnergy': '/fleurInput/output/densityOfStates/@maxEnergy',
                      'maxIterBroyd': '/fleurInput/calculationSetup/scfLoop/@maxIterBroyd',
                      'maxSpinDown': '/fleurInput/output/wannier/bandSelection/@maxSpinDown',
                      'maxSpinUp': '/fleurInput/output/wannier/bandSelection/@maxSpinUp',
                      'maxTimeToStartIter': '/fleurInput/calculationSetup/scfLoop/@maxTimeToStartIter',
                      'mcd': '/fleurInput/output/@mcd',
                      'minDistance': '/fleurInput/calculationSetup/scfLoop/@minDistance',
                      'minEigenval': '/fleurInput/output/chargeDensitySlicing/@minEigenval',
                      'minEnergy': '/fleurInput/output/densityOfStates/@minEnergy',
                      'minSpinDown': '/fleurInput/output/wannier/bandSelection/@minSpinDown',
                      'minSpinUp': '/fleurInput/output/wannier/bandSelection/@minSpinUp',
                      'mixParam': '/fleurInput/calculationSetup/ldaU/@mixParam',
                      'mix_b': '/fleurInput/calculationSetup/nocoParams/@mix_b',
                      'mode': '/fleurInput/calculationSetup/bzIntegration/@mode',
                      'ms': '/fleurInput/output/wannier/@ms',
                      'ndir': '/fleurInput/output/densityOfStates/@ndir',
                      'ndvgrd': '/fleurInput/xcFunctional/xcParams/@ndvgrd',
                      'nnne': '/fleurInput/output/chargeDensitySlicing/@nnne',
                      'nqphi': '/fleurInput/output/coreSpectrum/@nqphi',
                      'nqr': '/fleurInput/output/coreSpectrum/@nqr',
                      'nsh': '/fleurInput/calculationSetup/nocoParams/@nsh',
                      'nstars': '/fleurInput/output/vacuumDOS/@nstars',
                      'nstm': '/fleurInput/output/vacuumDOS/@nstm',
                      'numPoints': '/fleurInput/output/coreSpectrum/@numPoints',
                      'numbands': '/fleurInput/calculationSetup/cutoffs/@numbands',
                      'numkpt': '/fleurInput/output/chargeDensitySlicing/@numkpt',
                      'occEps': '/fleurInput/calculationSetup/rdmft/@occEps',
                      'off': '/fleurInput/calculationSetup/soc/@off',
                      'pallst': '/fleurInput/output/chargeDensitySlicing/@pallst',
                      'plot_charge': '/fleurInput/calculationSetup/fields/@plot_charge',
                      'plot_rho': '/fleurInput/calculationSetup/fields/@plot_rho',
                      'plplot': '/fleurInput/output/plotting/@plplot',
                      'pot8': '/fleurInput/calculationSetup/expertModes/@pot8',
                      'precondParam': '/fleurInput/calculationSetup/scfLoop/@precondParam',
                      'qfix': '/fleurInput/calculationSetup/geometryOptimization/@qfix',
                      'qx': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qx',
                      'qy': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qy',
                      'qz': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qz',
                      'relativisticCorrections': '/fleurInput/xcFunctional/@relativisticCorrections',
                      'rot': '/fleurInput/calculationSetup/oneDParams/@rot',
                      'score': '/fleurInput/output/plotting/@score',
                      'secvar': '/fleurInput/calculationSetup/expertModes/@secvar',
                      'sgwf': '/fleurInput/output/wannier/@sgwf',
                      'sig_b_1': '/fleurInput/calculationSetup/fields/@sig_b_1',
                      'sig_b_2': '/fleurInput/calculationSetup/fields/@sig_b_2',
                      'sigma': '/fleurInput/output/densityOfStates/@sigma',
                      'slice': '/fleurInput/output/@slice',
                      'soc66': '/fleurInput/calculationSetup/soc/@soc66',
                      'socgwf': '/fleurInput/output/wannier/@socgwf',
                      'spav': '/fleurInput/calculationSetup/soc/@spav',
                      'spgrp': '/fleurInput/cell/symmetry/@spgrp',
                      'sso_opt': '/fleurInput/calculationSetup/nocoParams/@sso_opt',
                      'star': '/fleurInput/output/vacuumDOS/@star',
                      'statesAbove': '/fleurInput/calculationSetup/rdmft/@statesAbove',
                      'statesBelow': '/fleurInput/calculationSetup/rdmft/@statesBelow',
                      'supercellX': '/fleurInput/output/unfoldingBand/@supercellX',
                      'supercellY': '/fleurInput/output/unfoldingBand/@supercellY',
                      'supercellZ': '/fleurInput/output/unfoldingBand/@supercellZ',
                      'swsp': '/fleurInput/calculationSetup/magnetism/@swsp',
                      'thetaJ': '/fleurInput/calculationSetup/nocoParams/@thetaJ',
                      'thetaj': '/fleurInput/forceTheorem/Jij/@thetaj',
                      'tolerance': '/fleurInput/calculationSetup/prodBasis/@tolerance',
                      'tworkf': '/fleurInput/output/vacuumDOS/@tworkf',
                      'unfoldBand': '/fleurInput/output/unfoldingBand/@unfoldBand',
                      'vM': '/fleurInput/calculationSetup/oneDParams/@vM',
                      'vacdos': '/fleurInput/output/@vacdos',
                      'valenceElectrons': '/fleurInput/calculationSetup/bzIntegration/@valenceElectrons',
                      'vchk': '/fleurInput/output/checks/@vchk',
                      'verbose': '/fleurInput/output/coreSpectrum/@verbose',
                      'zrfs': '/fleurInput/cell/symmetry/@zrfs',
                      'zrfs1': '/fleurInput/calculationSetup/oneDParams/@zrfs1',
                      'zsigma': '/fleurInput/calculationSetup/fields/@zsigma'},
 'tag_order': {'altKPointSet': ['kPointMesh',
                                'kPointCount',
                                'kPointList',
                                'kPointDensity',
                                'kPointListFile'],
               'atomGroup': [['relPos', 'absPos', 'filmPos'],
                             'mtSphere',
                             'atomicCutoffs',
                             'energyParameters',
                             'force',
                             'nocoParams',
                             'ldaU',
                             'lo',
                             'orbcomprot'],
               'atomGroups': 'atomGroup',
               'atomSpecies': 'species',
               'bravaisMatrix': ['row-1', 'row-2', 'row-3'],
               'bulkLattice': [['a1', 'a2', 'c'],
                               ['row-1', 'row-2', 'c'],
                               'bravaisMatrix'],
               'bzIntegration': [['kPointMesh',
                                  'kPointCount',
                                  'kPointList',
                                  'kPointDensity',
                                  'kPointListFile'],
                                 'altKPointSet'],
               'cell': [['symmetry', 'symmetryFile', 'symmetryOperations'],
                        ['bulkLattice', 'filmLattice']],
               'constants': 'constant',
               'coreSpectrum': 'edgeIndices',
               'displacements': 'displace',
               'electronConfig': ['coreConfig',
                                  'valenceConfig',
                                  'stateOccupation'],
               'fields': 'shape',
               'filmLattice': [[['a1', 'a2'],
                                ['row-1', 'row-2'],
                                'bravaisMatrix'],
                               'vacuumEnergyParameters'],
               'kPointCount': 'specialPoint',
               'kPointList': 'kPoint',
               'nocoParams': ['qss', 'qsc'],
               'relaxation-history': 'step',
               'species': ['mtSphere',
                           'atomicCutoffs',
                           'energyParameters',
                           'prodBasis',
                           'special',
                           'force',
                           'electronConfig',
                           'nocoParams',
                           'ldaU',
                           'lo'],
               'spinSpiralDispersion': 'q',
               'step': 'posforce',
               'symOp': ['row-1', 'row-2', 'row-3'],
               'symmetryOperations': 'symOp',
               'xcFunctional': ['LibXCID',
                                'LibXCName',
                                'xcParams',
                                'ggaPrinting']},
 'tag_paths': {'DMI': '/fleurInput/forceTheorem/DMI',
               'Jij': '/fleurInput/forceTheorem/Jij',
               'LibXCID': '/fleurInput/xcFunctional/LibXCID',
               'LibXCName': '/fleurInput/xcFunctional/LibXCName',
               'MAE': '/fleurInput/forceTheorem/MAE',
               'a1': ['/fleurInput/cell/bulkLattice/a1',
                      '/fleurInput/cell/filmLattice/a1'],
               'a2': ['/fleurInput/cell/bulkLattice/a2',
                      '/fleurInput/cell/filmLattice/a2'],
               'absPos': '/fleurInput/atomGroups/atomGroup/absPos',
               'altKPointSet': '/fleurInput/calculationSetup/bzIntegration/altKPointSet',
               'atomGroup': '/fleurInput/atomGroups/atomGroup',
               'atomGroups': '/fleurInput/atomGroups',
               'atomSpecies': '/fleurInput/atomSpecies',
               'atomicCutoffs': ['/fleurInput/atomSpecies/species/atomicCutoffs',
                                 '/fleurInput/atomGroups/atomGroup/atomicCutoffs'],
               'bandSelection': '/fleurInput/output/wannier/bandSelection',
               'bravaisMatrix': ['/fleurInput/cell/bulkLattice/bravaisMatrix',
                                 '/fleurInput/cell/filmLattice/bravaisMatrix'],
               'bulkLattice': '/fleurInput/cell/bulkLattice',
               'bzIntegration': '/fleurInput/calculationSetup/bzIntegration',
               'c': ['/fleurInput/cell/bulkLattice/c',
                     '/fleurInput/cell/bulkLattice/c'],
               'calculationSetup': '/fleurInput/calculationSetup',
               'cell': '/fleurInput/cell',
               'chargeDensitySlicing': '/fleurInput/output/chargeDensitySlicing',
               'checks': '/fleurInput/output/checks',
               'comment': '/fleurInput/comment',
               'constant': '/fleurInput/constants/constant',
               'constants': '/fleurInput/constants',
               'coreConfig': '/fleurInput/atomSpecies/species/electronConfig/coreConfig',
               'coreElectrons': '/fleurInput/calculationSetup/coreElectrons',
               'coreSpectrum': '/fleurInput/output/coreSpectrum',
               'cutoffs': '/fleurInput/calculationSetup/cutoffs',
               'densityOfStates': '/fleurInput/output/densityOfStates',
               'displace': '/fleurInput/relaxation/displacements/displace',
               'displacements': '/fleurInput/relaxation/displacements',
               'edgeIndices': '/fleurInput/output/coreSpectrum/edgeIndices',
               'electronConfig': '/fleurInput/atomSpecies/species/electronConfig',
               'energyParameterLimits': '/fleurInput/calculationSetup/energyParameterLimits',
               'energyParameters': ['/fleurInput/atomSpecies/species/energyParameters',
                                    '/fleurInput/atomGroups/atomGroup/energyParameters'],
               'expertModes': '/fleurInput/calculationSetup/expertModes',
               'fields': '/fleurInput/calculationSetup/fields',
               'filmLattice': '/fleurInput/cell/filmLattice',
               'filmPos': '/fleurInput/atomGroups/atomGroup/filmPos',
               'fleurInput': '/fleurInput',
               'force': ['/fleurInput/atomSpecies/species/force',
                         '/fleurInput/atomGroups/atomGroup/force'],
               'forceTheorem': '/fleurInput/forceTheorem',
               'geometryOptimization': '/fleurInput/calculationSetup/geometryOptimization',
               'ggaPrinting': '/fleurInput/xcFunctional/ggaPrinting',
               'jobList': '/fleurInput/output/wannier/jobList',
               'kPoint': ['/fleurInput/calculationSetup/bzIntegration/kPointList/kPoint',
                          '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/kPoint'],
               'kPointCount': ['/fleurInput/calculationSetup/bzIntegration/kPointCount',
                               '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount'],
               'kPointDensity': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity',
                                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity'],
               'kPointList': ['/fleurInput/calculationSetup/bzIntegration/kPointList',
                              '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList'],
               'kPointListFile': ['/fleurInput/calculationSetup/bzIntegration/kPointListFile',
                                  '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointListFile'],
               'kPointMesh': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh',
                              '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh'],
               'ldaU': ['/fleurInput/calculationSetup/ldaU',
                        '/fleurInput/atomSpecies/species/ldaU',
                        '/fleurInput/atomGroups/atomGroup/ldaU'],
               'lo': ['/fleurInput/atomSpecies/species/lo',
                      '/fleurInput/atomGroups/atomGroup/lo'],
               'magneticCircularDichroism': '/fleurInput/output/magneticCircularDichroism',
               'magnetism': '/fleurInput/calculationSetup/magnetism',
               'mtSphere': ['/fleurInput/atomSpecies/species/mtSphere',
                            '/fleurInput/atomGroups/atomGroup/mtSphere'],
               'nocoParams': ['/fleurInput/calculationSetup/nocoParams',
                              '/fleurInput/atomSpecies/species/nocoParams',
                              '/fleurInput/atomGroups/atomGroup/nocoParams'],
               'oneDParams': '/fleurInput/calculationSetup/oneDParams',
               'orbcomprot': '/fleurInput/atomGroups/atomGroup/orbcomprot',
               'output': '/fleurInput/output',
               'plotting': '/fleurInput/output/plotting',
               'posforce': '/fleurInput/relaxation/relaxation-history/step/posforce',
               'prodBasis': ['/fleurInput/calculationSetup/prodBasis',
                             '/fleurInput/atomSpecies/species/prodBasis'],
               'q': ['/fleurInput/forceTheorem/DMI/qVectors/q',
                     '/fleurInput/forceTheorem/Jij/qVectors/q'],
               'qVectors': ['/fleurInput/forceTheorem/DMI/qVectors',
                            '/fleurInput/forceTheorem/Jij/qVectors'],
               'qsc': '/fleurInput/calculationSetup/nocoParams/qsc',
               'qss': '/fleurInput/calculationSetup/nocoParams/qss',
               'rdmft': '/fleurInput/calculationSetup/rdmft',
               'relPos': '/fleurInput/atomGroups/atomGroup/relPos',
               'relaxation': '/fleurInput/relaxation',
               'relaxation-history': '/fleurInput/relaxation/relaxation-history',
               'row-1': ['/fleurInput/cell/bulkLattice/row-1',
                         '/fleurInput/cell/filmLattice/row-1',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-1',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-1',
                         '/fleurInput/cell/symmetryOperations/symOp/row-1'],
               'row-2': ['/fleurInput/cell/bulkLattice/row-2',
                         '/fleurInput/cell/filmLattice/row-2',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-2',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-2',
                         '/fleurInput/cell/symmetryOperations/symOp/row-2'],
               'row-3': ['/fleurInput/cell/bulkLattice/bravaisMatrix/row-3',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-3',
                         '/fleurInput/cell/symmetryOperations/symOp/row-3'],
               'scfLoop': '/fleurInput/calculationSetup/scfLoop',
               'shape': '/fleurInput/calculationSetup/fields/shape',
               'soc': '/fleurInput/calculationSetup/soc',
               'special': '/fleurInput/atomSpecies/species/special',
               'specialOutput': '/fleurInput/output/specialOutput',
               'specialPoint': ['/fleurInput/calculationSetup/bzIntegration/kPointCount/specialPoint',
                                '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount/specialPoint'],
               'species': '/fleurInput/atomSpecies/species',
               'spinSpiralDispersion': '/fleurInput/forceTheorem/spinSpiralDispersion',
               'spinSpiralQPointMesh': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
               'stateOccupation': '/fleurInput/atomSpecies/species/electronConfig/stateOccupation',
               'step': '/fleurInput/relaxation/relaxation-history/step',
               'symOp': '/fleurInput/cell/symmetryOperations/symOp',
               'symmetry': '/fleurInput/cell/symmetry',
               'symmetryFile': '/fleurInput/cell/symmetryFile',
               'symmetryOperations': '/fleurInput/cell/symmetryOperations',
               'unfoldingBand': '/fleurInput/output/unfoldingBand',
               'vacuumDOS': '/fleurInput/output/vacuumDOS',
               'vacuumEnergyParameters': '/fleurInput/cell/filmLattice/vacuumEnergyParameters',
               'valenceConfig': '/fleurInput/atomSpecies/species/electronConfig/valenceConfig',
               'wannier': '/fleurInput/output/wannier',
               'xcFunctional': '/fleurInput/xcFunctional',
               'xcParams': '/fleurInput/xcFunctional/xcParams'},
 'tags_several': ['constant',
                  'shape',
                  'symOp',
                  'vacuumEnergyParameters',
                  'species',
                  'ldaU',
                  'lo',
                  'atomGroup',
                  'altKPointSet',
                  'specialPoint',
                  'kPoint',
                  'displace',
                  'step',
                  'posforce',
                  'q',
                  'stateOccupation']}
