# -*- coding: utf-8 -*-
__inp_version__ = '0.29'
schema_dict = {'attrib_paths': {'Gmax': '/fleurInput/calculationSetup/cutoffs/@Gmax',
                  'GmaxXC': '/fleurInput/calculationSetup/cutoffs/@GmaxXC',
                  'I_initial': '/fleurInput/output/coreSpectrum/@I_initial',
                  'J': ['/fleurInput/atomSpecies/species/ldaU/@J',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@J'],
                  'Kmax': '/fleurInput/calculationSetup/cutoffs/@Kmax',
                  'M': ['/fleurInput/atomSpecies/species/nocoParams/@M',
                        '/fleurInput/atomGroups/atomGroup/nocoParams/@M'],
                  'MM': '/fleurInput/calculationSetup/oneDParams/@MM',
                  'U': ['/fleurInput/atomSpecies/species/ldaU/@U',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@U'],
                  'alpha': ['/fleurInput/atomSpecies/species/nocoParams/@alpha',
                            '/fleurInput/atomGroups/atomGroup/nocoParams/@alpha',
                            '/fleurInput/calculationSetup/scfLoop/@alpha'],
                  'alpha_Ex': '/fleurInput/output/coreSpectrum/@alpha_Ex',
                  'atomList': '/fleurInput/output/wannier/@atomList',
                  'atomType': '/fleurInput/output/coreSpectrum/@atomType',
                  'atomicNumber': '/fleurInput/atomSpecies/species/@atomicNumber',
                  'autocomp': '/fleurInput/calculationSetup/fields/@autocomp',
                  'b_cons_x': ['/fleurInput/atomSpecies/species/nocoParams/@b_cons_x',
                               '/fleurInput/atomGroups/atomGroup/nocoParams/@b_cons_x'],
                  'b_cons_y': ['/fleurInput/atomSpecies/species/nocoParams/@b_cons_y',
                               '/fleurInput/atomGroups/atomGroup/nocoParams/@b_cons_y'],
                  'b_field': '/fleurInput/calculationSetup/fields/@b_field',
                  'b_field_mt': '/fleurInput/atomSpecies/species/special/@b_field_mt',
                  'band': '/fleurInput/output/@band',
                  'bands': '/fleurInput/calculationSetup/prodBasis/@bands',
                  'beta': ['/fleurInput/atomSpecies/species/nocoParams/@beta',
                           '/fleurInput/atomGroups/atomGroup/nocoParams/@beta'],
                  'beta_Ex': '/fleurInput/output/coreSpectrum/@beta_Ex',
                  'bmt': '/fleurInput/output/specialOutput/@bmt',
                  'bsComf': '/fleurInput/output/wannier/@bsComf',
                  'calculate': ['/fleurInput/atomSpecies/species/force/@calculate',
                                '/fleurInput/atomGroups/atomGroup/force/@calculate'],
                  'cdinf': '/fleurInput/output/checks/@cdinf',
                  'chi': '/fleurInput/calculationSetup/oneDParams/@chi',
                  'chng': '/fleurInput/xcFunctional/xcParams/@chng',
                  'coreSpec': '/fleurInput/output/@coreSpec',
                  'coreStates': '/fleurInput/atomSpecies/species/@coreStates',
                  'coretail_lmax': '/fleurInput/calculationSetup/coreElectrons/@coretail_lmax',
                  'correlation': ['/fleurInput/xcFunctional/LibXCID/@correlation',
                                  '/fleurInput/xcFunctional/LibXCName/@correlation'],
                  'count': ['/fleurInput/calculationSetup/bzIntegration/kPointCount/@count',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount/@count',
                            '/fleurInput/calculationSetup/bzIntegration/kPointList/@count',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/@count'],
                  'ctail': '/fleurInput/calculationSetup/coreElectrons/@ctail',
                  'd': ['/fleurInput/atomSpecies/species/energyParameters/@d',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@d'],
                  'd1': '/fleurInput/calculationSetup/oneDParams/@d1',
                  'dTilda': '/fleurInput/cell/filmLattice/@dTilda',
                  'dVac': '/fleurInput/cell/filmLattice/@dVac',
                  'denX': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity/@denX',
                           '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity/@denX'],
                  'denY': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity/@denY',
                           '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity/@denY'],
                  'denZ': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity/@denZ',
                           '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity/@denZ'],
                  'dirichlet': '/fleurInput/calculationSetup/fields/@dirichlet',
                  'disp': '/fleurInput/output/checks/@disp',
                  'dos': '/fleurInput/output/@dos',
                  'eDeriv': ['/fleurInput/atomSpecies/species/lo/@eDeriv',
                             '/fleurInput/atomGroups/atomGroup/lo/@eDeriv'],
                  'eKin': '/fleurInput/output/coreSpectrum/@eKin',
                  'eMax': '/fleurInput/output/coreSpectrum/@eMax',
                  'eMin': '/fleurInput/output/coreSpectrum/@eMin',
                  'eV': '/fleurInput/calculationSetup/fields/@eV',
                  'edgeType': '/fleurInput/output/coreSpectrum/@edgeType',
                  'eig66': '/fleurInput/calculationSetup/expertModes/@eig66',
                  'element': '/fleurInput/atomSpecies/species/@element',
                  'ellow': '/fleurInput/calculationSetup/energyParameterLimits/@ellow',
                  'elup': '/fleurInput/calculationSetup/energyParameterLimits/@elup',
                  'energy': '/fleurInput/relaxation/relaxation-history/step/@energy',
                  'energyLo': '/fleurInput/output/magneticCircularDichroism/@energyLo',
                  'energyUp': '/fleurInput/output/magneticCircularDichroism/@energyUp',
                  'eonly': '/fleurInput/output/specialOutput/@eonly',
                  'epsdisp': '/fleurInput/calculationSetup/geometryOptimization/@epsdisp',
                  'epsforce': '/fleurInput/calculationSetup/geometryOptimization/@epsforce',
                  'ewaldlambda': '/fleurInput/calculationSetup/prodBasis/@ewaldlambda',
                  'exchange': ['/fleurInput/xcFunctional/LibXCID/@exchange',
                               '/fleurInput/xcFunctional/LibXCName/@exchange'],
                  'f': ['/fleurInput/atomSpecies/species/energyParameters/@f',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@f'],
                  'fermiSmearingEnergy': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingEnergy',
                  'fermiSmearingTemp': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingTemp',
                  'filename': ['/fleurInput/cell/symmetryFile/@filename',
                               '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointListFile/@filename'],
                  'fixed_moment': '/fleurInput/calculationSetup/magnetism/@fixed_moment',
                  'fleurInputVersion': '/fleurInput/@fleurInputVersion',
                  'flipSpin': '/fleurInput/atomSpecies/species/@flipSpin',
                  'force_converged': '/fleurInput/calculationSetup/geometryOptimization/@force_converged',
                  'forcealpha': '/fleurInput/calculationSetup/geometryOptimization/@forcealpha',
                  'forcemix': '/fleurInput/calculationSetup/geometryOptimization/@forcemix',
                  'form66': '/fleurInput/output/specialOutput/@form66',
                  'frcor': '/fleurInput/calculationSetup/coreElectrons/@frcor',
                  'functional': '/fleurInput/calculationSetup/rdmft/@functional',
                  'gamma': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/kPointCount/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/kPointDensity/@gamma',
                            '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity/@gamma'],
                  'gcutm': '/fleurInput/calculationSetup/prodBasis/@gcutm',
                  'gridPoints': ['/fleurInput/atomSpecies/species/mtSphere/@gridPoints',
                                 '/fleurInput/atomGroups/atomGroup/mtSphere/@gridPoints'],
                  'gw': '/fleurInput/calculationSetup/expertModes/@gw',
                  'idsprs': '/fleurInput/xcFunctional/xcParams/@idsprs',
                  'idsprs0': '/fleurInput/xcFunctional/ggaPrinting/@idsprs0',
                  'idsprsi': '/fleurInput/xcFunctional/ggaPrinting/@idsprsi',
                  'idsprsl': '/fleurInput/xcFunctional/ggaPrinting/@idsprsl',
                  'idsprsv': '/fleurInput/xcFunctional/ggaPrinting/@idsprsv',
                  'iggachk': '/fleurInput/xcFunctional/ggaPrinting/@iggachk',
                  'igrd': '/fleurInput/xcFunctional/xcParams/@igrd',
                  'imix': '/fleurInput/calculationSetup/scfLoop/@imix',
                  'integ': '/fleurInput/output/vacuumDOS/@integ',
                  'invs': '/fleurInput/cell/symmetry/@invs',
                  'invs1': '/fleurInput/calculationSetup/oneDParams/@invs1',
                  'iplot': '/fleurInput/output/plotting/@iplot',
                  'isec1': '/fleurInput/calculationSetup/expertModes/@isec1',
                  'itmax': '/fleurInput/calculationSetup/scfLoop/@itmax',
                  'jspins': '/fleurInput/calculationSetup/magnetism/@jspins',
                  'kcrel': '/fleurInput/calculationSetup/coreElectrons/@kcrel',
                  'l': ['/fleurInput/atomSpecies/species/ldaU/@l',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@l',
                        '/fleurInput/atomSpecies/species/lo/@l',
                        '/fleurInput/atomGroups/atomGroup/lo/@l'],
                  'l_J': '/fleurInput/calculationSetup/magnetism/@l_J',
                  'l_amf': ['/fleurInput/atomSpecies/species/ldaU/@l_amf',
                            '/fleurInput/atomGroups/atomGroup/ldaU/@l_amf'],
                  'l_constr': '/fleurInput/calculationSetup/nocoParams/@l_constr',
                  'l_disp': '/fleurInput/calculationSetup/nocoParams/@l_disp',
                  'l_f': '/fleurInput/calculationSetup/geometryOptimization/@l_f',
                  'l_linMix': '/fleurInput/calculationSetup/ldaU/@l_linMix',
                  'l_magn': ['/fleurInput/atomSpecies/species/nocoParams/@l_magn',
                             '/fleurInput/atomGroups/atomGroup/nocoParams/@l_magn'],
                  'l_mperp': '/fleurInput/calculationSetup/nocoParams/@l_mperp',
                  'l_mtNocoPot': '/fleurInput/calculationSetup/nocoParams/@l_mtNocoPot',
                  'l_noco': '/fleurInput/calculationSetup/magnetism/@l_noco',
                  'l_rdmft': '/fleurInput/calculationSetup/rdmft/@l_rdmft',
                  'l_relax': ['/fleurInput/atomSpecies/species/nocoParams/@l_relax',
                              '/fleurInput/atomGroups/atomGroup/nocoParams/@l_relax'],
                  'l_soc': '/fleurInput/calculationSetup/soc/@l_soc',
                  'l_ss': '/fleurInput/calculationSetup/nocoParams/@l_ss',
                  'label': ['/fleurInput/atomGroups/atomGroup/relPos/@label',
                            '/fleurInput/atomGroups/atomGroup/absPos/@label',
                            '/fleurInput/atomGroups/atomGroup/filmPos/@label'],
                  'latnam': ['/fleurInput/cell/bulkLattice/@latnam',
                             '/fleurInput/cell/filmLattice/@latnam'],
                  'layers': '/fleurInput/output/vacuumDOS/@layers',
                  'lcutm': '/fleurInput/atomSpecies/species/prodBasis/@lcutm',
                  'lcutwf': '/fleurInput/atomSpecies/species/prodBasis/@lcutwf',
                  'lda': '/fleurInput/atomSpecies/species/special/@lda',
                  'lexp': '/fleurInput/calculationSetup/prodBasis/@lexp',
                  'lflip': '/fleurInput/calculationSetup/magnetism/@lflip',
                  'lmax': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lmax',
                           '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lmax',
                           '/fleurInput/output/coreSpectrum/@lmax'],
                  'lmaxAPW': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lmaxAPW',
                              '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lmaxAPW'],
                  'lnonsphr': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lnonsphr',
                               '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lnonsphr'],
                  'locx1': '/fleurInput/output/vacuumDOS/@locx1',
                  'locx2': '/fleurInput/output/vacuumDOS/@locx2',
                  'locy1': '/fleurInput/output/vacuumDOS/@locy1',
                  'locy2': '/fleurInput/output/vacuumDOS/@locy2',
                  'logIncrement': ['/fleurInput/atomSpecies/species/mtSphere/@logIncrement',
                                   '/fleurInput/atomGroups/atomGroup/mtSphere/@logIncrement'],
                  'lpr': '/fleurInput/calculationSetup/expertModes/@lpr',
                  'lwb': '/fleurInput/xcFunctional/xcParams/@lwb',
                  'm_cyl': '/fleurInput/calculationSetup/oneDParams/@m_cyl',
                  'magField': ['/fleurInput/atomSpecies/species/@magField',
                               '/fleurInput/atomGroups/atomGroup/@magField'],
                  'magMom': '/fleurInput/atomSpecies/species/@magMom',
                  'maxEigenval': '/fleurInput/output/chargeDensitySlicing/@maxEigenval',
                  'maxEnergy': '/fleurInput/output/densityOfStates/@maxEnergy',
                  'maxIterBroyd': '/fleurInput/calculationSetup/scfLoop/@maxIterBroyd',
                  'maxSpinDown': '/fleurInput/output/wannier/bandSelection/@maxSpinDown',
                  'maxSpinUp': '/fleurInput/output/wannier/bandSelection/@maxSpinUp',
                  'maxTimeToStartIter': '/fleurInput/calculationSetup/scfLoop/@maxTimeToStartIter',
                  'mcd': '/fleurInput/output/@mcd',
                  'minDistance': '/fleurInput/calculationSetup/scfLoop/@minDistance',
                  'minEigenval': '/fleurInput/output/chargeDensitySlicing/@minEigenval',
                  'minEnergy': '/fleurInput/output/densityOfStates/@minEnergy',
                  'minSpinDown': '/fleurInput/output/wannier/bandSelection/@minSpinDown',
                  'minSpinUp': '/fleurInput/output/wannier/bandSelection/@minSpinUp',
                  'mixParam': '/fleurInput/calculationSetup/ldaU/@mixParam',
                  'mix_b': '/fleurInput/calculationSetup/nocoParams/@mix_b',
                  'mode': '/fleurInput/calculationSetup/bzIntegration/@mode',
                  'ms': '/fleurInput/output/wannier/@ms',
                  'n': ['/fleurInput/atomSpecies/species/lo/@n',
                        '/fleurInput/atomGroups/atomGroup/lo/@n'],
                  'name': ['/fleurInput/constants/constant/@name',
                           '/fleurInput/xcFunctional/@name',
                           '/fleurInput/atomSpecies/species/@name',
                           '/fleurInput/calculationSetup/bzIntegration/kPointCount/specialPoint/@name',
                           '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount/specialPoint/@name'],
                  'ndir': '/fleurInput/output/densityOfStates/@ndir',
                  'ndvgrd': '/fleurInput/xcFunctional/xcParams/@ndvgrd',
                  'nnne': '/fleurInput/output/chargeDensitySlicing/@nnne',
                  'nqphi': '/fleurInput/output/coreSpectrum/@nqphi',
                  'nqr': '/fleurInput/output/coreSpectrum/@nqr',
                  'nsh': '/fleurInput/calculationSetup/nocoParams/@nsh',
                  'nstars': '/fleurInput/output/vacuumDOS/@nstars',
                  'nstm': '/fleurInput/output/vacuumDOS/@nstm',
                  'numPoints': '/fleurInput/output/coreSpectrum/@numPoints',
                  'numbands': '/fleurInput/calculationSetup/cutoffs/@numbands',
                  'numkpt': '/fleurInput/output/chargeDensitySlicing/@numkpt',
                  'nx': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh/@nx',
                         '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh/@nx'],
                  'ny': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh/@ny',
                         '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh/@ny'],
                  'nz': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh/@nz',
                         '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh/@nz'],
                  'occEps': '/fleurInput/calculationSetup/rdmft/@occEps',
                  'off': '/fleurInput/calculationSetup/soc/@off',
                  'orbcomp': ['/fleurInput/atomGroups/atomGroup/relPos/@orbcomp',
                              '/fleurInput/atomGroups/atomGroup/absPos/@orbcomp',
                              '/fleurInput/atomGroups/atomGroup/filmPos/@orbcomp'],
                  'p': ['/fleurInput/atomSpecies/species/energyParameters/@p',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@p'],
                  'pallst': '/fleurInput/output/chargeDensitySlicing/@pallst',
                  'phi': ['/fleurInput/calculationSetup/soc/@phi',
                          '/fleurInput/forceTheorem/MAE/@phi',
                          '/fleurInput/forceTheorem/DMI/@phi'],
                  'plot_charge': '/fleurInput/calculationSetup/fields/@plot_charge',
                  'plot_rho': '/fleurInput/calculationSetup/fields/@plot_rho',
                  'plplot': '/fleurInput/output/plotting/@plplot',
                  'posScale': ['/fleurInput/calculationSetup/bzIntegration/kPointList/@posScale',
                               '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/@posScale'],
                  'pot8': '/fleurInput/calculationSetup/expertModes/@pot8',
                  'preconditioning_param': '/fleurInput/calculationSetup/scfLoop/@preconditioning_param',
                  'purpose': '/fleurInput/calculationSetup/bzIntegration/altKPointSet/@purpose',
                  'qfix': '/fleurInput/calculationSetup/geometryOptimization/@qfix',
                  'qx': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qx',
                  'qy': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qy',
                  'qz': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qz',
                  'radius': ['/fleurInput/atomSpecies/species/mtSphere/@radius',
                             '/fleurInput/atomGroups/atomGroup/mtSphere/@radius'],
                  'relativisticCorrections': '/fleurInput/xcFunctional/@relativisticCorrections',
                  'relaxXYZ': ['/fleurInput/atomSpecies/species/force/@relaxXYZ',
                               '/fleurInput/atomGroups/atomGroup/force/@relaxXYZ'],
                  'rot': '/fleurInput/calculationSetup/oneDParams/@rot',
                  's': ['/fleurInput/atomSpecies/species/energyParameters/@s',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@s'],
                  'scale': ['/fleurInput/cell/bulkLattice/@scale',
                            '/fleurInput/cell/filmLattice/@scale',
                            '/fleurInput/cell/bulkLattice/a1/@scale',
                            '/fleurInput/cell/filmLattice/a1/@scale',
                            '/fleurInput/cell/bulkLattice/a2/@scale',
                            '/fleurInput/cell/filmLattice/a2/@scale',
                            '/fleurInput/cell/bulkLattice/c/@scale'],
                  'score': '/fleurInput/output/plotting/@score',
                  'secvar': '/fleurInput/calculationSetup/expertModes/@secvar',
                  'select': '/fleurInput/atomSpecies/species/prodBasis/@select',
                  'sgwf': '/fleurInput/output/wannier/@sgwf',
                  'sig_b_1': '/fleurInput/calculationSetup/fields/@sig_b_1',
                  'sig_b_2': '/fleurInput/calculationSetup/fields/@sig_b_2',
                  'sigma': '/fleurInput/output/densityOfStates/@sigma',
                  'slice': '/fleurInput/output/@slice',
                  'soc66': '/fleurInput/calculationSetup/soc/@soc66',
                  'socgwf': '/fleurInput/output/wannier/@socgwf',
                  'socscale': '/fleurInput/atomSpecies/species/special/@socscale',
                  'spav': '/fleurInput/calculationSetup/soc/@spav',
                  'species': '/fleurInput/atomGroups/atomGroup/@species',
                  'spgrp': '/fleurInput/cell/symmetry/@spgrp',
                  'spinDown': ['/fleurInput/cell/filmLattice/vacuumEnergyParameters/@spinDown',
                               '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@spinDown'],
                  'spinUp': ['/fleurInput/cell/filmLattice/vacuumEnergyParameters/@spinUp',
                             '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@spinUp'],
                  'spinf': ['/fleurInput/calculationSetup/scfLoop/@spinf',
                            '/fleurInput/calculationSetup/ldaU/@spinf'],
                  'sso_opt': '/fleurInput/calculationSetup/nocoParams/@sso_opt',
                  'star': '/fleurInput/output/vacuumDOS/@star',
                  'state': '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@state',
                  'statesAbove': '/fleurInput/calculationSetup/rdmft/@statesAbove',
                  'statesBelow': '/fleurInput/calculationSetup/rdmft/@statesBelow',
                  'supercellX': '/fleurInput/output/unfoldingBand/@supercellX',
                  'supercellY': '/fleurInput/output/unfoldingBand/@supercellY',
                  'supercellZ': '/fleurInput/output/unfoldingBand/@supercellZ',
                  'swsp': '/fleurInput/calculationSetup/magnetism/@swsp',
                  'theta': ['/fleurInput/calculationSetup/soc/@theta',
                            '/fleurInput/forceTheorem/MAE/@theta',
                            '/fleurInput/forceTheorem/DMI/@theta'],
                  'thetaJ': '/fleurInput/calculationSetup/nocoParams/@thetaJ',
                  'thetaj': '/fleurInput/forceTheorem/Jij/@thetaj',
                  'tolerance': '/fleurInput/calculationSetup/prodBasis/@tolerance',
                  'tworkf': '/fleurInput/output/vacuumDOS/@tworkf',
                  'type': ['/fleurInput/atomSpecies/species/lo/@type',
                           '/fleurInput/atomGroups/atomGroup/lo/@type'],
                  'unfoldband': '/fleurInput/output/unfoldingBand/@unfoldband',
                  'vM': '/fleurInput/calculationSetup/oneDParams/@vM',
                  'vacdos': '/fleurInput/output/@vacdos',
                  'vacuum': '/fleurInput/cell/filmLattice/vacuumEnergyParameters/@vacuum',
                  'valenceElectrons': '/fleurInput/calculationSetup/bzIntegration/@valenceElectrons',
                  'value': '/fleurInput/constants/constant/@value',
                  'vcaAddCharge': ['/fleurInput/atomSpecies/species/@vcaAddCharge',
                                   '/fleurInput/atomGroups/atomGroup/@vcaAddCharge'],
                  'vca_charge': '/fleurInput/atomSpecies/species/special/@vca_charge',
                  'vchk': '/fleurInput/output/checks/@vchk',
                  'verbose': '/fleurInput/output/coreSpectrum/@verbose',
                  'wannier': ['/fleurInput/atomGroups/atomGroup/relPos/@wannier',
                              '/fleurInput/atomGroups/atomGroup/absPos/@wannier',
                              '/fleurInput/atomGroups/atomGroup/filmPos/@wannier',
                              '/fleurInput/output/@wannier'],
                  'weight': ['/fleurInput/calculationSetup/bzIntegration/kPointList/kPoint/@weight',
                             '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/kPoint/@weight'],
                  'weightScale': ['/fleurInput/calculationSetup/bzIntegration/kPointList/@weightScale',
                                  '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/@weightScale'],
                  'zrfs': '/fleurInput/cell/symmetry/@zrfs',
                  'zrfs1': '/fleurInput/calculationSetup/oneDParams/@zrfs1',
                  'zsigma': '/fleurInput/calculationSetup/fields/@zsigma'},
 'attrib_types': {'Gmax': 'string',
                  'GmaxXC': 'string',
                  'I_initial': 'float',
                  'J': 'string',
                  'Kmax': 'string',
                  'M': 'string',
                  'MM': 'int',
                  'U': 'string',
                  'alpha': 'string',
                  'alpha_Ex': 'float',
                  'atomList': 'switch',
                  'atomType': 'int',
                  'atomicNumber': 'int',
                  'autocomp': 'switch',
                  'b_cons_x': 'string',
                  'b_cons_y': 'string',
                  'b_field': 'string',
                  'b_field_mt': 'string',
                  'band': 'switch',
                  'bands': 'int',
                  'beta': 'string',
                  'beta_Ex': 'float',
                  'bmt': 'switch',
                  'bsComf': 'switch',
                  'calculate': 'switch',
                  'cdinf': 'switch',
                  'chi': 'int',
                  'chng': 'float',
                  'coreSpec': 'switch',
                  'coreStates': 'int',
                  'coretail_lmax': 'int',
                  'correlation': ['int', 'string'],
                  'count': 'int',
                  'ctail': 'switch',
                  'd': 'int',
                  'd1': 'switch',
                  'dTilda': 'string',
                  'dVac': 'string',
                  'denX': 'float',
                  'denY': 'float',
                  'denZ': 'float',
                  'dirichlet': 'switch',
                  'disp': 'switch',
                  'dos': 'switch',
                  'eDeriv': 'int',
                  'eKin': 'float',
                  'eMax': 'float',
                  'eMin': 'float',
                  'eV': 'switch',
                  'edgeType': 'string',
                  'eig66': 'switch',
                  'element': 'string',
                  'ellow': 'string',
                  'elup': 'string',
                  'energy': 'string',
                  'energyLo': 'float',
                  'energyUp': 'float',
                  'eonly': 'switch',
                  'epsdisp': 'string',
                  'epsforce': 'string',
                  'ewaldlambda': 'int',
                  'exchange': ['int', 'string'],
                  'f': 'int',
                  'fermiSmearingEnergy': 'string',
                  'fermiSmearingTemp': 'string',
                  'filename': 'string',
                  'fixed_moment': 'string',
                  'fleurInputVersion': 'string',
                  'flipSpin': 'switch',
                  'force_converged': 'string',
                  'forcealpha': 'string',
                  'forcemix': 'int',
                  'form66': 'switch',
                  'frcor': 'switch',
                  'functional': 'string',
                  'gamma': 'switch',
                  'gcutm': 'float',
                  'gridPoints': 'int',
                  'gw': 'int',
                  'idsprs': 'int',
                  'idsprs0': 'int',
                  'idsprsi': 'int',
                  'idsprsl': 'int',
                  'idsprsv': 'float',
                  'iggachk': 'int',
                  'igrd': 'int',
                  'imix': 'string',
                  'integ': 'switch',
                  'invs': 'switch',
                  'invs1': 'switch',
                  'iplot': 'switch',
                  'isec1': 'int',
                  'itmax': 'int',
                  'jspins': 'int',
                  'kcrel': 'int',
                  'l': 'int',
                  'l_J': 'switch',
                  'l_amf': 'switch',
                  'l_constr': 'switch',
                  'l_disp': 'switch',
                  'l_f': 'switch',
                  'l_linMix': 'switch',
                  'l_magn': 'switch',
                  'l_mperp': 'switch',
                  'l_mtNocoPot': 'switch',
                  'l_noco': 'switch',
                  'l_rdmft': 'switch',
                  'l_relax': 'switch',
                  'l_soc': 'switch',
                  'l_ss': 'switch',
                  'label': 'string',
                  'latnam': 'string',
                  'layers': 'int',
                  'lcutm': 'int',
                  'lcutwf': 'int',
                  'lda': 'switch',
                  'lexp': 'int',
                  'lflip': 'switch',
                  'lmax': 'int',
                  'lmaxAPW': 'int',
                  'lnonsphr': 'int',
                  'locx1': 'string',
                  'locx2': 'string',
                  'locy1': 'string',
                  'locy2': 'string',
                  'logIncrement': 'string',
                  'lpr': 'int',
                  'lwb': 'switch',
                  'm_cyl': 'int',
                  'magField': 'float',
                  'magMom': 'string',
                  'maxEigenval': 'string',
                  'maxEnergy': 'string',
                  'maxIterBroyd': 'int',
                  'maxSpinDown': 'int',
                  'maxSpinUp': 'int',
                  'maxTimeToStartIter': 'string',
                  'mcd': 'switch',
                  'minDistance': 'string',
                  'minEigenval': 'string',
                  'minEnergy': 'string',
                  'minSpinDown': 'int',
                  'minSpinUp': 'int',
                  'mixParam': 'float',
                  'mix_b': 'string',
                  'mode': 'string',
                  'ms': 'switch',
                  'n': 'int',
                  'name': 'string',
                  'ndir': 'int',
                  'ndvgrd': 'int',
                  'nnne': 'int',
                  'nqphi': 'int',
                  'nqr': 'int',
                  'nsh': 'int',
                  'nstars': 'int',
                  'nstm': 'int',
                  'numPoints': 'int',
                  'numbands': ['int', 'string'],
                  'numkpt': 'int',
                  'nx': 'int',
                  'ny': 'int',
                  'nz': 'int',
                  'occEps': 'float',
                  'off': 'switch',
                  'orbcomp': 'switch',
                  'p': 'int',
                  'pallst': 'switch',
                  'phi': 'string',
                  'plot_charge': 'switch',
                  'plot_rho': 'switch',
                  'plplot': 'switch',
                  'posScale': 'string',
                  'pot8': 'switch',
                  'preconditioning_param': 'string',
                  'purpose': 'string',
                  'qfix': 'int',
                  'qx': 'int',
                  'qy': 'int',
                  'qz': 'int',
                  'radius': 'string',
                  'relativisticCorrections': 'switch',
                  'relaxXYZ': 'string',
                  'rot': 'int',
                  's': 'int',
                  'scale': 'string',
                  'score': 'switch',
                  'secvar': 'switch',
                  'select': 'string',
                  'sgwf': 'switch',
                  'sig_b_1': 'string',
                  'sig_b_2': 'string',
                  'sigma': 'string',
                  'slice': 'switch',
                  'soc66': 'switch',
                  'socgwf': 'switch',
                  'socscale': 'float',
                  'spav': 'switch',
                  'species': 'string',
                  'spgrp': 'string',
                  'spinDown': 'string',
                  'spinUp': 'string',
                  'spinf': ['float', 'string'],
                  'sso_opt': 'string',
                  'star': 'switch',
                  'state': 'string',
                  'statesAbove': 'int',
                  'statesBelow': 'int',
                  'supercellX': 'int',
                  'supercellY': 'int',
                  'supercellZ': 'int',
                  'swsp': 'switch',
                  'theta': 'string',
                  'thetaJ': 'string',
                  'thetaj': 'string',
                  'tolerance': 'float',
                  'tworkf': 'string',
                  'type': 'string',
                  'unfoldband': 'switch',
                  'vM': 'int',
                  'vacdos': 'switch',
                  'vacuum': 'int',
                  'valenceElectrons': 'string',
                  'value': 'string',
                  'vcaAddCharge': 'float',
                  'vca_charge': 'string',
                  'vchk': 'switch',
                  'verbose': 'switch',
                  'wannier': 'switch',
                  'weight': 'string',
                  'weightScale': 'string',
                  'zrfs': 'switch',
                  'zrfs1': 'switch',
                  'zsigma': 'string'},
 'basic_types': {'AtomPosType': {'base_types': ['string'], 'length': 3},
                 'BZIntegrationModeEnum': {'base_types': ['string'],
                                           'length': 1},
                 'CoreConfigEnum': {'base_types': ['string'], 'length': 1},
                 'CoreSpecEdgeEnum': {'base_types': ['string'], 'length': 1},
                 'CoreStateListType': {'base_types': ['string'],
                                       'length': 'unbounded'},
                 'DisplaceType': {'base_types': ['float'], 'length': 3},
                 'Double3DVecType': {'base_types': ['float'], 'length': 3},
                 'Double4DVecType': {'base_types': ['float'], 'length': 4},
                 'DoubleVecType': {'base_types': ['float'],
                                   'length': 'unbounded'},
                 'EParamSelectionEnum': {'base_types': ['string'], 'length': 1},
                 'ElectronStateEnum': {'base_types': ['string'], 'length': 1},
                 'FleurVersionType': {'base_types': ['string'], 'length': 1},
                 'IntegerVecType': {'base_types': ['int'],
                                    'length': 'unbounded'},
                 'KPointSetPurposeEnum': {'base_types': ['string'],
                                          'length': 1},
                 'KPointType': {'base_types': ['float'], 'length': 3},
                 'LatnamEnum': {'base_types': ['string'], 'length': 1},
                 'LatticeParameterType': {'base_types': ['string'],
                                          'length': 1},
                 'MixingEnum': {'base_types': ['string'], 'length': 1},
                 'NobleGasConfigEnum': {'base_types': ['string'], 'length': 1},
                 'NumBandsType': {'base_types': ['int', 'string'], 'length': 1},
                 'PositionType': {'base_types': ['float'], 'length': 3},
                 'RDMFTFunctionalEnum': {'base_types': ['string'], 'length': 1},
                 'SpecialPointType': {'base_types': ['string'], 'length': 3},
                 'SpgrpEnum': {'base_types': ['string'], 'length': 1},
                 'SpinNumberType': {'base_types': ['int'], 'length': 1},
                 'String2DVecType': {'base_types': ['string'], 'length': 2},
                 'String3DVecType': {'base_types': ['string'], 'length': 3},
                 'StringVecType': {'base_types': ['string'],
                                   'length': 'unbounded'},
                 'TripleFleurBool': {'base_types': ['string'], 'length': 1},
                 'ValenceStateListType': {'base_types': ['string'],
                                          'length': 'unbounded'},
                 'XCFunctionalEnum': {'base_types': ['string'], 'length': 1},
                 'ZeroToOneNumberType': {'base_types': ['float'], 'length': 1}},
 'omitt_contained_tags': ['constants',
                          'atomSpecies',
                          'atomGroups',
                          'symmetryOperations',
                          'displacements',
                          'relaxation-history',
                          'spinSpiralDispersion',
                          'qVectors'],
 'settable_attribs': {'Gmax': '/fleurInput/calculationSetup/cutoffs',
                      'GmaxXC': '/fleurInput/calculationSetup/cutoffs',
                      'I_initial': '/fleurInput/output/coreSpectrum',
                      'Kmax': '/fleurInput/calculationSetup/cutoffs',
                      'MM': '/fleurInput/calculationSetup/oneDParams',
                      'alpha_Ex': '/fleurInput/output/coreSpectrum',
                      'atomList': '/fleurInput/output/wannier',
                      'atomType': '/fleurInput/output/coreSpectrum',
                      'autocomp': '/fleurInput/calculationSetup/fields',
                      'b_field': '/fleurInput/calculationSetup/fields',
                      'band': '/fleurInput/output',
                      'bands': '/fleurInput/calculationSetup/prodBasis',
                      'beta_Ex': '/fleurInput/output/coreSpectrum',
                      'bmt': '/fleurInput/output/specialOutput',
                      'bsComf': '/fleurInput/output/wannier',
                      'c': '/fleurInput/cell/bulkLattice/c',
                      'cdinf': '/fleurInput/output/checks',
                      'chi': '/fleurInput/calculationSetup/oneDParams',
                      'chng': '/fleurInput/xcFunctional/xcParams',
                      'comment': '/fleurInput/comment',
                      'coreSpec': '/fleurInput/output',
                      'coretail_lmax': '/fleurInput/calculationSetup/coreElectrons',
                      'ctail': '/fleurInput/calculationSetup/coreElectrons',
                      'd1': '/fleurInput/calculationSetup/oneDParams',
                      'dTilda': '/fleurInput/cell/filmLattice',
                      'dVac': '/fleurInput/cell/filmLattice',
                      'dirichlet': '/fleurInput/calculationSetup/fields',
                      'disp': '/fleurInput/output/checks',
                      'dos': '/fleurInput/output',
                      'eKin': '/fleurInput/output/coreSpectrum',
                      'eMax': '/fleurInput/output/coreSpectrum',
                      'eMin': '/fleurInput/output/coreSpectrum',
                      'eV': '/fleurInput/calculationSetup/fields',
                      'edgeIndices': '/fleurInput/output/coreSpectrum/edgeIndices',
                      'edgeType': '/fleurInput/output/coreSpectrum',
                      'eig66': '/fleurInput/calculationSetup/expertModes',
                      'ellow': '/fleurInput/calculationSetup/energyParameterLimits',
                      'elup': '/fleurInput/calculationSetup/energyParameterLimits',
                      'energyLo': '/fleurInput/output/magneticCircularDichroism',
                      'energyUp': '/fleurInput/output/magneticCircularDichroism',
                      'eonly': '/fleurInput/output/specialOutput',
                      'epsdisp': '/fleurInput/calculationSetup/geometryOptimization',
                      'epsforce': '/fleurInput/calculationSetup/geometryOptimization',
                      'ewaldlambda': '/fleurInput/calculationSetup/prodBasis',
                      'fermiSmearingEnergy': '/fleurInput/calculationSetup/bzIntegration',
                      'fermiSmearingTemp': '/fleurInput/calculationSetup/bzIntegration',
                      'fixed_moment': '/fleurInput/calculationSetup/magnetism',
                      'fleurInputVersion': '/fleurInput',
                      'force_converged': '/fleurInput/calculationSetup/geometryOptimization',
                      'forcealpha': '/fleurInput/calculationSetup/geometryOptimization',
                      'forcemix': '/fleurInput/calculationSetup/geometryOptimization',
                      'form66': '/fleurInput/output/specialOutput',
                      'frcor': '/fleurInput/calculationSetup/coreElectrons',
                      'functional': '/fleurInput/calculationSetup/rdmft',
                      'gcutm': '/fleurInput/calculationSetup/prodBasis',
                      'gw': '/fleurInput/calculationSetup/expertModes',
                      'idsprs': '/fleurInput/xcFunctional/xcParams',
                      'idsprs0': '/fleurInput/xcFunctional/ggaPrinting',
                      'idsprsi': '/fleurInput/xcFunctional/ggaPrinting',
                      'idsprsl': '/fleurInput/xcFunctional/ggaPrinting',
                      'idsprsv': '/fleurInput/xcFunctional/ggaPrinting',
                      'iggachk': '/fleurInput/xcFunctional/ggaPrinting',
                      'igrd': '/fleurInput/xcFunctional/xcParams',
                      'imix': '/fleurInput/calculationSetup/scfLoop',
                      'integ': '/fleurInput/output/vacuumDOS',
                      'invs': '/fleurInput/cell/symmetry',
                      'invs1': '/fleurInput/calculationSetup/oneDParams',
                      'iplot': '/fleurInput/output/plotting',
                      'isec1': '/fleurInput/calculationSetup/expertModes',
                      'itmax': '/fleurInput/calculationSetup/scfLoop',
                      'jobList': '/fleurInput/output/wannier/jobList',
                      'jspins': '/fleurInput/calculationSetup/magnetism',
                      'kcrel': '/fleurInput/calculationSetup/coreElectrons',
                      'l_J': '/fleurInput/calculationSetup/magnetism',
                      'l_constr': '/fleurInput/calculationSetup/nocoParams',
                      'l_disp': '/fleurInput/calculationSetup/nocoParams',
                      'l_f': '/fleurInput/calculationSetup/geometryOptimization',
                      'l_linMix': '/fleurInput/calculationSetup/ldaU',
                      'l_mperp': '/fleurInput/calculationSetup/nocoParams',
                      'l_mtNocoPot': '/fleurInput/calculationSetup/nocoParams',
                      'l_noco': '/fleurInput/calculationSetup/magnetism',
                      'l_rdmft': '/fleurInput/calculationSetup/rdmft',
                      'l_soc': '/fleurInput/calculationSetup/soc',
                      'l_ss': '/fleurInput/calculationSetup/nocoParams',
                      'layers': '/fleurInput/output/vacuumDOS',
                      'lexp': '/fleurInput/calculationSetup/prodBasis',
                      'lflip': '/fleurInput/calculationSetup/magnetism',
                      'locx1': '/fleurInput/output/vacuumDOS',
                      'locx2': '/fleurInput/output/vacuumDOS',
                      'locy1': '/fleurInput/output/vacuumDOS',
                      'locy2': '/fleurInput/output/vacuumDOS',
                      'lpr': '/fleurInput/calculationSetup/expertModes',
                      'lwb': '/fleurInput/xcFunctional/xcParams',
                      'm_cyl': '/fleurInput/calculationSetup/oneDParams',
                      'maxEigenval': '/fleurInput/output/chargeDensitySlicing',
                      'maxEnergy': '/fleurInput/output/densityOfStates',
                      'maxIterBroyd': '/fleurInput/calculationSetup/scfLoop',
                      'maxSpinDown': '/fleurInput/output/wannier/bandSelection',
                      'maxSpinUp': '/fleurInput/output/wannier/bandSelection',
                      'maxTimeToStartIter': '/fleurInput/calculationSetup/scfLoop',
                      'mcd': '/fleurInput/output',
                      'minDistance': '/fleurInput/calculationSetup/scfLoop',
                      'minEigenval': '/fleurInput/output/chargeDensitySlicing',
                      'minEnergy': '/fleurInput/output/densityOfStates',
                      'minSpinDown': '/fleurInput/output/wannier/bandSelection',
                      'minSpinUp': '/fleurInput/output/wannier/bandSelection',
                      'mixParam': '/fleurInput/calculationSetup/ldaU',
                      'mix_b': '/fleurInput/calculationSetup/nocoParams',
                      'mode': '/fleurInput/calculationSetup/bzIntegration',
                      'ms': '/fleurInput/output/wannier',
                      'ndir': '/fleurInput/output/densityOfStates',
                      'ndvgrd': '/fleurInput/xcFunctional/xcParams',
                      'nnne': '/fleurInput/output/chargeDensitySlicing',
                      'nqphi': '/fleurInput/output/coreSpectrum',
                      'nqr': '/fleurInput/output/coreSpectrum',
                      'nsh': '/fleurInput/calculationSetup/nocoParams',
                      'nstars': '/fleurInput/output/vacuumDOS',
                      'nstm': '/fleurInput/output/vacuumDOS',
                      'numPoints': '/fleurInput/output/coreSpectrum',
                      'numbands': '/fleurInput/calculationSetup/cutoffs',
                      'numkpt': '/fleurInput/output/chargeDensitySlicing',
                      'occEps': '/fleurInput/calculationSetup/rdmft',
                      'off': '/fleurInput/calculationSetup/soc',
                      'pallst': '/fleurInput/output/chargeDensitySlicing',
                      'plot_charge': '/fleurInput/calculationSetup/fields',
                      'plot_rho': '/fleurInput/calculationSetup/fields',
                      'plplot': '/fleurInput/output/plotting',
                      'pot8': '/fleurInput/calculationSetup/expertModes',
                      'preconditioning_param': '/fleurInput/calculationSetup/scfLoop',
                      'qfix': '/fleurInput/calculationSetup/geometryOptimization',
                      'qsc': '/fleurInput/calculationSetup/nocoParams/qsc',
                      'qss': '/fleurInput/calculationSetup/nocoParams/qss',
                      'qx': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
                      'qy': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
                      'qz': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
                      'relativisticCorrections': '/fleurInput/xcFunctional',
                      'rot': '/fleurInput/calculationSetup/oneDParams',
                      'score': '/fleurInput/output/plotting',
                      'secvar': '/fleurInput/calculationSetup/expertModes',
                      'sgwf': '/fleurInput/output/wannier',
                      'sig_b_1': '/fleurInput/calculationSetup/fields',
                      'sig_b_2': '/fleurInput/calculationSetup/fields',
                      'sigma': '/fleurInput/output/densityOfStates',
                      'slice': '/fleurInput/output',
                      'soc66': '/fleurInput/calculationSetup/soc',
                      'socgwf': '/fleurInput/output/wannier',
                      'spav': '/fleurInput/calculationSetup/soc',
                      'spgrp': '/fleurInput/cell/symmetry',
                      'sso_opt': '/fleurInput/calculationSetup/nocoParams',
                      'star': '/fleurInput/output/vacuumDOS',
                      'statesAbove': '/fleurInput/calculationSetup/rdmft',
                      'statesBelow': '/fleurInput/calculationSetup/rdmft',
                      'supercellX': '/fleurInput/output/unfoldingBand',
                      'supercellY': '/fleurInput/output/unfoldingBand',
                      'supercellZ': '/fleurInput/output/unfoldingBand',
                      'swsp': '/fleurInput/calculationSetup/magnetism',
                      'thetaJ': '/fleurInput/calculationSetup/nocoParams',
                      'thetaj': '/fleurInput/forceTheorem/Jij',
                      'tolerance': '/fleurInput/calculationSetup/prodBasis',
                      'tworkf': '/fleurInput/output/vacuumDOS',
                      'unfoldband': '/fleurInput/output/unfoldingBand',
                      'vM': '/fleurInput/calculationSetup/oneDParams',
                      'vacdos': '/fleurInput/output',
                      'valenceElectrons': '/fleurInput/calculationSetup/bzIntegration',
                      'vchk': '/fleurInput/output/checks',
                      'verbose': '/fleurInput/output/coreSpectrum',
                      'zrfs': '/fleurInput/cell/symmetry',
                      'zrfs1': '/fleurInput/calculationSetup/oneDParams',
                      'zsigma': '/fleurInput/calculationSetup/fields'},
 'settable_contains_attribs': {'a1': ['/fleurInput/cell/bulkLattice/a1',
                                      '/fleurInput/cell/filmLattice/a1'],
                               'a2': ['/fleurInput/cell/bulkLattice/a2',
                                      '/fleurInput/cell/filmLattice/a2'],
                               'alpha': ['/fleurInput/calculationSetup/scfLoop'],
                               'correlation': ['/fleurInput/xcFunctional/LibXCID',
                                               '/fleurInput/xcFunctional/LibXCName'],
                               'count': ['/fleurInput/calculationSetup/bzIntegration/kPointCount',
                                         '/fleurInput/calculationSetup/bzIntegration/kPointList'],
                               'denX': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity'],
                               'denY': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity'],
                               'denZ': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity'],
                               'exchange': ['/fleurInput/xcFunctional/LibXCID',
                                            '/fleurInput/xcFunctional/LibXCName'],
                               'filename': ['/fleurInput/cell/symmetryFile'],
                               'gamma': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh',
                                         '/fleurInput/calculationSetup/bzIntegration/kPointCount',
                                         '/fleurInput/calculationSetup/bzIntegration/kPointDensity'],
                               'latnam': ['/fleurInput/cell/bulkLattice',
                                          '/fleurInput/cell/filmLattice'],
                               'lmax': ['/fleurInput/output/coreSpectrum'],
                               'name': ['/fleurInput/xcFunctional'],
                               'nx': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh'],
                               'ny': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh'],
                               'nz': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh'],
                               'phi': ['/fleurInput/calculationSetup/soc',
                                       '/fleurInput/forceTheorem/MAE',
                                       '/fleurInput/forceTheorem/DMI'],
                               'posScale': ['/fleurInput/calculationSetup/bzIntegration/kPointList'],
                               'row-1': ['/fleurInput/cell/bulkLattice/row-1',
                                         '/fleurInput/cell/filmLattice/row-1',
                                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-1',
                                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-1'],
                               'row-2': ['/fleurInput/cell/bulkLattice/row-2',
                                         '/fleurInput/cell/filmLattice/row-2',
                                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-2',
                                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-2'],
                               'row-3': ['/fleurInput/cell/bulkLattice/bravaisMatrix/row-3',
                                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-3'],
                               'scale': ['/fleurInput/cell/bulkLattice',
                                         '/fleurInput/cell/filmLattice',
                                         '/fleurInput/cell/bulkLattice/a1',
                                         '/fleurInput/cell/filmLattice/a1',
                                         '/fleurInput/cell/bulkLattice/a2',
                                         '/fleurInput/cell/filmLattice/a2',
                                         '/fleurInput/cell/bulkLattice/c'],
                               'spinf': ['/fleurInput/calculationSetup/scfLoop',
                                         '/fleurInput/calculationSetup/ldaU'],
                               'theta': ['/fleurInput/calculationSetup/soc',
                                         '/fleurInput/forceTheorem/MAE',
                                         '/fleurInput/forceTheorem/DMI'],
                               'wannier': ['/fleurInput/output'],
                               'weightScale': ['/fleurInput/calculationSetup/bzIntegration/kPointList']},
 'simple_elements': {'a1': {'length': 1, 'type': ['string']},
                     'a2': {'length': 1, 'type': ['string']},
                     'absPos': {'length': 3, 'type': ['string']},
                     'c': {'length': 1, 'type': ['string']},
                     'comment': {'length': 1, 'type': ['string']},
                     'coreConfig': {'length': 'unbounded', 'type': ['string']},
                     'displace': {'length': 3, 'type': ['float']},
                     'edgeIndices': {'length': 'unbounded', 'type': ['int']},
                     'filmPos': {'length': 3, 'type': ['string']},
                     'jobList': {'length': 'unbounded', 'type': ['string']},
                     'kPoint': {'length': 3, 'type': ['float']},
                     'orbcomprot': {'length': 3, 'type': ['float']},
                     'posforce': {'length': 1, 'type': ['string']},
                     'q': {'length': 1, 'type': ['string']},
                     'qsc': {'length': 3, 'type': ['float']},
                     'qss': {'length': 3, 'type': ['float']},
                     'relPos': {'length': 3, 'type': ['string']},
                     'row-1': [{'length': 2, 'type': ['string']},
                               {'length': 3, 'type': ['string']},
                               {'length': 4, 'type': ['float']}],
                     'row-2': [{'length': 2, 'type': ['string']},
                               {'length': 3, 'type': ['string']},
                               {'length': 4, 'type': ['float']}],
                     'row-3': [{'length': 3, 'type': ['string']},
                               {'length': 4, 'type': ['float']}],
                     'shape': {'length': 1, 'type': ['string']},
                     'specialPoint': {'length': 3, 'type': ['string']},
                     'valenceConfig': {'length': 'unbounded',
                                       'type': ['string']}},
 'tag_attribs': {'/fleurInput': ['fleurInputVersion'],
                 '/fleurInput/atomGroups/atomGroup': ['species',
                                                      'magField',
                                                      'vcaAddCharge'],
                 '/fleurInput/atomGroups/atomGroup/absPos': ['label',
                                                             'wannier',
                                                             'orbcomp'],
                 '/fleurInput/atomGroups/atomGroup/atomicCutoffs': ['lmax',
                                                                    'lnonsphr',
                                                                    'lmaxAPW'],
                 '/fleurInput/atomGroups/atomGroup/energyParameters': ['s',
                                                                       'p',
                                                                       'd',
                                                                       'f'],
                 '/fleurInput/atomGroups/atomGroup/filmPos': ['label',
                                                              'wannier',
                                                              'orbcomp'],
                 '/fleurInput/atomGroups/atomGroup/force': ['calculate',
                                                            'relaxXYZ'],
                 '/fleurInput/atomGroups/atomGroup/ldaU': ['l',
                                                           'U',
                                                           'J',
                                                           'l_amf'],
                 '/fleurInput/atomGroups/atomGroup/lo': ['type',
                                                         'l',
                                                         'n',
                                                         'eDeriv'],
                 '/fleurInput/atomGroups/atomGroup/mtSphere': ['radius',
                                                               'gridPoints',
                                                               'logIncrement'],
                 '/fleurInput/atomGroups/atomGroup/nocoParams': ['l_relax',
                                                                 'l_magn',
                                                                 'M',
                                                                 'alpha',
                                                                 'beta',
                                                                 'b_cons_x',
                                                                 'b_cons_y'],
                 '/fleurInput/atomGroups/atomGroup/relPos': ['label',
                                                             'wannier',
                                                             'orbcomp'],
                 '/fleurInput/atomSpecies/species': ['name',
                                                     'element',
                                                     'atomicNumber',
                                                     'coreStates',
                                                     'magMom',
                                                     'flipSpin',
                                                     'magField',
                                                     'vcaAddCharge'],
                 '/fleurInput/atomSpecies/species/atomicCutoffs': ['lmax',
                                                                   'lnonsphr',
                                                                   'lmaxAPW'],
                 '/fleurInput/atomSpecies/species/electronConfig/stateOccupation': ['state',
                                                                                    'spinUp',
                                                                                    'spinDown'],
                 '/fleurInput/atomSpecies/species/energyParameters': ['s',
                                                                      'p',
                                                                      'd',
                                                                      'f'],
                 '/fleurInput/atomSpecies/species/force': ['calculate',
                                                           'relaxXYZ'],
                 '/fleurInput/atomSpecies/species/ldaU': ['l',
                                                          'U',
                                                          'J',
                                                          'l_amf'],
                 '/fleurInput/atomSpecies/species/lo': ['type',
                                                        'l',
                                                        'n',
                                                        'eDeriv'],
                 '/fleurInput/atomSpecies/species/mtSphere': ['radius',
                                                              'gridPoints',
                                                              'logIncrement'],
                 '/fleurInput/atomSpecies/species/nocoParams': ['l_relax',
                                                                'l_magn',
                                                                'M',
                                                                'alpha',
                                                                'beta',
                                                                'b_cons_x',
                                                                'b_cons_y'],
                 '/fleurInput/atomSpecies/species/prodBasis': ['lcutm',
                                                               'lcutwf',
                                                               'select'],
                 '/fleurInput/atomSpecies/species/special': ['lda',
                                                             'socscale',
                                                             'b_field_mt',
                                                             'vca_charge'],
                 '/fleurInput/calculationSetup/bzIntegration': ['valenceElectrons',
                                                                'mode',
                                                                'fermiSmearingEnergy',
                                                                'fermiSmearingTemp'],
                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet': ['purpose'],
                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount': ['count',
                                                                                         'gamma'],
                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount/specialPoint': ['name'],
                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity': ['denX',
                                                                                           'denY',
                                                                                           'denZ',
                                                                                           'gamma'],
                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList': ['posScale',
                                                                                        'weightScale',
                                                                                        'count'],
                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/kPoint': ['weight'],
                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointListFile': ['filename'],
                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh': ['nx',
                                                                                        'ny',
                                                                                        'nz',
                                                                                        'gamma'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointCount': ['count',
                                                                            'gamma'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointCount/specialPoint': ['name'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointDensity': ['denX',
                                                                              'denY',
                                                                              'denZ',
                                                                              'gamma'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointList': ['posScale',
                                                                           'weightScale',
                                                                           'count'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointList/kPoint': ['weight'],
                 '/fleurInput/calculationSetup/bzIntegration/kPointMesh': ['nx',
                                                                           'ny',
                                                                           'nz',
                                                                           'gamma'],
                 '/fleurInput/calculationSetup/coreElectrons': ['ctail',
                                                                'frcor',
                                                                'kcrel',
                                                                'coretail_lmax'],
                 '/fleurInput/calculationSetup/cutoffs': ['Kmax',
                                                          'Gmax',
                                                          'GmaxXC',
                                                          'numbands'],
                 '/fleurInput/calculationSetup/energyParameterLimits': ['ellow',
                                                                        'elup'],
                 '/fleurInput/calculationSetup/expertModes': ['gw',
                                                              'pot8',
                                                              'eig66',
                                                              'lpr',
                                                              'isec1',
                                                              'secvar'],
                 '/fleurInput/calculationSetup/fields': ['b_field',
                                                         'zsigma',
                                                         'sig_b_1',
                                                         'sig_b_2',
                                                         'plot_charge',
                                                         'plot_rho',
                                                         'autocomp',
                                                         'dirichlet',
                                                         'eV'],
                 '/fleurInput/calculationSetup/geometryOptimization': ['l_f',
                                                                       'forcealpha',
                                                                       'epsdisp',
                                                                       'epsforce',
                                                                       'forcemix',
                                                                       'qfix',
                                                                       'force_converged'],
                 '/fleurInput/calculationSetup/ldaU': ['l_linMix',
                                                       'mixParam',
                                                       'spinf'],
                 '/fleurInput/calculationSetup/magnetism': ['jspins',
                                                            'l_noco',
                                                            'l_J',
                                                            'swsp',
                                                            'lflip',
                                                            'fixed_moment'],
                 '/fleurInput/calculationSetup/nocoParams': ['l_ss',
                                                             'l_mperp',
                                                             'l_constr',
                                                             'l_disp',
                                                             'sso_opt',
                                                             'mix_b',
                                                             'thetaJ',
                                                             'nsh',
                                                             'l_mtNocoPot'],
                 '/fleurInput/calculationSetup/oneDParams': ['d1',
                                                             'MM',
                                                             'vM',
                                                             'm_cyl',
                                                             'chi',
                                                             'rot',
                                                             'invs1',
                                                             'zrfs1'],
                 '/fleurInput/calculationSetup/prodBasis': ['gcutm',
                                                            'bands',
                                                            'tolerance',
                                                            'lexp',
                                                            'ewaldlambda'],
                 '/fleurInput/calculationSetup/rdmft': ['l_rdmft',
                                                        'occEps',
                                                        'statesBelow',
                                                        'statesAbove',
                                                        'functional'],
                 '/fleurInput/calculationSetup/scfLoop': ['itmax',
                                                          'maxIterBroyd',
                                                          'imix',
                                                          'alpha',
                                                          'preconditioning_param',
                                                          'spinf',
                                                          'minDistance',
                                                          'maxTimeToStartIter'],
                 '/fleurInput/calculationSetup/soc': ['theta',
                                                      'phi',
                                                      'l_soc',
                                                      'spav',
                                                      'off',
                                                      'soc66'],
                 '/fleurInput/calculationSetup/spinSpiralQPointMesh': ['qx',
                                                                       'qy',
                                                                       'qz'],
                 '/fleurInput/cell/bulkLattice': ['scale', 'latnam'],
                 '/fleurInput/cell/bulkLattice/a1': ['scale'],
                 '/fleurInput/cell/bulkLattice/a2': ['scale'],
                 '/fleurInput/cell/bulkLattice/c': ['scale'],
                 '/fleurInput/cell/filmLattice': ['scale',
                                                  'latnam',
                                                  'dVac',
                                                  'dTilda'],
                 '/fleurInput/cell/filmLattice/a1': ['scale'],
                 '/fleurInput/cell/filmLattice/a2': ['scale'],
                 '/fleurInput/cell/filmLattice/vacuumEnergyParameters': ['vacuum',
                                                                         'spinUp',
                                                                         'spinDown'],
                 '/fleurInput/cell/symmetry': ['spgrp', 'invs', 'zrfs'],
                 '/fleurInput/cell/symmetryFile': ['filename'],
                 '/fleurInput/constants/constant': ['name', 'value'],
                 '/fleurInput/forceTheorem/DMI': ['theta', 'phi'],
                 '/fleurInput/forceTheorem/Jij': ['thetaj'],
                 '/fleurInput/forceTheorem/MAE': ['theta', 'phi'],
                 '/fleurInput/output': ['dos',
                                        'band',
                                        'vacdos',
                                        'slice',
                                        'coreSpec',
                                        'wannier',
                                        'mcd'],
                 '/fleurInput/output/chargeDensitySlicing': ['numkpt',
                                                             'minEigenval',
                                                             'maxEigenval',
                                                             'nnne',
                                                             'pallst'],
                 '/fleurInput/output/checks': ['vchk', 'cdinf', 'disp'],
                 '/fleurInput/output/coreSpectrum': ['eKin',
                                                     'atomType',
                                                     'lmax',
                                                     'edgeType',
                                                     'eMin',
                                                     'eMax',
                                                     'numPoints',
                                                     'verbose',
                                                     'nqphi',
                                                     'nqr',
                                                     'alpha_Ex',
                                                     'beta_Ex',
                                                     'I_initial'],
                 '/fleurInput/output/densityOfStates': ['ndir',
                                                        'minEnergy',
                                                        'maxEnergy',
                                                        'sigma'],
                 '/fleurInput/output/magneticCircularDichroism': ['energyLo',
                                                                  'energyUp'],
                 '/fleurInput/output/plotting': ['iplot', 'score', 'plplot'],
                 '/fleurInput/output/specialOutput': ['form66', 'eonly', 'bmt'],
                 '/fleurInput/output/unfoldingBand': ['unfoldband',
                                                      'supercellX',
                                                      'supercellY',
                                                      'supercellZ'],
                 '/fleurInput/output/vacuumDOS': ['layers',
                                                  'integ',
                                                  'star',
                                                  'nstars',
                                                  'locx1',
                                                  'locy1',
                                                  'locx2',
                                                  'locy2',
                                                  'nstm',
                                                  'tworkf'],
                 '/fleurInput/output/wannier': ['ms',
                                                'sgwf',
                                                'socgwf',
                                                'bsComf',
                                                'atomList'],
                 '/fleurInput/output/wannier/bandSelection': ['minSpinUp',
                                                              'maxSpinUp',
                                                              'minSpinDown',
                                                              'maxSpinDown'],
                 '/fleurInput/relaxation/relaxation-history/step': ['energy'],
                 '/fleurInput/xcFunctional': ['name',
                                              'relativisticCorrections'],
                 '/fleurInput/xcFunctional/LibXCID': ['exchange',
                                                      'correlation'],
                 '/fleurInput/xcFunctional/LibXCName': ['exchange',
                                                        'correlation'],
                 '/fleurInput/xcFunctional/ggaPrinting': ['iggachk',
                                                          'idsprs0',
                                                          'idsprsl',
                                                          'idsprsi',
                                                          'idsprsv'],
                 '/fleurInput/xcFunctional/xcParams': ['igrd',
                                                       'lwb',
                                                       'ndvgrd',
                                                       'idsprs',
                                                       'chng']},
 'tag_order': {'altKPointSet': ['kPointMesh',
                                'kPointCount',
                                'kPointList',
                                'kPointDensity',
                                'kPointListFile'],
               'atomGroup': [['relPos', 'absPos', 'filmPos'],
                             'mtSphere',
                             'atomicCutoffs',
                             'energyParameters',
                             'force',
                             'nocoParams',
                             'ldaU',
                             'lo',
                             'orbcomprot'],
               'atomGroups': 'atomGroup',
               'atomSpecies': 'species',
               'bravaisMatrix': ['row-1', 'row-2', 'row-3'],
               'bulkLattice': [['a1', 'a2', 'c'],
                               ['row-1', 'row-2', 'c'],
                               'bravaisMatrix'],
               'bzIntegration': [['kPointMesh',
                                  'kPointCount',
                                  'kPointList',
                                  'kPointDensity'],
                                 'altKPointSet'],
               'cell': [['symmetry', 'symmetryFile', 'symmetryOperations'],
                        ['bulkLattice', 'filmLattice']],
               'constants': 'constant',
               'coreSpectrum': 'edgeIndices',
               'displacements': 'displace',
               'electronConfig': ['coreConfig',
                                  'valenceConfig',
                                  'stateOccupation'],
               'fields': 'shape',
               'filmLattice': [[['a1', 'a2'],
                                ['row-1', 'row-2'],
                                'bravaisMatrix'],
                               'vacuumEnergyParameters'],
               'kPointCount': 'specialPoint',
               'kPointList': 'kPoint',
               'nocoParams': ['qss', 'qsc'],
               'relaxation-history': 'step',
               'species': ['mtSphere',
                           'atomicCutoffs',
                           'energyParameters',
                           'prodBasis',
                           'special',
                           'force',
                           'electronConfig',
                           'nocoParams',
                           'ldaU',
                           'lo'],
               'spinSpiralDispersion': 'q',
               'step': 'posforce',
               'symOp': ['row-1', 'row-2', 'row-3'],
               'symmetryOperations': 'symOp',
               'xcFunctional': ['LibXCID',
                                'LibXCName',
                                'xcParams',
                                'ggaPrinting']},
 'tag_paths': {'DMI': '/fleurInput/forceTheorem/DMI',
               'Jij': '/fleurInput/forceTheorem/Jij',
               'LibXCID': '/fleurInput/xcFunctional/LibXCID',
               'LibXCName': '/fleurInput/xcFunctional/LibXCName',
               'MAE': '/fleurInput/forceTheorem/MAE',
               'a1': ['/fleurInput/cell/bulkLattice/a1',
                      '/fleurInput/cell/filmLattice/a1'],
               'a2': ['/fleurInput/cell/bulkLattice/a2',
                      '/fleurInput/cell/filmLattice/a2'],
               'absPos': '/fleurInput/atomGroups/atomGroup/absPos',
               'altKPointSet': '/fleurInput/calculationSetup/bzIntegration/altKPointSet',
               'atomGroup': '/fleurInput/atomGroups/atomGroup',
               'atomGroups': '/fleurInput/atomGroups',
               'atomSpecies': '/fleurInput/atomSpecies',
               'atomicCutoffs': ['/fleurInput/atomSpecies/species/atomicCutoffs',
                                 '/fleurInput/atomGroups/atomGroup/atomicCutoffs'],
               'bandSelection': '/fleurInput/output/wannier/bandSelection',
               'bravaisMatrix': ['/fleurInput/cell/bulkLattice/bravaisMatrix',
                                 '/fleurInput/cell/filmLattice/bravaisMatrix'],
               'bulkLattice': '/fleurInput/cell/bulkLattice',
               'bzIntegration': '/fleurInput/calculationSetup/bzIntegration',
               'c': '/fleurInput/cell/bulkLattice/c',
               'calculationSetup': '/fleurInput/calculationSetup',
               'cell': '/fleurInput/cell',
               'chargeDensitySlicing': '/fleurInput/output/chargeDensitySlicing',
               'checks': '/fleurInput/output/checks',
               'comment': '/fleurInput/comment',
               'constant': '/fleurInput/constants/constant',
               'constants': '/fleurInput/constants',
               'coreConfig': '/fleurInput/atomSpecies/species/electronConfig/coreConfig',
               'coreElectrons': '/fleurInput/calculationSetup/coreElectrons',
               'coreSpectrum': '/fleurInput/output/coreSpectrum',
               'cutoffs': '/fleurInput/calculationSetup/cutoffs',
               'densityOfStates': '/fleurInput/output/densityOfStates',
               'displace': '/fleurInput/relaxation/displacements/displace',
               'displacements': '/fleurInput/relaxation/displacements',
               'edgeIndices': '/fleurInput/output/coreSpectrum/edgeIndices',
               'electronConfig': '/fleurInput/atomSpecies/species/electronConfig',
               'energyParameterLimits': '/fleurInput/calculationSetup/energyParameterLimits',
               'energyParameters': ['/fleurInput/atomSpecies/species/energyParameters',
                                    '/fleurInput/atomGroups/atomGroup/energyParameters'],
               'expertModes': '/fleurInput/calculationSetup/expertModes',
               'fields': '/fleurInput/calculationSetup/fields',
               'filmLattice': '/fleurInput/cell/filmLattice',
               'filmPos': '/fleurInput/atomGroups/atomGroup/filmPos',
               'fleurInput': '/fleurInput',
               'force': ['/fleurInput/atomSpecies/species/force',
                         '/fleurInput/atomGroups/atomGroup/force'],
               'forceTheorem': '/fleurInput/forceTheorem',
               'geometryOptimization': '/fleurInput/calculationSetup/geometryOptimization',
               'ggaPrinting': '/fleurInput/xcFunctional/ggaPrinting',
               'jobList': '/fleurInput/output/wannier/jobList',
               'kPoint': ['/fleurInput/calculationSetup/bzIntegration/kPointList/kPoint',
                          '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList/kPoint'],
               'kPointCount': ['/fleurInput/calculationSetup/bzIntegration/kPointCount',
                               '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount'],
               'kPointDensity': ['/fleurInput/calculationSetup/bzIntegration/kPointDensity',
                                 '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointDensity'],
               'kPointList': ['/fleurInput/calculationSetup/bzIntegration/kPointList',
                              '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointList'],
               'kPointListFile': '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointListFile',
               'kPointMesh': ['/fleurInput/calculationSetup/bzIntegration/kPointMesh',
                              '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointMesh'],
               'ldaU': ['/fleurInput/calculationSetup/ldaU',
                        '/fleurInput/atomSpecies/species/ldaU',
                        '/fleurInput/atomGroups/atomGroup/ldaU'],
               'lo': ['/fleurInput/atomSpecies/species/lo',
                      '/fleurInput/atomGroups/atomGroup/lo'],
               'magneticCircularDichroism': '/fleurInput/output/magneticCircularDichroism',
               'magnetism': '/fleurInput/calculationSetup/magnetism',
               'mtSphere': ['/fleurInput/atomSpecies/species/mtSphere',
                            '/fleurInput/atomGroups/atomGroup/mtSphere'],
               'nocoParams': ['/fleurInput/calculationSetup/nocoParams',
                              '/fleurInput/atomSpecies/species/nocoParams',
                              '/fleurInput/atomGroups/atomGroup/nocoParams'],
               'oneDParams': '/fleurInput/calculationSetup/oneDParams',
               'orbcomprot': '/fleurInput/atomGroups/atomGroup/orbcomprot',
               'output': '/fleurInput/output',
               'plotting': '/fleurInput/output/plotting',
               'posforce': '/fleurInput/relaxation/relaxation-history/step/posforce',
               'prodBasis': ['/fleurInput/calculationSetup/prodBasis',
                             '/fleurInput/atomSpecies/species/prodBasis'],
               'q': ['/fleurInput/forceTheorem/spinSpiralDispersion/q',
                     '/fleurInput/forceTheorem/DMI/qVectors/q',
                     '/fleurInput/forceTheorem/Jij/qVectors/q'],
               'qVectors': ['/fleurInput/forceTheorem/DMI/qVectors',
                            '/fleurInput/forceTheorem/Jij/qVectors'],
               'qsc': '/fleurInput/calculationSetup/nocoParams/qsc',
               'qss': '/fleurInput/calculationSetup/nocoParams/qss',
               'rdmft': '/fleurInput/calculationSetup/rdmft',
               'relPos': '/fleurInput/atomGroups/atomGroup/relPos',
               'relaxation': '/fleurInput/relaxation',
               'relaxation-history': '/fleurInput/relaxation/relaxation-history',
               'row-1': ['/fleurInput/cell/bulkLattice/row-1',
                         '/fleurInput/cell/filmLattice/row-1',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-1',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-1',
                         '/fleurInput/cell/symmetryOperations/symOp/row-1'],
               'row-2': ['/fleurInput/cell/bulkLattice/row-2',
                         '/fleurInput/cell/filmLattice/row-2',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-2',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-2',
                         '/fleurInput/cell/symmetryOperations/symOp/row-2'],
               'row-3': ['/fleurInput/cell/bulkLattice/bravaisMatrix/row-3',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-3',
                         '/fleurInput/cell/symmetryOperations/symOp/row-3'],
               'scfLoop': '/fleurInput/calculationSetup/scfLoop',
               'shape': '/fleurInput/calculationSetup/fields/shape',
               'soc': '/fleurInput/calculationSetup/soc',
               'special': '/fleurInput/atomSpecies/species/special',
               'specialOutput': '/fleurInput/output/specialOutput',
               'specialPoint': ['/fleurInput/calculationSetup/bzIntegration/kPointCount/specialPoint',
                                '/fleurInput/calculationSetup/bzIntegration/altKPointSet/kPointCount/specialPoint'],
               'species': '/fleurInput/atomSpecies/species',
               'spinSpiralDispersion': '/fleurInput/forceTheorem/spinSpiralDispersion',
               'spinSpiralQPointMesh': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
               'stateOccupation': '/fleurInput/atomSpecies/species/electronConfig/stateOccupation',
               'step': '/fleurInput/relaxation/relaxation-history/step',
               'symOp': '/fleurInput/cell/symmetryOperations/symOp',
               'symmetry': '/fleurInput/cell/symmetry',
               'symmetryFile': '/fleurInput/cell/symmetryFile',
               'symmetryOperations': '/fleurInput/cell/symmetryOperations',
               'unfoldingBand': '/fleurInput/output/unfoldingBand',
               'vacuumDOS': '/fleurInput/output/vacuumDOS',
               'vacuumEnergyParameters': '/fleurInput/cell/filmLattice/vacuumEnergyParameters',
               'valenceConfig': '/fleurInput/atomSpecies/species/electronConfig/valenceConfig',
               'wannier': '/fleurInput/output/wannier',
               'xcFunctional': '/fleurInput/xcFunctional',
               'xcParams': '/fleurInput/xcFunctional/xcParams'},
 'tags_several': ['constant',
                  'shape',
                  'symOp',
                  'vacuumEnergyParameters',
                  'species',
                  'ldaU',
                  'lo',
                  'atomGroup',
                  'relPos',
                  'absPos',
                  'filmPos',
                  'altKPointSet',
                  'specialPoint',
                  'kPoint',
                  'displace',
                  'step',
                  'posforce',
                  'q',
                  'stateOccupation']}
