# -*- coding: utf-8 -*-
__inp_version__ = '0.32'
schema_dict = {'attrib_paths': {'Gmax': '/fleurInput/calculationSetup/cutoffs/@Gmax',
                  'GmaxXC': '/fleurInput/calculationSetup/cutoffs/@GmaxXC',
                  'I_initial': '/fleurInput/output/coreSpectrum/@I_initial',
                  'J': ['/fleurInput/atomSpecies/species/ldaU/@J',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@J',
                        '/fleurInput/atomSpecies/species/ldaHIA/@J',
                        '/fleurInput/atomGroups/atomGroup/ldaHIA/@J',
                        '/fleurInput/atomSpecies/species/ldaHIA/exc/@J',
                        '/fleurInput/atomGroups/atomGroup/ldaHIA/exc/@J'],
                  'Kmax': '/fleurInput/calculationSetup/cutoffs/@Kmax',
                  'M': ['/fleurInput/atomSpecies/species/nocoParams/@M',
                        '/fleurInput/atomGroups/atomGroup/nocoParams/@M'],
                  'MM': '/fleurInput/calculationSetup/oneDParams/@MM',
                  'TwoD': '/fleurInput/output/plotting/plot/@TwoD',
                  'U': ['/fleurInput/atomSpecies/species/ldaU/@U',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@U',
                        '/fleurInput/atomSpecies/species/ldaHIA/@U',
                        '/fleurInput/atomGroups/atomGroup/ldaHIA/@U'],
                  'all_atoms': '/fleurInput/output/bandDOS/@all_atoms',
                  'alpha': ['/fleurInput/atomSpecies/species/nocoParams/@alpha',
                            '/fleurInput/atomGroups/atomGroup/nocoParams/@alpha',
                            '/fleurInput/calculationSetup/scfLoop/@alpha',
                            '/fleurInput/calculationSetup/greensFunction/contourSemicircle/@alpha'],
                  'alpha_Ex': '/fleurInput/output/coreSpectrum/@alpha_Ex',
                  'analytical_cont': '/fleurInput/calculationSetup/greensFunction/contourDOS/@analytical_cont',
                  'atomList': '/fleurInput/output/wannier/@atomList',
                  'atomType': '/fleurInput/output/coreSpectrum/@atomType',
                  'atomicNumber': '/fleurInput/atomSpecies/species/@atomicNumber',
                  'autocomp': '/fleurInput/calculationSetup/fields/@autocomp',
                  'b_cons_x': ['/fleurInput/atomSpecies/species/nocoParams/@b_cons_x',
                               '/fleurInput/atomGroups/atomGroup/nocoParams/@b_cons_x'],
                  'b_cons_y': ['/fleurInput/atomSpecies/species/nocoParams/@b_cons_y',
                               '/fleurInput/atomGroups/atomGroup/nocoParams/@b_cons_y'],
                  'b_field': '/fleurInput/calculationSetup/fields/@b_field',
                  'b_field_mt': '/fleurInput/atomSpecies/species/special/@b_field_mt',
                  'band': '/fleurInput/output/@band',
                  'banddos': ['/fleurInput/atomGroups/atomGroup/relPos/@banddos',
                              '/fleurInput/atomGroups/atomGroup/absPos/@banddos',
                              '/fleurInput/atomGroups/atomGroup/filmPos/@banddos'],
                  'bands': '/fleurInput/calculationSetup/prodBasis/@bands',
                  'beta': ['/fleurInput/atomSpecies/species/nocoParams/@beta',
                           '/fleurInput/atomGroups/atomGroup/nocoParams/@beta',
                           '/fleurInput/calculationSetup/ldaHIA/@beta'],
                  'beta_Ex': '/fleurInput/output/coreSpectrum/@beta_Ex',
                  'bmt': '/fleurInput/output/specialOutput/@bmt',
                  'bsComf': '/fleurInput/output/wannier/@bsComf',
                  'calculate': ['/fleurInput/atomSpecies/species/force/@calculate',
                                '/fleurInput/atomGroups/atomGroup/force/@calculate'],
                  'cartesian': '/fleurInput/output/plotting/plot/@cartesian',
                  'cdinf': '/fleurInput/output/checks/@cdinf',
                  'chargeDensity': '/fleurInput/atomGroups/atomGroup/cFCoeffs/@chargeDensity',
                  'chi': '/fleurInput/calculationSetup/oneDParams/@chi',
                  'chng': '/fleurInput/xcFunctional/xcParams/@chng',
                  'coreSpec': '/fleurInput/output/@coreSpec',
                  'coretail_lmax': '/fleurInput/calculationSetup/coreElectrons/@coretail_lmax',
                  'correlation': ['/fleurInput/xcFunctional/LibXCID/@correlation',
                                  '/fleurInput/xcFunctional/LibXCName/@correlation'],
                  'count': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/@count',
                  'ctail': '/fleurInput/calculationSetup/coreElectrons/@ctail',
                  'd': ['/fleurInput/atomSpecies/species/greensfCalculation/diagElements/@d',
                        '/fleurInput/atomGroups/atomGroup/greensfCalculation/diagElements/@d',
                        '/fleurInput/atomSpecies/species/energyParameters/@d',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@d'],
                  'd1': '/fleurInput/calculationSetup/oneDParams/@d1',
                  'dTilda': '/fleurInput/cell/filmLattice/@dTilda',
                  'dVac': '/fleurInput/cell/filmLattice/@dVac',
                  'dftspinpol': '/fleurInput/calculationSetup/ldaHIA/@dftspinpol',
                  'dirichlet': '/fleurInput/calculationSetup/fields/@dirichlet',
                  'disp': '/fleurInput/output/checks/@disp',
                  'dos': '/fleurInput/output/@dos',
                  'eDeriv': ['/fleurInput/atomSpecies/species/lo/@eDeriv',
                             '/fleurInput/atomGroups/atomGroup/lo/@eDeriv'],
                  'eKin': '/fleurInput/output/coreSpectrum/@eKin',
                  'eMax': '/fleurInput/output/coreSpectrum/@eMax',
                  'eMin': '/fleurInput/output/coreSpectrum/@eMin',
                  'eV': '/fleurInput/calculationSetup/fields/@eV',
                  'eb': ['/fleurInput/calculationSetup/greensFunction/contourRectangle/@eb',
                         '/fleurInput/calculationSetup/greensFunction/contourSemicircle/@eb',
                         '/fleurInput/calculationSetup/greensFunction/contourDOS/@eb'],
                  'edgeType': '/fleurInput/output/coreSpectrum/@edgeType',
                  'eig66': ['/fleurInput/calculationSetup/expertModes/@eig66',
                            '/fleurInput/output/@eig66'],
                  'element': '/fleurInput/atomSpecies/species/@element',
                  'ellow': ['/fleurInput/calculationSetup/energyParameterLimits/@ellow',
                            '/fleurInput/calculationSetup/greensFunction/realAxis/@ellow'],
                  'elup': ['/fleurInput/calculationSetup/energyParameterLimits/@elup',
                           '/fleurInput/calculationSetup/greensFunction/realAxis/@elup'],
                  'energy': '/fleurInput/relaxation/relaxation-history/step/@energy',
                  'energyLo': '/fleurInput/output/magneticCircularDichroism/@energyLo',
                  'energyUp': '/fleurInput/output/magneticCircularDichroism/@energyUp',
                  'eonly': '/fleurInput/output/specialOutput/@eonly',
                  'epsdisp': '/fleurInput/calculationSetup/geometryOptimization/@epsdisp',
                  'epsforce': '/fleurInput/calculationSetup/geometryOptimization/@epsforce',
                  'et': ['/fleurInput/calculationSetup/greensFunction/contourSemicircle/@et',
                         '/fleurInput/calculationSetup/greensFunction/contourDOS/@et'],
                  'etot_correlation': ['/fleurInput/xcFunctional/LibXCID/@etot_correlation',
                                       '/fleurInput/xcFunctional/LibXCName/@etot_correlation'],
                  'etot_exchange': ['/fleurInput/xcFunctional/LibXCID/@etot_exchange',
                                    '/fleurInput/xcFunctional/LibXCName/@etot_exchange'],
                  'ewaldlambda': '/fleurInput/calculationSetup/prodBasis/@ewaldlambda',
                  'exchange': ['/fleurInput/xcFunctional/LibXCID/@exchange',
                               '/fleurInput/xcFunctional/LibXCName/@exchange'],
                  'f': ['/fleurInput/atomSpecies/species/greensfCalculation/diagElements/@f',
                        '/fleurInput/atomGroups/atomGroup/greensfCalculation/diagElements/@f',
                        '/fleurInput/atomSpecies/species/energyParameters/@f',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@f'],
                  'fermiSmearingEnergy': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingEnergy',
                  'fermiSmearingTemp': '/fleurInput/calculationSetup/bzIntegration/@fermiSmearingTemp',
                  'file': '/fleurInput/output/plotting/plot/@file',
                  'fixed_moment': '/fleurInput/calculationSetup/magnetism/@fixed_moment',
                  'fleurInputVersion': '/fleurInput/@fleurInputVersion',
                  'flipSpinPhi': '/fleurInput/atomSpecies/species/@flipSpinPhi',
                  'flipSpinScale': '/fleurInput/atomSpecies/species/@flipSpinScale',
                  'flipSpinTheta': '/fleurInput/atomSpecies/species/@flipSpinTheta',
                  'force_converged': '/fleurInput/calculationSetup/geometryOptimization/@force_converged',
                  'forcealpha': '/fleurInput/calculationSetup/geometryOptimization/@forcealpha',
                  'forcemix': '/fleurInput/calculationSetup/geometryOptimization/@forcemix',
                  'form66': '/fleurInput/output/specialOutput/@form66',
                  'format': '/fleurInput/output/plotting/@format',
                  'frcor': '/fleurInput/calculationSetup/coreElectrons/@frcor',
                  'fullMatch': '/fleurInput/calculationSetup/ldaHIA/@fullMatch',
                  'functional': '/fleurInput/calculationSetup/rdmft/@functional',
                  'gcutm': '/fleurInput/calculationSetup/prodBasis/@gcutm',
                  'grid': '/fleurInput/output/plotting/plot/@grid',
                  'gridPoints': ['/fleurInput/atomSpecies/species/mtSphere/@gridPoints',
                                 '/fleurInput/atomGroups/atomGroup/mtSphere/@gridPoints'],
                  'gw': '/fleurInput/calculationSetup/expertModes/@gw',
                  'idsprs': '/fleurInput/xcFunctional/xcParams/@idsprs',
                  'idsprs0': '/fleurInput/xcFunctional/ggaPrinting/@idsprs0',
                  'idsprsi': '/fleurInput/xcFunctional/ggaPrinting/@idsprsi',
                  'idsprsl': '/fleurInput/xcFunctional/ggaPrinting/@idsprsl',
                  'idsprsv': '/fleurInput/xcFunctional/ggaPrinting/@idsprsv',
                  'iggachk': '/fleurInput/xcFunctional/ggaPrinting/@iggachk',
                  'igrd': '/fleurInput/xcFunctional/xcParams/@igrd',
                  'imix': '/fleurInput/calculationSetup/scfLoop/@imix',
                  'init_mom': ['/fleurInput/atomSpecies/species/ldaHIA/exc/@init_mom',
                               '/fleurInput/atomGroups/atomGroup/ldaHIA/exc/@init_mom'],
                  'init_occ': ['/fleurInput/atomSpecies/species/ldaHIA/@init_occ',
                               '/fleurInput/atomGroups/atomGroup/ldaHIA/@init_occ'],
                  'intFullRadial': '/fleurInput/calculationSetup/greensFunction/@intFullRadial',
                  'integ': '/fleurInput/output/vacuumDOS/@integ',
                  'invs1': '/fleurInput/calculationSetup/oneDParams/@invs1',
                  'iplot': '/fleurInput/output/plotting/@iplot',
                  'isec1': '/fleurInput/calculationSetup/expertModes/@isec1',
                  'itmax': ['/fleurInput/calculationSetup/scfLoop/@itmax',
                            '/fleurInput/calculationSetup/ldaHIA/@itmax'],
                  'jDOS': ['/fleurInput/atomGroups/atomGroup/relPos/@jDOS',
                           '/fleurInput/atomGroups/atomGroup/absPos/@jDOS',
                           '/fleurInput/atomGroups/atomGroup/filmPos/@jDOS'],
                  'jspins': '/fleurInput/calculationSetup/magnetism/@jspins',
                  'kcrel': '/fleurInput/calculationSetup/coreElectrons/@kcrel',
                  'key': ['/fleurInput/atomSpecies/species/ldaHIA/addArg/@key',
                          '/fleurInput/atomGroups/atomGroup/ldaHIA/addArg/@key'],
                  'kkintgrCutoff': ['/fleurInput/atomSpecies/species/ldaHIA/@kkintgrCutoff',
                                    '/fleurInput/atomGroups/atomGroup/ldaHIA/@kkintgrCutoff',
                                    '/fleurInput/atomSpecies/species/greensfCalculation/@kkintgrCutoff',
                                    '/fleurInput/atomGroups/atomGroup/greensfCalculation/@kkintgrCutoff',
                                    '/fleurInput/atomSpecies/species/torgueCalculation/@kkintgrCutoff',
                                    '/fleurInput/atomGroups/atomGroup/torgueCalculation/@kkintgrCutoff'],
                  'l': ['/fleurInput/atomSpecies/species/ldaU/@l',
                        '/fleurInput/atomGroups/atomGroup/ldaU/@l',
                        '/fleurInput/atomSpecies/species/ldaHIA/@l',
                        '/fleurInput/atomGroups/atomGroup/ldaHIA/@l',
                        '/fleurInput/atomSpecies/species/ldaHIA/exc/@l',
                        '/fleurInput/atomGroups/atomGroup/ldaHIA/exc/@l',
                        '/fleurInput/atomSpecies/species/lo/@l',
                        '/fleurInput/atomGroups/atomGroup/lo/@l'],
                  'l_J': '/fleurInput/calculationSetup/magnetism/@l_J',
                  'l_RelaxAlpha': '/fleurInput/calculationSetup/nocoParams/@l_RelaxAlpha',
                  'l_RelaxBeta': '/fleurInput/calculationSetup/nocoParams/@l_RelaxBeta',
                  'l_RelaxMT': '/fleurInput/calculationSetup/nocoParams/@l_RelaxMT',
                  'l_adjEnpara': '/fleurInput/calculationSetup/ldaU/@l_adjEnpara',
                  'l_amf': ['/fleurInput/atomSpecies/species/ldaU/@l_amf',
                            '/fleurInput/atomGroups/atomGroup/ldaU/@l_amf',
                            '/fleurInput/atomSpecies/species/ldaHIA/@l_amf',
                            '/fleurInput/atomGroups/atomGroup/ldaHIA/@l_amf'],
                  'l_bloechl': '/fleurInput/calculationSetup/bzIntegration/@l_bloechl',
                  'l_constr': '/fleurInput/calculationSetup/nocoParams/@l_constr',
                  'l_correctEtot': '/fleurInput/calculationSetup/ldaHIA/@l_correctEtot',
                  'l_disp': '/fleurInput/calculationSetup/nocoParams/@l_disp',
                  'l_f': '/fleurInput/calculationSetup/geometryOptimization/@l_f',
                  'l_fermi': '/fleurInput/calculationSetup/greensFunction/contourDOS/@l_fermi',
                  'l_linMix': '/fleurInput/calculationSetup/ldaU/@l_linMix',
                  'l_magn': ['/fleurInput/atomSpecies/species/nocoParams/@l_magn',
                             '/fleurInput/atomGroups/atomGroup/nocoParams/@l_magn'],
                  'l_mperp': ['/fleurInput/calculationSetup/nocoParams/@l_mperp',
                              '/fleurInput/calculationSetup/greensFunction/@l_mperp'],
                  'l_mtNocoPot': '/fleurInput/calculationSetup/nocoParams/@l_mtNocoPot',
                  'l_noco': '/fleurInput/calculationSetup/magnetism/@l_noco',
                  'l_nonsphDC': '/fleurInput/calculationSetup/ldaHIA/@l_nonsphDC',
                  'l_onlyMtStDen': '/fleurInput/calculationSetup/magnetism/@l_onlyMtStDen',
                  'l_rdmft': '/fleurInput/calculationSetup/rdmft/@l_rdmft',
                  'l_relax': ['/fleurInput/atomSpecies/species/nocoParams/@l_relax',
                              '/fleurInput/atomGroups/atomGroup/nocoParams/@l_relax'],
                  'l_resolvent': '/fleurInput/calculationSetup/greensFunction/@l_resolvent',
                  'l_scaleMag': '/fleurInput/calculationSetup/nocoParams/@l_scaleMag',
                  'l_soc': '/fleurInput/calculationSetup/soc/@l_soc',
                  'l_sourceFree': '/fleurInput/calculationSetup/nocoParams/@l_sourceFree',
                  'l_sphavg': ['/fleurInput/atomSpecies/species/greensfCalculation/@l_sphavg',
                               '/fleurInput/atomGroups/atomGroup/greensfCalculation/@l_sphavg'],
                  'l_ss': '/fleurInput/calculationSetup/nocoParams/@l_ss',
                  'label': ['/fleurInput/atomGroups/atomGroup/relPos/@label',
                            '/fleurInput/atomGroups/atomGroup/absPos/@label',
                            '/fleurInput/atomGroups/atomGroup/filmPos/@label',
                            '/fleurInput/atomSpecies/species/ldaHIA/@label',
                            '/fleurInput/atomGroups/atomGroup/ldaHIA/@label',
                            '/fleurInput/atomSpecies/species/greensfCalculation/@label',
                            '/fleurInput/atomGroups/atomGroup/greensfCalculation/@label',
                            '/fleurInput/atomSpecies/species/torgueCalculation/@label',
                            '/fleurInput/atomGroups/atomGroup/torgueCalculation/@label',
                            '/fleurInput/calculationSetup/greensFunction/contourRectangle/@label',
                            '/fleurInput/calculationSetup/greensFunction/contourSemicircle/@label',
                            '/fleurInput/calculationSetup/greensFunction/contourDOS/@label',
                            '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/kPoint/@label'],
                  'lcutm': '/fleurInput/atomSpecies/species/prodBasis/@lcutm',
                  'lcutwf': '/fleurInput/atomSpecies/species/prodBasis/@lcutwf',
                  'lda': '/fleurInput/atomSpecies/species/special/@lda',
                  'lexp': '/fleurInput/calculationSetup/prodBasis/@lexp',
                  'lflip': '/fleurInput/calculationSetup/magnetism/@lflip',
                  'listName': '/fleurInput/calculationSetup/bzIntegration/kPointListSelection/@listName',
                  'lmax': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lmax',
                           '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lmax',
                           '/fleurInput/output/coreSpectrum/@lmax'],
                  'lmaxAPW': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lmaxAPW',
                              '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lmaxAPW'],
                  'lnonsphr': ['/fleurInput/atomSpecies/species/atomicCutoffs/@lnonsphr',
                               '/fleurInput/atomGroups/atomGroup/atomicCutoffs/@lnonsphr'],
                  'locx1': '/fleurInput/output/vacuumDOS/@locx1',
                  'locx2': '/fleurInput/output/vacuumDOS/@locx2',
                  'locy1': '/fleurInput/output/vacuumDOS/@locy1',
                  'locy2': '/fleurInput/output/vacuumDOS/@locy2',
                  'logIncrement': ['/fleurInput/atomSpecies/species/mtSphere/@logIncrement',
                                   '/fleurInput/atomGroups/atomGroup/mtSphere/@logIncrement'],
                  'lpr': '/fleurInput/calculationSetup/expertModes/@lpr',
                  'lwb': '/fleurInput/xcFunctional/xcParams/@lwb',
                  'm_cyl': '/fleurInput/calculationSetup/oneDParams/@m_cyl',
                  'magField': '/fleurInput/atomGroups/atomGroup/@magField',
                  'magMom': '/fleurInput/atomSpecies/species/@magMom',
                  'mag_scale': '/fleurInput/calculationSetup/nocoParams/@mag_scale',
                  'maxEigenval': '/fleurInput/output/chargeDensitySlicing/@maxEigenval',
                  'maxEnergy': '/fleurInput/output/bandDOS/@maxEnergy',
                  'maxIterBroyd': '/fleurInput/calculationSetup/scfLoop/@maxIterBroyd',
                  'maxSpinDown': '/fleurInput/output/wannier/bandSelection/@maxSpinDown',
                  'maxSpinUp': '/fleurInput/output/wannier/bandSelection/@maxSpinUp',
                  'maxTimeToStartIter': '/fleurInput/calculationSetup/scfLoop/@maxTimeToStartIter',
                  'mcd': '/fleurInput/output/magneticCircularDichroism/@mcd',
                  'minCalcDistance': '/fleurInput/calculationSetup/greensFunction/@minCalcDistance',
                  'minDistance': '/fleurInput/calculationSetup/scfLoop/@minDistance',
                  'minEigenval': '/fleurInput/output/chargeDensitySlicing/@minEigenval',
                  'minEnergy': '/fleurInput/output/bandDOS/@minEnergy',
                  'minSpinDown': '/fleurInput/output/wannier/bandSelection/@minSpinDown',
                  'minSpinUp': '/fleurInput/output/wannier/bandSelection/@minSpinUp',
                  'minmatDistance': '/fleurInput/calculationSetup/ldaHIA/@minmatDistance',
                  'minoccDistance': '/fleurInput/calculationSetup/ldaHIA/@minoccDistance',
                  'mixParam': '/fleurInput/calculationSetup/ldaU/@mixParam',
                  'mix_RelaxWeightOffD': '/fleurInput/calculationSetup/nocoParams/@mix_RelaxWeightOffD',
                  'mix_b': '/fleurInput/calculationSetup/nocoParams/@mix_b',
                  'mode': '/fleurInput/calculationSetup/bzIntegration/@mode',
                  'ms': '/fleurInput/output/wannier/@ms',
                  'n': ['/fleurInput/atomSpecies/species/lo/@n',
                        '/fleurInput/atomGroups/atomGroup/lo/@n',
                        '/fleurInput/calculationSetup/greensFunction/contourSemicircle/@n',
                        '/fleurInput/calculationSetup/greensFunction/contourDOS/@n'],
                  'n1': '/fleurInput/calculationSetup/greensFunction/contourRectangle/@n1',
                  'n2': '/fleurInput/calculationSetup/greensFunction/contourRectangle/@n2',
                  'n3': '/fleurInput/calculationSetup/greensFunction/contourRectangle/@n3',
                  'n_occpm': '/fleurInput/calculationSetup/ldaHIA/@n_occpm',
                  'name': ['/fleurInput/constants/constant/@name',
                           '/fleurInput/xcFunctional/@name',
                           '/fleurInput/atomSpecies/species/@name',
                           '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/@name'],
                  'ndvgrd': '/fleurInput/xcFunctional/xcParams/@ndvgrd',
                  'ne': '/fleurInput/calculationSetup/greensFunction/realAxis/@ne',
                  'nmatsub': '/fleurInput/calculationSetup/greensFunction/contourRectangle/@nmatsub',
                  'nnne': '/fleurInput/output/chargeDensitySlicing/@nnne',
                  'nqphi': '/fleurInput/output/coreSpectrum/@nqphi',
                  'nqr': '/fleurInput/output/coreSpectrum/@nqr',
                  'nsh': '/fleurInput/calculationSetup/nocoParams/@nsh',
                  'nshells': ['/fleurInput/atomSpecies/species/greensfCalculation/@nshells',
                              '/fleurInput/atomGroups/atomGroup/greensfCalculation/@nshells'],
                  'nstars': '/fleurInput/output/vacuumDOS/@nstars',
                  'nstm': '/fleurInput/output/vacuumDOS/@nstm',
                  'ntet': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/tetraeder/@ntet',
                  'ntria': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/triangles/@ntria',
                  'numPoints': '/fleurInput/output/coreSpectrum/@numPoints',
                  'numbands': '/fleurInput/calculationSetup/cutoffs/@numbands',
                  'numberPoints': '/fleurInput/output/bandDOS/@numberPoints',
                  'numkpt': '/fleurInput/output/chargeDensitySlicing/@numkpt',
                  'nx': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/@nx',
                  'ny': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/@ny',
                  'nz': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/@nz',
                  'occEps': '/fleurInput/calculationSetup/rdmft/@occEps',
                  'off': '/fleurInput/calculationSetup/soc/@off',
                  'onlyMT': '/fleurInput/output/plotting/plot/@onlyMT',
                  'orbcomp': ['/fleurInput/atomGroups/atomGroup/relPos/@orbcomp',
                              '/fleurInput/atomGroups/atomGroup/absPos/@orbcomp',
                              '/fleurInput/atomGroups/atomGroup/filmPos/@orbcomp'],
                  'outputSphavg': '/fleurInput/calculationSetup/greensFunction/@outputSphavg',
                  'p': ['/fleurInput/atomSpecies/species/greensfCalculation/diagElements/@p',
                        '/fleurInput/atomGroups/atomGroup/greensfCalculation/diagElements/@p',
                        '/fleurInput/atomSpecies/species/energyParameters/@p',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@p'],
                  'pallst': '/fleurInput/output/chargeDensitySlicing/@pallst',
                  'phi': ['/fleurInput/atomSpecies/species/ldaU/@phi',
                          '/fleurInput/atomGroups/atomGroup/ldaU/@phi',
                          '/fleurInput/atomSpecies/species/ldaHIA/@phi',
                          '/fleurInput/atomGroups/atomGroup/ldaHIA/@phi',
                          '/fleurInput/calculationSetup/soc/@phi',
                          '/fleurInput/forceTheorem/MAE/@phi',
                          '/fleurInput/forceTheorem/DMI/@phi'],
                  'plot_charge': '/fleurInput/calculationSetup/fields/@plot_charge',
                  'plot_rho': '/fleurInput/calculationSetup/fields/@plot_rho',
                  'polar': '/fleurInput/output/plotting/@polar',
                  'pot8': '/fleurInput/calculationSetup/expertModes/@pot8',
                  'potential': '/fleurInput/atomGroups/atomGroup/cFCoeffs/@potential',
                  'precondParam': '/fleurInput/calculationSetup/scfLoop/@precondParam',
                  'qfix': '/fleurInput/calculationSetup/geometryOptimization/@qfix',
                  'qx': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qx',
                  'qy': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qy',
                  'qz': '/fleurInput/calculationSetup/spinSpiralQPointMesh/@qz',
                  'radius': ['/fleurInput/atomSpecies/species/mtSphere/@radius',
                             '/fleurInput/atomGroups/atomGroup/mtSphere/@radius'],
                  'relativisticCorrections': '/fleurInput/xcFunctional/@relativisticCorrections',
                  'relaxXYZ': ['/fleurInput/atomSpecies/species/force/@relaxXYZ',
                               '/fleurInput/atomGroups/atomGroup/force/@relaxXYZ'],
                  'remove4f': '/fleurInput/atomGroups/atomGroup/cFCoeffs/@remove4f',
                  'rot': '/fleurInput/calculationSetup/oneDParams/@rot',
                  's': ['/fleurInput/atomSpecies/species/greensfCalculation/diagElements/@s',
                        '/fleurInput/atomGroups/atomGroup/greensfCalculation/diagElements/@s',
                        '/fleurInput/atomSpecies/species/energyParameters/@s',
                        '/fleurInput/atomGroups/atomGroup/energyParameters/@s'],
                  'scale': ['/fleurInput/cell/bulkLattice/@scale',
                            '/fleurInput/cell/filmLattice/@scale',
                            '/fleurInput/cell/bulkLattice/a1/@scale',
                            '/fleurInput/cell/filmLattice/a1/@scale',
                            '/fleurInput/cell/bulkLattice/a2/@scale',
                            '/fleurInput/cell/filmLattice/a2/@scale',
                            '/fleurInput/cell/bulkLattice/c/@scale'],
                  'secvar': '/fleurInput/calculationSetup/expertModes/@secvar',
                  'select': '/fleurInput/atomSpecies/species/prodBasis/@select',
                  'sgwf': '/fleurInput/output/wannier/@sgwf',
                  'sig_b_1': '/fleurInput/calculationSetup/fields/@sig_b_1',
                  'sig_b_2': '/fleurInput/calculationSetup/fields/@sig_b_2',
                  'sigma': ['/fleurInput/calculationSetup/greensFunction/contourRectangle/@sigma',
                            '/fleurInput/calculationSetup/greensFunction/contourDOS/@sigma',
                            '/fleurInput/output/bandDOS/@sigma'],
                  'slice': '/fleurInput/output/@slice',
                  'soc66': '/fleurInput/calculationSetup/soc/@soc66',
                  'socgwf': '/fleurInput/output/wannier/@socgwf',
                  'socscale': '/fleurInput/atomSpecies/species/special/@socscale',
                  'spav': '/fleurInput/calculationSetup/soc/@spav',
                  'species': '/fleurInput/atomGroups/atomGroup/@species',
                  'spinDown': ['/fleurInput/cell/filmLattice/vacuumEnergyParameters/@spinDown',
                               '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@spinDown'],
                  'spinUp': ['/fleurInput/cell/filmLattice/vacuumEnergyParameters/@spinUp',
                             '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@spinUp'],
                  'spinf': ['/fleurInput/calculationSetup/scfLoop/@spinf',
                            '/fleurInput/calculationSetup/ldaU/@spinf'],
                  'sso_opt': '/fleurInput/calculationSetup/nocoParams/@sso_opt',
                  'star': '/fleurInput/output/vacuumDOS/@star',
                  'state': '/fleurInput/atomSpecies/species/electronConfig/stateOccupation/@state',
                  'statesAbove': '/fleurInput/calculationSetup/rdmft/@statesAbove',
                  'statesBelow': '/fleurInput/calculationSetup/rdmft/@statesBelow',
                  'supercellX': '/fleurInput/output/unfoldingBand/@supercellX',
                  'supercellY': '/fleurInput/output/unfoldingBand/@supercellY',
                  'supercellZ': '/fleurInput/output/unfoldingBand/@supercellZ',
                  'swsp': '/fleurInput/calculationSetup/magnetism/@swsp',
                  'theta': ['/fleurInput/atomSpecies/species/ldaU/@theta',
                            '/fleurInput/atomGroups/atomGroup/ldaU/@theta',
                            '/fleurInput/atomSpecies/species/ldaHIA/@theta',
                            '/fleurInput/atomGroups/atomGroup/ldaHIA/@theta',
                            '/fleurInput/calculationSetup/soc/@theta',
                            '/fleurInput/forceTheorem/MAE/@theta',
                            '/fleurInput/forceTheorem/DMI/@theta'],
                  'thetaJ': '/fleurInput/calculationSetup/nocoParams/@thetaJ',
                  'thetaj': '/fleurInput/forceTheorem/Jij/@thetaj',
                  'tolerance': '/fleurInput/calculationSetup/prodBasis/@tolerance',
                  'tworkf': '/fleurInput/output/vacuumDOS/@tworkf',
                  'type': ['/fleurInput/atomSpecies/species/lo/@type',
                           '/fleurInput/atomGroups/atomGroup/lo/@type',
                           '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/@type'],
                  'typeMT': '/fleurInput/output/plotting/plot/@typeMT',
                  'unfoldBand': '/fleurInput/output/unfoldingBand/@unfoldBand',
                  'vM': '/fleurInput/calculationSetup/oneDParams/@vM',
                  'vacdos': '/fleurInput/output/vacuumDOS/@vacdos',
                  'vacuum': '/fleurInput/cell/filmLattice/vacuumEnergyParameters/@vacuum',
                  'valenceElectrons': '/fleurInput/calculationSetup/bzIntegration/@valenceElectrons',
                  'value': ['/fleurInput/constants/constant/@value',
                            '/fleurInput/atomSpecies/species/ldaHIA/addArg/@value',
                            '/fleurInput/atomGroups/atomGroup/ldaHIA/addArg/@value'],
                  'vcaAddCharge': '/fleurInput/atomGroups/atomGroup/@vcaAddCharge',
                  'vca_charge': '/fleurInput/atomSpecies/species/special/@vca_charge',
                  'vchk': '/fleurInput/output/checks/@vchk',
                  'vec1': '/fleurInput/output/plotting/plot/@vec1',
                  'vec2': '/fleurInput/output/plotting/plot/@vec2',
                  'vec3': '/fleurInput/output/plotting/plot/@vec3',
                  'vecField': '/fleurInput/output/plotting/plot/@vecField',
                  'verbose': '/fleurInput/output/coreSpectrum/@verbose',
                  'vol': ['/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/tetraeder/tet/@vol',
                          '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/triangles/tria/@vol'],
                  'wannier': ['/fleurInput/atomGroups/atomGroup/relPos/@wannier',
                              '/fleurInput/atomGroups/atomGroup/absPos/@wannier',
                              '/fleurInput/atomGroups/atomGroup/filmPos/@wannier',
                              '/fleurInput/output/@wannier'],
                  'warp_factor': '/fleurInput/calculationSetup/expertModes/@warp_factor',
                  'weight': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/kPoint/@weight',
                  'zero': '/fleurInput/output/plotting/plot/@zero',
                  'zrfs1': '/fleurInput/calculationSetup/oneDParams/@zrfs1',
                  'zsigma': '/fleurInput/calculationSetup/fields/@zsigma'},
 'attrib_types': {'Gmax': 'string',
                  'GmaxXC': 'string',
                  'I_initial': 'float',
                  'J': 'string',
                  'Kmax': 'string',
                  'M': 'string',
                  'MM': 'int',
                  'TwoD': 'switch',
                  'U': 'string',
                  'all_atoms': 'switch',
                  'alpha': ['float', 'string'],
                  'alpha_Ex': 'float',
                  'analytical_cont': 'switch',
                  'atomList': 'switch',
                  'atomType': 'int',
                  'atomicNumber': 'int',
                  'autocomp': 'switch',
                  'b_cons_x': 'string',
                  'b_cons_y': 'string',
                  'b_field': 'string',
                  'b_field_mt': 'string',
                  'band': 'switch',
                  'banddos': 'switch',
                  'bands': 'int',
                  'beta': ['float', 'string'],
                  'beta_Ex': 'float',
                  'bmt': 'switch',
                  'bsComf': 'switch',
                  'calculate': 'switch',
                  'cartesian': 'switch',
                  'cdinf': 'switch',
                  'chargeDensity': 'switch',
                  'chi': 'int',
                  'chng': 'float',
                  'coreSpec': 'switch',
                  'coretail_lmax': 'int',
                  'correlation': ['int', 'string'],
                  'count': 'int',
                  'ctail': 'switch',
                  'd': ['switch', 'int'],
                  'd1': 'switch',
                  'dTilda': 'string',
                  'dVac': 'string',
                  'dftspinpol': 'switch',
                  'dirichlet': 'switch',
                  'disp': 'switch',
                  'dos': 'switch',
                  'eDeriv': 'int',
                  'eKin': 'float',
                  'eMax': 'float',
                  'eMin': 'float',
                  'eV': 'switch',
                  'eb': 'float',
                  'edgeType': 'string',
                  'eig66': 'switch',
                  'element': 'string',
                  'ellow': ['float', 'string'],
                  'elup': ['float', 'string'],
                  'energy': 'string',
                  'energyLo': 'float',
                  'energyUp': 'float',
                  'eonly': 'switch',
                  'epsdisp': 'string',
                  'epsforce': 'string',
                  'et': 'float',
                  'etot_correlation': ['int', 'string'],
                  'etot_exchange': ['int', 'string'],
                  'ewaldlambda': 'int',
                  'exchange': ['int', 'string'],
                  'f': ['switch', 'int'],
                  'fermiSmearingEnergy': 'string',
                  'fermiSmearingTemp': 'string',
                  'file': 'string',
                  'fixed_moment': 'string',
                  'fleurInputVersion': 'string',
                  'flipSpinPhi': 'string',
                  'flipSpinScale': 'switch',
                  'flipSpinTheta': 'string',
                  'force_converged': 'string',
                  'forcealpha': 'string',
                  'forcemix': 'string',
                  'form66': 'switch',
                  'format': 'int',
                  'frcor': 'switch',
                  'fullMatch': 'switch',
                  'functional': 'string',
                  'gcutm': 'float',
                  'grid': 'string',
                  'gridPoints': 'int',
                  'gw': 'int',
                  'idsprs': 'int',
                  'idsprs0': 'int',
                  'idsprsi': 'int',
                  'idsprsl': 'int',
                  'idsprsv': 'float',
                  'iggachk': 'int',
                  'igrd': 'int',
                  'imix': 'string',
                  'init_mom': ['float', 'string'],
                  'init_occ': ['float', 'string'],
                  'intFullRadial': 'switch',
                  'integ': 'switch',
                  'invs1': 'switch',
                  'iplot': 'int',
                  'isec1': 'int',
                  'itmax': 'int',
                  'jDOS': 'switch',
                  'jspins': 'int',
                  'kcrel': 'int',
                  'key': 'string',
                  'kkintgrCutoff': ['float', 'string'],
                  'l': 'int',
                  'l_J': 'switch',
                  'l_RelaxAlpha': 'switch',
                  'l_RelaxBeta': 'switch',
                  'l_RelaxMT': 'switch',
                  'l_adjEnpara': 'switch',
                  'l_amf': 'switch',
                  'l_bloechl': 'switch',
                  'l_constr': 'switch',
                  'l_correctEtot': 'switch',
                  'l_disp': 'switch',
                  'l_f': 'switch',
                  'l_fermi': 'switch',
                  'l_linMix': 'switch',
                  'l_magn': 'switch',
                  'l_mperp': 'switch',
                  'l_mtNocoPot': 'switch',
                  'l_noco': 'switch',
                  'l_nonsphDC': 'switch',
                  'l_onlyMtStDen': 'switch',
                  'l_rdmft': 'switch',
                  'l_relax': 'switch',
                  'l_resolvent': 'switch',
                  'l_scaleMag': 'switch',
                  'l_soc': 'switch',
                  'l_sourceFree': 'switch',
                  'l_sphavg': 'switch',
                  'l_ss': 'switch',
                  'label': 'string',
                  'lcutm': 'int',
                  'lcutwf': 'int',
                  'lda': 'switch',
                  'lexp': 'int',
                  'lflip': 'switch',
                  'listName': 'string',
                  'lmax': 'int',
                  'lmaxAPW': 'int',
                  'lnonsphr': 'int',
                  'locx1': 'string',
                  'locx2': 'string',
                  'locy1': 'string',
                  'locy2': 'string',
                  'logIncrement': 'string',
                  'lpr': 'int',
                  'lwb': 'switch',
                  'm_cyl': 'int',
                  'magField': 'float',
                  'magMom': 'string',
                  'mag_scale': 'string',
                  'maxEigenval': 'string',
                  'maxEnergy': 'string',
                  'maxIterBroyd': 'int',
                  'maxSpinDown': 'int',
                  'maxSpinUp': 'int',
                  'maxTimeToStartIter': 'string',
                  'mcd': 'switch',
                  'minCalcDistance': 'float',
                  'minDistance': 'string',
                  'minEigenval': 'string',
                  'minEnergy': 'string',
                  'minSpinDown': 'int',
                  'minSpinUp': 'int',
                  'minmatDistance': 'float',
                  'minoccDistance': 'float',
                  'mixParam': 'float',
                  'mix_RelaxWeightOffD': 'string',
                  'mix_b': 'string',
                  'mode': 'string',
                  'ms': 'switch',
                  'n': 'int',
                  'n1': 'int',
                  'n2': 'int',
                  'n3': 'int',
                  'n_occpm': 'int',
                  'name': 'string',
                  'ndvgrd': 'int',
                  'ne': 'int',
                  'nmatsub': 'int',
                  'nnne': 'int',
                  'nqphi': 'int',
                  'nqr': 'int',
                  'nsh': 'int',
                  'nshells': 'int',
                  'nstars': 'int',
                  'nstm': 'int',
                  'ntet': 'int',
                  'ntria': 'int',
                  'numPoints': 'int',
                  'numbands': ['int', 'string'],
                  'numberPoints': 'int',
                  'numkpt': 'int',
                  'nx': 'int',
                  'ny': 'int',
                  'nz': 'int',
                  'occEps': 'float',
                  'off': 'switch',
                  'onlyMT': 'switch',
                  'orbcomp': 'switch',
                  'outputSphavg': 'switch',
                  'p': ['switch', 'int'],
                  'pallst': 'switch',
                  'phi': 'string',
                  'plot_charge': 'switch',
                  'plot_rho': 'switch',
                  'polar': 'switch',
                  'pot8': 'switch',
                  'potential': 'switch',
                  'precondParam': 'string',
                  'purpose': 'string',
                  'qfix': 'int',
                  'qx': 'int',
                  'qy': 'int',
                  'qz': 'int',
                  'radius': 'string',
                  'relativisticCorrections': 'switch',
                  'relaxXYZ': 'string',
                  'remove4f': 'switch',
                  'rot': 'int',
                  's': ['switch', 'int'],
                  'scale': 'string',
                  'secvar': 'switch',
                  'select': 'string',
                  'sgwf': 'switch',
                  'sig_b_1': 'string',
                  'sig_b_2': 'string',
                  'sigma': ['float', 'string'],
                  'slice': 'switch',
                  'soc66': 'switch',
                  'socgwf': 'switch',
                  'socscale': 'float',
                  'spav': 'switch',
                  'species': 'string',
                  'spinDown': 'string',
                  'spinUp': 'string',
                  'spinf': ['float', 'string'],
                  'sso_opt': 'string',
                  'star': 'switch',
                  'state': 'string',
                  'statesAbove': 'int',
                  'statesBelow': 'int',
                  'supercellX': 'int',
                  'supercellY': 'int',
                  'supercellZ': 'int',
                  'swsp': 'switch',
                  'theta': 'string',
                  'thetaJ': 'string',
                  'thetaj': 'string',
                  'tolerance': 'float',
                  'tworkf': 'string',
                  'type': 'string',
                  'typeMT': 'int',
                  'unfoldBand': 'switch',
                  'vM': 'int',
                  'vacdos': 'switch',
                  'vacuum': 'int',
                  'valenceElectrons': 'string',
                  'value': 'string',
                  'vcaAddCharge': 'float',
                  'vca_charge': 'string',
                  'vchk': 'switch',
                  'vec1': 'string',
                  'vec2': 'string',
                  'vec3': 'string',
                  'vecField': 'switch',
                  'verbose': 'switch',
                  'vol': 'string',
                  'wannier': 'switch',
                  'warp_factor': 'string',
                  'weight': 'string',
                  'zero': 'string',
                  'zrfs1': 'switch',
                  'zsigma': 'string'},
 'basic_types': {'AtomPosType': {'base_types': ['string'], 'length': 3},
                 'BZIntegrationModeEnum': {'base_types': ['string'],
                                           'length': 1},
                 'CoreConfigEnum': {'base_types': ['string'], 'length': 1},
                 'CoreSpecEdgeEnum': {'base_types': ['string'], 'length': 1},
                 'CoreStateListType': {'base_types': ['string'],
                                       'length': 'unbounded'},
                 'DisplaceType': {'base_types': ['float'], 'length': 3},
                 'Double3DVecType': {'base_types': ['float'], 'length': 3},
                 'Double4DVecType': {'base_types': ['float'], 'length': 4},
                 'DoubleVecType': {'base_types': ['float'],
                                   'length': 'unbounded'},
                 'EParamSelectionEnum': {'base_types': ['string'], 'length': 1},
                 'ElectronStateEnum': {'base_types': ['string'], 'length': 1},
                 'FleurBool4DVecType': {'base_types': ['switch'], 'length': 4},
                 'FleurBoolVecType': {'base_types': ['switch'],
                                      'length': 'unbounded'},
                 'FleurVersionType': {'base_types': ['string'], 'length': 1},
                 'ForceMixEnum': {'base_types': ['string'], 'length': 1},
                 'Integer3DVecType': {'base_types': ['int'], 'length': 3},
                 'Integer4DVecType': {'base_types': ['int'], 'length': 4},
                 'IntegerVecType': {'base_types': ['int'],
                                    'length': 'unbounded'},
                 'KPointListPurposeEnum': {'base_types': ['string'],
                                           'length': 1},
                 'KPointType': {'base_types': ['string'], 'length': 3},
                 'LatticeParameterType': {'base_types': ['string'],
                                          'length': 1},
                 'ManualCutoffType': {'base_types': ['float', 'string'],
                                      'length': 1},
                 'ManualKKintgrCutoffType': {'base_types': ['float', 'string'],
                                             'length': 1},
                 'MixingEnum': {'base_types': ['string'], 'length': 1},
                 'NobleGasConfigEnum': {'base_types': ['string'], 'length': 1},
                 'NumBandsType': {'base_types': ['int', 'string'], 'length': 1},
                 'PositionType': {'base_types': ['float'], 'length': 3},
                 'RDMFTFunctionalEnum': {'base_types': ['string'], 'length': 1},
                 'SpecialPointType': {'base_types': ['string'], 'length': 3},
                 'SpinNumberType': {'base_types': ['int'], 'length': 1},
                 'String2DVecType': {'base_types': ['string'], 'length': 2},
                 'String3DVecType': {'base_types': ['string'], 'length': 3},
                 'StringVecType': {'base_types': ['string'],
                                   'length': 'unbounded'},
                 'TetType': {'base_types': ['int'], 'length': 4},
                 'TriaType': {'base_types': ['int'], 'length': 3},
                 'TripleFleurBool': {'base_types': ['string'], 'length': 1},
                 'ValenceStateListType': {'base_types': ['string'],
                                          'length': 'unbounded'},
                 'XCFunctionalEnum': {'base_types': ['string'], 'length': 1},
                 'ZeroToOneNumberType': {'base_types': ['float'], 'length': 1},
                 'kPointListTypeEnum': {'base_types': ['string'], 'length': 1}},
 'omitt_contained_tags': ['constants',
                          'atomSpecies',
                          'atomGroups',
                          'symmetryOperations',
                          'kPointLists',
                          'displacements',
                          'relaxation-history',
                          'spinSpiralDispersion',
                          'qVectors'],
 'settable_attribs': {'Gmax': '/fleurInput/calculationSetup/cutoffs',
                      'GmaxXC': '/fleurInput/calculationSetup/cutoffs',
                      'I_initial': '/fleurInput/output/coreSpectrum',
                      'Kmax': '/fleurInput/calculationSetup/cutoffs',
                      'MM': '/fleurInput/calculationSetup/oneDParams',
                      'all_atoms': '/fleurInput/output/bandDOS',
                      'alpha_Ex': '/fleurInput/output/coreSpectrum',
                      'analytical_cont': '/fleurInput/calculationSetup/greensFunction/contourDOS',
                      'atomList': '/fleurInput/output/wannier',
                      'atomType': '/fleurInput/output/coreSpectrum',
                      'autocomp': '/fleurInput/calculationSetup/fields',
                      'b_field': '/fleurInput/calculationSetup/fields',
                      'band': '/fleurInput/output',
                      'bands': '/fleurInput/calculationSetup/prodBasis',
                      'beta_Ex': '/fleurInput/output/coreSpectrum',
                      'bmt': '/fleurInput/output/specialOutput',
                      'bsComf': '/fleurInput/output/wannier',
                      'c': '/fleurInput/cell/bulkLattice/c',
                      'cdinf': '/fleurInput/output/checks',
                      'chi': '/fleurInput/calculationSetup/oneDParams',
                      'chng': '/fleurInput/xcFunctional/xcParams',
                      'comment': '/fleurInput/comment',
                      'coreSpec': '/fleurInput/output',
                      'coretail_lmax': '/fleurInput/calculationSetup/coreElectrons',
                      'ctail': '/fleurInput/calculationSetup/coreElectrons',
                      'd1': '/fleurInput/calculationSetup/oneDParams',
                      'dTilda': '/fleurInput/cell/filmLattice',
                      'dVac': '/fleurInput/cell/filmLattice',
                      'dftspinpol': '/fleurInput/calculationSetup/ldaHIA',
                      'dirichlet': '/fleurInput/calculationSetup/fields',
                      'disp': '/fleurInput/output/checks',
                      'dos': '/fleurInput/output',
                      'eKin': '/fleurInput/output/coreSpectrum',
                      'eMax': '/fleurInput/output/coreSpectrum',
                      'eMin': '/fleurInput/output/coreSpectrum',
                      'eV': '/fleurInput/calculationSetup/fields',
                      'edgeIndices': '/fleurInput/output/coreSpectrum/edgeIndices',
                      'edgeType': '/fleurInput/output/coreSpectrum',
                      'energyLo': '/fleurInput/output/magneticCircularDichroism',
                      'energyUp': '/fleurInput/output/magneticCircularDichroism',
                      'eonly': '/fleurInput/output/specialOutput',
                      'epsdisp': '/fleurInput/calculationSetup/geometryOptimization',
                      'epsforce': '/fleurInput/calculationSetup/geometryOptimization',
                      'ewaldlambda': '/fleurInput/calculationSetup/prodBasis',
                      'fermiSmearingEnergy': '/fleurInput/calculationSetup/bzIntegration',
                      'fermiSmearingTemp': '/fleurInput/calculationSetup/bzIntegration',
                      'fixed_moment': '/fleurInput/calculationSetup/magnetism',
                      'fleurInputVersion': '/fleurInput',
                      'force_converged': '/fleurInput/calculationSetup/geometryOptimization',
                      'forcealpha': '/fleurInput/calculationSetup/geometryOptimization',
                      'forcemix': '/fleurInput/calculationSetup/geometryOptimization',
                      'form66': '/fleurInput/output/specialOutput',
                      'format': '/fleurInput/output/plotting',
                      'frcor': '/fleurInput/calculationSetup/coreElectrons',
                      'fullMatch': '/fleurInput/calculationSetup/ldaHIA',
                      'functional': '/fleurInput/calculationSetup/rdmft',
                      'gcutm': '/fleurInput/calculationSetup/prodBasis',
                      'gw': '/fleurInput/calculationSetup/expertModes',
                      'idsprs': '/fleurInput/xcFunctional/xcParams',
                      'idsprs0': '/fleurInput/xcFunctional/ggaPrinting',
                      'idsprsi': '/fleurInput/xcFunctional/ggaPrinting',
                      'idsprsl': '/fleurInput/xcFunctional/ggaPrinting',
                      'idsprsv': '/fleurInput/xcFunctional/ggaPrinting',
                      'iggachk': '/fleurInput/xcFunctional/ggaPrinting',
                      'igrd': '/fleurInput/xcFunctional/xcParams',
                      'imix': '/fleurInput/calculationSetup/scfLoop',
                      'intFullRadial': '/fleurInput/calculationSetup/greensFunction',
                      'integ': '/fleurInput/output/vacuumDOS',
                      'invs1': '/fleurInput/calculationSetup/oneDParams',
                      'iplot': '/fleurInput/output/plotting',
                      'isec1': '/fleurInput/calculationSetup/expertModes',
                      'jobList': '/fleurInput/output/wannier/jobList',
                      'jspins': '/fleurInput/calculationSetup/magnetism',
                      'kcrel': '/fleurInput/calculationSetup/coreElectrons',
                      'l_J': '/fleurInput/calculationSetup/magnetism',
                      'l_RelaxAlpha': '/fleurInput/calculationSetup/nocoParams',
                      'l_RelaxBeta': '/fleurInput/calculationSetup/nocoParams',
                      'l_RelaxMT': '/fleurInput/calculationSetup/nocoParams',
                      'l_adjEnpara': '/fleurInput/calculationSetup/ldaU',
                      'l_bloechl': '/fleurInput/calculationSetup/bzIntegration',
                      'l_constr': '/fleurInput/calculationSetup/nocoParams',
                      'l_correctEtot': '/fleurInput/calculationSetup/ldaHIA',
                      'l_disp': '/fleurInput/calculationSetup/nocoParams',
                      'l_f': '/fleurInput/calculationSetup/geometryOptimization',
                      'l_fermi': '/fleurInput/calculationSetup/greensFunction/contourDOS',
                      'l_linMix': '/fleurInput/calculationSetup/ldaU',
                      'l_mtNocoPot': '/fleurInput/calculationSetup/nocoParams',
                      'l_noco': '/fleurInput/calculationSetup/magnetism',
                      'l_nonsphDC': '/fleurInput/calculationSetup/ldaHIA',
                      'l_onlyMtStDen': '/fleurInput/calculationSetup/magnetism',
                      'l_rdmft': '/fleurInput/calculationSetup/rdmft',
                      'l_resolvent': '/fleurInput/calculationSetup/greensFunction',
                      'l_scaleMag': '/fleurInput/calculationSetup/nocoParams',
                      'l_soc': '/fleurInput/calculationSetup/soc',
                      'l_sourceFree': '/fleurInput/calculationSetup/nocoParams',
                      'l_ss': '/fleurInput/calculationSetup/nocoParams',
                      'lexp': '/fleurInput/calculationSetup/prodBasis',
                      'lflip': '/fleurInput/calculationSetup/magnetism',
                      'listName': '/fleurInput/calculationSetup/bzIntegration/kPointListSelection',
                      'locx1': '/fleurInput/output/vacuumDOS',
                      'locx2': '/fleurInput/output/vacuumDOS',
                      'locy1': '/fleurInput/output/vacuumDOS',
                      'locy2': '/fleurInput/output/vacuumDOS',
                      'lpr': '/fleurInput/calculationSetup/expertModes',
                      'lwb': '/fleurInput/xcFunctional/xcParams',
                      'm_cyl': '/fleurInput/calculationSetup/oneDParams',
                      'mag_scale': '/fleurInput/calculationSetup/nocoParams',
                      'maxEigenval': '/fleurInput/output/chargeDensitySlicing',
                      'maxEnergy': '/fleurInput/output/bandDOS',
                      'maxIterBroyd': '/fleurInput/calculationSetup/scfLoop',
                      'maxSpinDown': '/fleurInput/output/wannier/bandSelection',
                      'maxSpinUp': '/fleurInput/output/wannier/bandSelection',
                      'maxTimeToStartIter': '/fleurInput/calculationSetup/scfLoop',
                      'mcd': '/fleurInput/output/magneticCircularDichroism',
                      'minCalcDistance': '/fleurInput/calculationSetup/greensFunction',
                      'minDistance': '/fleurInput/calculationSetup/scfLoop',
                      'minEigenval': '/fleurInput/output/chargeDensitySlicing',
                      'minEnergy': '/fleurInput/output/bandDOS',
                      'minSpinDown': '/fleurInput/output/wannier/bandSelection',
                      'minSpinUp': '/fleurInput/output/wannier/bandSelection',
                      'minmatDistance': '/fleurInput/calculationSetup/ldaHIA',
                      'minoccDistance': '/fleurInput/calculationSetup/ldaHIA',
                      'mixParam': '/fleurInput/calculationSetup/ldaU',
                      'mix_RelaxWeightOffD': '/fleurInput/calculationSetup/nocoParams',
                      'mix_b': '/fleurInput/calculationSetup/nocoParams',
                      'mode': '/fleurInput/calculationSetup/bzIntegration',
                      'ms': '/fleurInput/output/wannier',
                      'n1': '/fleurInput/calculationSetup/greensFunction/contourRectangle',
                      'n2': '/fleurInput/calculationSetup/greensFunction/contourRectangle',
                      'n3': '/fleurInput/calculationSetup/greensFunction/contourRectangle',
                      'n_occpm': '/fleurInput/calculationSetup/ldaHIA',
                      'ndvgrd': '/fleurInput/xcFunctional/xcParams',
                      'ne': '/fleurInput/calculationSetup/greensFunction/realAxis',
                      'nmatsub': '/fleurInput/calculationSetup/greensFunction/contourRectangle',
                      'nnne': '/fleurInput/output/chargeDensitySlicing',
                      'nqphi': '/fleurInput/output/coreSpectrum',
                      'nqr': '/fleurInput/output/coreSpectrum',
                      'nsh': '/fleurInput/calculationSetup/nocoParams',
                      'nstars': '/fleurInput/output/vacuumDOS',
                      'nstm': '/fleurInput/output/vacuumDOS',
                      'numPoints': '/fleurInput/output/coreSpectrum',
                      'numbands': '/fleurInput/calculationSetup/cutoffs',
                      'numberPoints': '/fleurInput/output/bandDOS',
                      'numkpt': '/fleurInput/output/chargeDensitySlicing',
                      'occEps': '/fleurInput/calculationSetup/rdmft',
                      'off': '/fleurInput/calculationSetup/soc',
                      'outputSphavg': '/fleurInput/calculationSetup/greensFunction',
                      'pallst': '/fleurInput/output/chargeDensitySlicing',
                      'plot_charge': '/fleurInput/calculationSetup/fields',
                      'plot_rho': '/fleurInput/calculationSetup/fields',
                      'polar': '/fleurInput/output/plotting',
                      'pot8': '/fleurInput/calculationSetup/expertModes',
                      'precondParam': '/fleurInput/calculationSetup/scfLoop',
                      'qfix': '/fleurInput/calculationSetup/geometryOptimization',
                      'qsc': '/fleurInput/calculationSetup/nocoParams/qsc',
                      'qss': '/fleurInput/calculationSetup/nocoParams/qss',
                      'qx': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
                      'qy': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
                      'qz': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
                      'relativisticCorrections': '/fleurInput/xcFunctional',
                      'rot': '/fleurInput/calculationSetup/oneDParams',
                      'secvar': '/fleurInput/calculationSetup/expertModes',
                      'sgwf': '/fleurInput/output/wannier',
                      'sig_b_1': '/fleurInput/calculationSetup/fields',
                      'sig_b_2': '/fleurInput/calculationSetup/fields',
                      'slice': '/fleurInput/output',
                      'soc66': '/fleurInput/calculationSetup/soc',
                      'socgwf': '/fleurInput/output/wannier',
                      'spav': '/fleurInput/calculationSetup/soc',
                      'sso_opt': '/fleurInput/calculationSetup/nocoParams',
                      'star': '/fleurInput/output/vacuumDOS',
                      'statesAbove': '/fleurInput/calculationSetup/rdmft',
                      'statesBelow': '/fleurInput/calculationSetup/rdmft',
                      'supercellX': '/fleurInput/output/unfoldingBand',
                      'supercellY': '/fleurInput/output/unfoldingBand',
                      'supercellZ': '/fleurInput/output/unfoldingBand',
                      'swsp': '/fleurInput/calculationSetup/magnetism',
                      'thetaJ': '/fleurInput/calculationSetup/nocoParams',
                      'thetaj': '/fleurInput/forceTheorem/Jij',
                      'tolerance': '/fleurInput/calculationSetup/prodBasis',
                      'tworkf': '/fleurInput/output/vacuumDOS',
                      'unfoldBand': '/fleurInput/output/unfoldingBand',
                      'vM': '/fleurInput/calculationSetup/oneDParams',
                      'vacdos': '/fleurInput/output/vacuumDOS',
                      'valenceElectrons': '/fleurInput/calculationSetup/bzIntegration',
                      'vchk': '/fleurInput/output/checks',
                      'verbose': '/fleurInput/output/coreSpectrum',
                      'warp_factor': '/fleurInput/calculationSetup/expertModes',
                      'zrfs1': '/fleurInput/calculationSetup/oneDParams',
                      'zsigma': '/fleurInput/calculationSetup/fields'},
 'settable_contains_attribs': {'a1': ['/fleurInput/cell/bulkLattice/a1',
                                      '/fleurInput/cell/filmLattice/a1'],
                               'a2': ['/fleurInput/cell/bulkLattice/a2',
                                      '/fleurInput/cell/filmLattice/a2'],
                               'alpha': ['/fleurInput/calculationSetup/scfLoop',
                                         '/fleurInput/calculationSetup/greensFunction/contourSemicircle'],
                               'beta': ['/fleurInput/calculationSetup/ldaHIA'],
                               'correlation': ['/fleurInput/xcFunctional/LibXCID',
                                               '/fleurInput/xcFunctional/LibXCName'],
                               'eb': ['/fleurInput/calculationSetup/greensFunction/contourRectangle',
                                      '/fleurInput/calculationSetup/greensFunction/contourSemicircle',
                                      '/fleurInput/calculationSetup/greensFunction/contourDOS'],
                               'eig66': ['/fleurInput/calculationSetup/expertModes',
                                         '/fleurInput/output'],
                               'ellow': ['/fleurInput/calculationSetup/energyParameterLimits',
                                         '/fleurInput/calculationSetup/greensFunction/realAxis'],
                               'elup': ['/fleurInput/calculationSetup/energyParameterLimits',
                                        '/fleurInput/calculationSetup/greensFunction/realAxis'],
                               'et': ['/fleurInput/calculationSetup/greensFunction/contourSemicircle',
                                      '/fleurInput/calculationSetup/greensFunction/contourDOS'],
                               'etot_correlation': ['/fleurInput/xcFunctional/LibXCID',
                                                    '/fleurInput/xcFunctional/LibXCName'],
                               'etot_exchange': ['/fleurInput/xcFunctional/LibXCID',
                                                 '/fleurInput/xcFunctional/LibXCName'],
                               'exchange': ['/fleurInput/xcFunctional/LibXCID',
                                            '/fleurInput/xcFunctional/LibXCName'],
                               'itmax': ['/fleurInput/calculationSetup/scfLoop',
                                         '/fleurInput/calculationSetup/ldaHIA'],
                               'l_mperp': ['/fleurInput/calculationSetup/nocoParams',
                                           '/fleurInput/calculationSetup/greensFunction'],
                               'label': ['/fleurInput/calculationSetup/greensFunction/contourRectangle',
                                         '/fleurInput/calculationSetup/greensFunction/contourSemicircle',
                                         '/fleurInput/calculationSetup/greensFunction/contourDOS'],
                               'lmax': ['/fleurInput/output/coreSpectrum'],
                               'n': ['/fleurInput/calculationSetup/greensFunction/contourSemicircle',
                                     '/fleurInput/calculationSetup/greensFunction/contourDOS'],
                               'name': ['/fleurInput/xcFunctional'],
                               'phi': ['/fleurInput/calculationSetup/soc',
                                       '/fleurInput/forceTheorem/MAE',
                                       '/fleurInput/forceTheorem/DMI'],
                               'row-1': ['/fleurInput/cell/bulkLattice/row-1',
                                         '/fleurInput/cell/filmLattice/row-1',
                                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-1',
                                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-1'],
                               'row-2': ['/fleurInput/cell/bulkLattice/row-2',
                                         '/fleurInput/cell/filmLattice/row-2',
                                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-2',
                                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-2'],
                               'row-3': ['/fleurInput/cell/bulkLattice/bravaisMatrix/row-3',
                                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-3'],
                               'scale': ['/fleurInput/cell/bulkLattice',
                                         '/fleurInput/cell/filmLattice',
                                         '/fleurInput/cell/bulkLattice/a1',
                                         '/fleurInput/cell/filmLattice/a1',
                                         '/fleurInput/cell/bulkLattice/a2',
                                         '/fleurInput/cell/filmLattice/a2',
                                         '/fleurInput/cell/bulkLattice/c'],
                               'sigma': ['/fleurInput/calculationSetup/greensFunction/contourRectangle',
                                         '/fleurInput/calculationSetup/greensFunction/contourDOS',
                                         '/fleurInput/output/bandDOS'],
                               'spinf': ['/fleurInput/calculationSetup/scfLoop',
                                         '/fleurInput/calculationSetup/ldaU'],
                               'theta': ['/fleurInput/calculationSetup/soc',
                                         '/fleurInput/forceTheorem/MAE',
                                         '/fleurInput/forceTheorem/DMI'],
                               'wannier': ['/fleurInput/output']},
 'simple_elements': {'a1': {'length': 1, 'type': ['string']},
                     'a2': {'length': 1, 'type': ['string']},
                     'absPos': {'length': 3, 'type': ['string']},
                     'c': {'length': 1, 'type': ['string']},
                     'comment': {'length': 1, 'type': ['string']},
                     'coreConfig': {'length': 'unbounded', 'type': ['string']},
                     'd': {'length': 4, 'type': ['switch']},
                     'displace': {'length': 3, 'type': ['float']},
                     'edgeIndices': {'length': 'unbounded', 'type': ['int']},
                     'f': {'length': 4, 'type': ['switch']},
                     'filmPos': {'length': 3, 'type': ['string']},
                     'jobList': {'length': 'unbounded', 'type': ['string']},
                     'kPoint': {'length': 3, 'type': ['string']},
                     'layer': {'length': 1, 'type': ['string']},
                     'orbcomprot': {'length': 3, 'type': ['float']},
                     'p': {'length': 4, 'type': ['switch']},
                     'posforce': {'length': 1, 'type': ['string']},
                     'q': {'length': 1, 'type': ['string']},
                     'qsc': {'length': 3, 'type': ['float']},
                     'qss': {'length': 3, 'type': ['float']},
                     'relPos': {'length': 3, 'type': ['string']},
                     'row-1': [{'length': 2, 'type': ['string']},
                               {'length': 3, 'type': ['string']},
                               {'length': 4, 'type': ['float']}],
                     'row-2': [{'length': 2, 'type': ['string']},
                               {'length': 3, 'type': ['string']},
                               {'length': 4, 'type': ['float']}],
                     'row-3': [{'length': 3, 'type': ['string']},
                               {'length': 4, 'type': ['float']}],
                     's': {'length': 4, 'type': ['switch']},
                     'shape': {'length': 1, 'type': ['string']},
                     'tet': {'length': 4, 'type': ['int']},
                     'tria': {'length': 3, 'type': ['int']},
                     'valenceConfig': {'length': 'unbounded',
                                       'type': ['string']}},
 'tag_order': {'atomGroup': [['relPos', 'absPos', 'filmPos'],
                             'mtSphere',
                             'atomicCutoffs',
                             'energyParameters',
                             'force',
                             'nocoParams',
                             'ldaU',
                             'ldaHIA',
                             'greensfCalculation',
                             'torgueCalculation',
                             'lo',
                             'orbcomprot',
                             'cFCoeffs'],
               'atomGroups': 'atomGroup',
               'atomSpecies': 'species',
               'bravaisMatrix': ['row-1', 'row-2', 'row-3'],
               'bulkLattice': [['a1', 'a2', 'c'],
                               ['row-1', 'row-2', 'c'],
                               'bravaisMatrix'],
               'bzIntegration': ['kPointListSelection', 'kPointLists'],
               'cell': ['bulkLattice', 'filmLattice'],
               'constants': 'constant',
               'coreSpectrum': 'edgeIndices',
               'displacements': 'displace',
               'electronConfig': ['coreConfig',
                                  'valenceConfig',
                                  'stateOccupation'],
               'fields': 'shape',
               'filmLattice': [[['a1', 'a2'],
                                ['row-1', 'row-2'],
                                'bravaisMatrix'],
                               'vacuumEnergyParameters'],
               'greensFunction': ['realAxis',
                                  ['contourRectangle',
                                   'contourSemicircle',
                                   'contourDOS']],
               'kPointList': ['kPoint', 'tetraeder', 'triangles'],
               'kPointLists': 'kPointList',
               'ldaHIA': ['exc', 'addArg'],
               'matrixElements': ['s', 'p', 'd', 'f'],
               'nocoParams': ['qss', 'qsc'],
               'plotting': 'plot',
               'relaxation-history': 'step',
               'species': ['mtSphere',
                           'atomicCutoffs',
                           'electronConfig',
                           'energyParameters',
                           'prodBasis',
                           'special',
                           'force',
                           'nocoParams',
                           'ldaU',
                           'ldaHIA',
                           'greensfCalculation',
                           'torgueCalculation',
                           'lo'],
               'spinSpiralDispersion': 'q',
               'step': 'posforce',
               'symOp': ['row-1', 'row-2', 'row-3'],
               'symmetryOperations': 'symOp',
               'tetraeder': 'tet',
               'torgueCalculation': 'greensfElements',
               'triangles': 'tria',
               'vacuumDOS': 'layer',
               'xcFunctional': ['LibXCID',
                                'LibXCName',
                                'xcParams',
                                'ggaPrinting']},
 'tag_paths': {'DMI': '/fleurInput/forceTheorem/DMI',
               'Jij': '/fleurInput/forceTheorem/Jij',
               'LibXCID': '/fleurInput/xcFunctional/LibXCID',
               'LibXCName': '/fleurInput/xcFunctional/LibXCName',
               'MAE': '/fleurInput/forceTheorem/MAE',
               'a1': ['/fleurInput/cell/bulkLattice/a1',
                      '/fleurInput/cell/filmLattice/a1'],
               'a2': ['/fleurInput/cell/bulkLattice/a2',
                      '/fleurInput/cell/filmLattice/a2'],
               'absPos': '/fleurInput/atomGroups/atomGroup/absPos',
               'addArg': ['/fleurInput/atomSpecies/species/ldaHIA/addArg',
                          '/fleurInput/atomGroups/atomGroup/ldaHIA/addArg'],
               'atomGroup': '/fleurInput/atomGroups/atomGroup',
               'atomGroups': '/fleurInput/atomGroups',
               'atomSpecies': '/fleurInput/atomSpecies',
               'atomicCutoffs': ['/fleurInput/atomSpecies/species/atomicCutoffs',
                                 '/fleurInput/atomGroups/atomGroup/atomicCutoffs'],
               'bandDOS': '/fleurInput/output/bandDOS',
               'bandSelection': '/fleurInput/output/wannier/bandSelection',
               'bravaisMatrix': ['/fleurInput/cell/bulkLattice/bravaisMatrix',
                                 '/fleurInput/cell/filmLattice/bravaisMatrix'],
               'bulkLattice': '/fleurInput/cell/bulkLattice',
               'bzIntegration': '/fleurInput/calculationSetup/bzIntegration',
               'c': '/fleurInput/cell/bulkLattice/c',
               'cFCoeffs': '/fleurInput/atomGroups/atomGroup/cFCoeffs',
               'calculationSetup': '/fleurInput/calculationSetup',
               'cell': '/fleurInput/cell',
               'chargeDensitySlicing': '/fleurInput/output/chargeDensitySlicing',
               'checks': '/fleurInput/output/checks',
               'comment': '/fleurInput/comment',
               'constant': '/fleurInput/constants/constant',
               'constants': '/fleurInput/constants',
               'contourDOS': '/fleurInput/calculationSetup/greensFunction/contourDOS',
               'contourRectangle': '/fleurInput/calculationSetup/greensFunction/contourRectangle',
               'contourSemicircle': '/fleurInput/calculationSetup/greensFunction/contourSemicircle',
               'coreConfig': '/fleurInput/atomSpecies/species/electronConfig/coreConfig',
               'coreElectrons': '/fleurInput/calculationSetup/coreElectrons',
               'coreSpectrum': '/fleurInput/output/coreSpectrum',
               'cutoffs': '/fleurInput/calculationSetup/cutoffs',
               'd': ['/fleurInput/atomSpecies/species/greensfCalculation/matrixElements/d',
                     '/fleurInput/atomGroups/atomGroup/greensfCalculation/matrixElements/d',
                     '/fleurInput/atomSpecies/species/torgueCalculation/greensfElements/d',
                     '/fleurInput/atomGroups/atomGroup/torgueCalculation/greensfElements/d'],
               'diagElements': ['/fleurInput/atomSpecies/species/greensfCalculation/diagElements',
                                '/fleurInput/atomGroups/atomGroup/greensfCalculation/diagElements'],
               'displace': '/fleurInput/relaxation/displacements/displace',
               'displacements': '/fleurInput/relaxation/displacements',
               'edgeIndices': '/fleurInput/output/coreSpectrum/edgeIndices',
               'electronConfig': '/fleurInput/atomSpecies/species/electronConfig',
               'energyParameterLimits': '/fleurInput/calculationSetup/energyParameterLimits',
               'energyParameters': ['/fleurInput/atomSpecies/species/energyParameters',
                                    '/fleurInput/atomGroups/atomGroup/energyParameters'],
               'exc': ['/fleurInput/atomSpecies/species/ldaHIA/exc',
                       '/fleurInput/atomGroups/atomGroup/ldaHIA/exc'],
               'expertModes': '/fleurInput/calculationSetup/expertModes',
               'f': ['/fleurInput/atomSpecies/species/greensfCalculation/matrixElements/f',
                     '/fleurInput/atomGroups/atomGroup/greensfCalculation/matrixElements/f',
                     '/fleurInput/atomSpecies/species/torgueCalculation/greensfElements/f',
                     '/fleurInput/atomGroups/atomGroup/torgueCalculation/greensfElements/f'],
               'fields': '/fleurInput/calculationSetup/fields',
               'filmLattice': '/fleurInput/cell/filmLattice',
               'filmPos': '/fleurInput/atomGroups/atomGroup/filmPos',
               'fleurInput': '/fleurInput',
               'force': ['/fleurInput/atomSpecies/species/force',
                         '/fleurInput/atomGroups/atomGroup/force'],
               'forceTheorem': '/fleurInput/forceTheorem',
               'geometryOptimization': '/fleurInput/calculationSetup/geometryOptimization',
               'ggaPrinting': '/fleurInput/xcFunctional/ggaPrinting',
               'greensFunction': '/fleurInput/calculationSetup/greensFunction',
               'greensfCalculation': ['/fleurInput/atomSpecies/species/greensfCalculation',
                                      '/fleurInput/atomGroups/atomGroup/greensfCalculation'],
               'greensfElements': ['/fleurInput/atomSpecies/species/torgueCalculation/greensfElements',
                                   '/fleurInput/atomGroups/atomGroup/torgueCalculation/greensfElements'],
               'jobList': '/fleurInput/output/wannier/jobList',
               'kPoint': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/kPoint',
               'kPointList': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList',
               'kPointListSelection': '/fleurInput/calculationSetup/bzIntegration/kPointListSelection',
               'kPointLists': '/fleurInput/calculationSetup/bzIntegration/kPointLists',
               'layer': '/fleurInput/output/vacuumDOS/layer',
               'ldaHIA': ['/fleurInput/calculationSetup/ldaHIA',
                          '/fleurInput/atomSpecies/species/ldaHIA',
                          '/fleurInput/atomGroups/atomGroup/ldaHIA'],
               'ldaU': ['/fleurInput/calculationSetup/ldaU',
                        '/fleurInput/atomSpecies/species/ldaU',
                        '/fleurInput/atomGroups/atomGroup/ldaU'],
               'lo': ['/fleurInput/atomSpecies/species/lo',
                      '/fleurInput/atomGroups/atomGroup/lo'],
               'magneticCircularDichroism': '/fleurInput/output/magneticCircularDichroism',
               'magnetism': '/fleurInput/calculationSetup/magnetism',
               'matrixElements': ['/fleurInput/atomSpecies/species/greensfCalculation/matrixElements',
                                  '/fleurInput/atomGroups/atomGroup/greensfCalculation/matrixElements'],
               'mtSphere': ['/fleurInput/atomSpecies/species/mtSphere',
                            '/fleurInput/atomGroups/atomGroup/mtSphere'],
               'nocoParams': ['/fleurInput/calculationSetup/nocoParams',
                              '/fleurInput/atomSpecies/species/nocoParams',
                              '/fleurInput/atomGroups/atomGroup/nocoParams'],
               'oneDParams': '/fleurInput/calculationSetup/oneDParams',
               'orbcomprot': '/fleurInput/atomGroups/atomGroup/orbcomprot',
               'output': '/fleurInput/output',
               'p': ['/fleurInput/atomSpecies/species/greensfCalculation/matrixElements/p',
                     '/fleurInput/atomGroups/atomGroup/greensfCalculation/matrixElements/p',
                     '/fleurInput/atomSpecies/species/torgueCalculation/greensfElements/p',
                     '/fleurInput/atomGroups/atomGroup/torgueCalculation/greensfElements/p'],
               'plot': '/fleurInput/output/plotting/plot',
               'plotting': '/fleurInput/output/plotting',
               'posforce': '/fleurInput/relaxation/relaxation-history/step/posforce',
               'prodBasis': ['/fleurInput/calculationSetup/prodBasis',
                             '/fleurInput/atomSpecies/species/prodBasis'],
               'q': ['/fleurInput/forceTheorem/spinSpiralDispersion/q',
                     '/fleurInput/forceTheorem/DMI/qVectors/q',
                     '/fleurInput/forceTheorem/Jij/qVectors/q'],
               'qVectors': ['/fleurInput/forceTheorem/DMI/qVectors',
                            '/fleurInput/forceTheorem/Jij/qVectors'],
               'qsc': '/fleurInput/calculationSetup/nocoParams/qsc',
               'qss': '/fleurInput/calculationSetup/nocoParams/qss',
               'rdmft': '/fleurInput/calculationSetup/rdmft',
               'realAxis': '/fleurInput/calculationSetup/greensFunction/realAxis',
               'relPos': '/fleurInput/atomGroups/atomGroup/relPos',
               'relaxation': '/fleurInput/relaxation',
               'relaxation-history': '/fleurInput/relaxation/relaxation-history',
               'row-1': ['/fleurInput/cell/bulkLattice/row-1',
                         '/fleurInput/cell/filmLattice/row-1',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-1',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-1',
                         '/fleurInput/calculationSetup/symmetryOperations/symOp/row-1'],
               'row-2': ['/fleurInput/cell/bulkLattice/row-2',
                         '/fleurInput/cell/filmLattice/row-2',
                         '/fleurInput/cell/bulkLattice/bravaisMatrix/row-2',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-2',
                         '/fleurInput/calculationSetup/symmetryOperations/symOp/row-2'],
               'row-3': ['/fleurInput/cell/bulkLattice/bravaisMatrix/row-3',
                         '/fleurInput/cell/filmLattice/bravaisMatrix/row-3',
                         '/fleurInput/calculationSetup/symmetryOperations/symOp/row-3'],
               's': ['/fleurInput/atomSpecies/species/greensfCalculation/matrixElements/s',
                     '/fleurInput/atomGroups/atomGroup/greensfCalculation/matrixElements/s',
                     '/fleurInput/atomSpecies/species/torgueCalculation/greensfElements/s',
                     '/fleurInput/atomGroups/atomGroup/torgueCalculation/greensfElements/s'],
               'scfLoop': '/fleurInput/calculationSetup/scfLoop',
               'shape': '/fleurInput/calculationSetup/fields/shape',
               'soc': '/fleurInput/calculationSetup/soc',
               'special': '/fleurInput/atomSpecies/species/special',
               'specialOutput': '/fleurInput/output/specialOutput',
               'species': '/fleurInput/atomSpecies/species',
               'spinSpiralDispersion': '/fleurInput/forceTheorem/spinSpiralDispersion',
               'spinSpiralQPointMesh': '/fleurInput/calculationSetup/spinSpiralQPointMesh',
               'stateOccupation': '/fleurInput/atomSpecies/species/electronConfig/stateOccupation',
               'step': '/fleurInput/relaxation/relaxation-history/step',
               'symOp': '/fleurInput/calculationSetup/symmetryOperations/symOp',
               'symmetryOperations': '/fleurInput/calculationSetup/symmetryOperations',
               'tet': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/tetraeder/tet',
               'tetraeder': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/tetraeder',
               'torgueCalculation': ['/fleurInput/atomSpecies/species/torgueCalculation',
                                     '/fleurInput/atomGroups/atomGroup/torgueCalculation'],
               'tria': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/triangles/tria',
               'triangles': '/fleurInput/calculationSetup/bzIntegration/kPointLists/kPointList/triangles',
               'unfoldingBand': '/fleurInput/output/unfoldingBand',
               'vacuumDOS': '/fleurInput/output/vacuumDOS',
               'vacuumEnergyParameters': '/fleurInput/cell/filmLattice/vacuumEnergyParameters',
               'valenceConfig': '/fleurInput/atomSpecies/species/electronConfig/valenceConfig',
               'wannier': '/fleurInput/output/wannier',
               'xcFunctional': '/fleurInput/xcFunctional',
               'xcParams': '/fleurInput/xcFunctional/xcParams'},
 'tags_several': ['constant',
                  'shape',
                  'symOp',
                  'vacuumEnergyParameters',
                  'species',
                  'ldaU',
                  'ldaHIA',
                  'greensfCalculation',
                  'lo',
                  'atomGroup',
                  'relPos',
                  'absPos',
                  'filmPos',
                  'exc',
                  'addArg',
                  'layer',
                  'plot',
                  'contourRectangle',
                  'contourSemicircle',
                  'contourDOS',
                  'kPointList',
                  'kPoint',
                  'tet',
                  'tria',
                  'displace',
                  'step',
                  'posforce',
                  'q',
                  'stateOccupation']}
