# -*- coding: utf-8 -*-
__inp_version__ = '0.33'
schema_dict = {'attrib_paths': {'No': ['/fleurOutput/scfLoop/iteration/Forcetheorem_Loop_MAE/@No',
                         '/fleurOutput/scfLoop/iteration/Forcetheorem_Loop_JIJ/@No'],
                  'Q-vec': ['/fleurOutput/scfLoop/iteration/Forcetheorem_Loop_SSDISP/@Q-vec',
                            '/fleurOutput/scfLoop/iteration/Forcetheorem_Loop_DMI/@Q-vec'],
                  'atomType': ['/fleurOutput/numericalParameters/volumes/mtVolume/@atomType',
                               '/fleurOutput/startDensityCharges/mtCharges/mtCharge/@atomType',
                               '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtCharge/@atomType',
                               '/fleurOutput/startDensityCharges/mtCharges/mtJcharge/@atomType',
                               '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge/@atomType'],
                  'branch': '/fleurOutput/programVersion/gitInfo/@branch',
                  'count': '/fleurOutput/numericalParameters/kPointList/@count',
                  'd': ['/fleurOutput/startDensityCharges/mtCharges/mtCharge/@d',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtCharge/@d',
                        '/fleurOutput/startDensityCharges/mtCharges/mtJcharge/lowJ/@d',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge/lowJ/@d',
                        '/fleurOutput/startDensityCharges/mtCharges/mtJcharge/highJ/@d',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge/highJ/@d'],
                  'date': ['/fleurOutput/programVersion/compilationInfo/@date',
                           '/fleurOutput/startDateAndTime/@date',
                           '/fleurOutput/endDateAndTime/@date'],
                  'ev-sum': '/fleurOutput/scfLoop/iteration/Forcetheorem_SSDISP/Entry/@ev-sum',
                  'f': ['/fleurOutput/startDensityCharges/mtCharges/mtCharge/@f',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtCharge/@f',
                        '/fleurOutput/startDensityCharges/mtCharges/mtJcharge/lowJ/@f',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge/lowJ/@f',
                        '/fleurOutput/startDensityCharges/mtCharges/mtJcharge/highJ/@f',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge/highJ/@f'],
                  'flag': '/fleurOutput/programVersion/compilationInfo/@flag',
                  'fleurOutputVersion': '/fleurOutput/@fleurOutputVersion',
                  'host': '/fleurOutput/programVersion/compilationInfo/@host',
                  'interstitial': ['/fleurOutput/numericalParameters/volumes/@interstitial',
                                   '/fleurOutput/startDensityCharges/spinDependentCharge/@interstitial',
                                   '/fleurOutput/scfLoop/readDensityCharges/spinDependentCharge/@interstitial'],
                  'jmtd': '/fleurOutput/numericalParameters/atomsInCell/@jmtd',
                  'lastCommitHash': '/fleurOutput/programVersion/gitInfo/@lastCommitHash',
                  'link': '/fleurOutput/programVersion/compilationInfo/@link',
                  'lmaxd': '/fleurOutput/numericalParameters/basis/@lmaxd',
                  'memoryPerNode': '/fleurOutput/parallelSetup/mem/@memoryPerNode',
                  'mpiProcesses': '/fleurOutput/parallelSetup/mpi/@mpiProcesses',
                  'mtRadius': '/fleurOutput/numericalParameters/volumes/mtVolume/@mtRadius',
                  'mtSpheres': ['/fleurOutput/startDensityCharges/spinDependentCharge/@mtSpheres',
                                '/fleurOutput/scfLoop/readDensityCharges/spinDependentCharge/@mtSpheres'],
                  'mtVolume': '/fleurOutput/numericalParameters/volumes/mtVolume/@mtVolume',
                  'n_hia': '/fleurOutput/numericalParameters/atomsInCell/@n_hia',
                  'n_u': '/fleurOutput/numericalParameters/atomsInCell/@n_u',
                  'nat': '/fleurOutput/numericalParameters/atomsInCell/@nat',
                  'ng2': '/fleurOutput/numericalParameters/density/@ng2',
                  'ng3': '/fleurOutput/numericalParameters/density/@ng3',
                  'nlotot': '/fleurOutput/numericalParameters/basis/@nlotot',
                  'ntype': '/fleurOutput/numericalParameters/atomsInCell/@ntype',
                  'numbands': '/fleurOutput/numericalParameters/bands/@numbands',
                  'numberForCurrentRun': '/fleurOutput/scfLoop/iteration/@numberForCurrentRun',
                  'nvd': '/fleurOutput/numericalParameters/basis/@nvd',
                  'omegaTilda': '/fleurOutput/numericalParameters/volumes/@omegaTilda',
                  'ompThreads': '/fleurOutput/parallelSetup/openMP/@ompThreads',
                  'overallNumber': '/fleurOutput/scfLoop/iteration/@overallNumber',
                  'p': ['/fleurOutput/startDensityCharges/mtCharges/mtCharge/@p',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtCharge/@p',
                        '/fleurOutput/startDensityCharges/mtCharges/mtJcharge/lowJ/@p',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge/lowJ/@p',
                        '/fleurOutput/startDensityCharges/mtCharges/mtJcharge/highJ/@p',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge/highJ/@p'],
                  'q': '/fleurOutput/scfLoop/iteration/Forcetheorem_SSDISP/Entry/@q',
                  'qvectors': '/fleurOutput/scfLoop/iteration/Forcetheorem_SSDISP/@qvectors',
                  's': ['/fleurOutput/startDensityCharges/mtCharges/mtCharge/@s',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtCharge/@s'],
                  'spin': ['/fleurOutput/startDensityCharges/mtCharges/@spin',
                           '/fleurOutput/scfLoop/readDensityCharges/mtCharges/@spin',
                           '/fleurOutput/startDensityCharges/spinDependentCharge/@spin',
                           '/fleurOutput/scfLoop/readDensityCharges/spinDependentCharge/@spin'],
                  'surfaceArea': '/fleurOutput/numericalParameters/volumes/@surfaceArea',
                  'time': ['/fleurOutput/startDateAndTime/@time',
                           '/fleurOutput/endDateAndTime/@time'],
                  'total': ['/fleurOutput/startDensityCharges/mtCharges/mtCharge/@total',
                            '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtCharge/@total',
                            '/fleurOutput/startDensityCharges/spinDependentCharge/@total',
                            '/fleurOutput/scfLoop/readDensityCharges/spinDependentCharge/@total'],
                  'type': '/fleurOutput/programVersion/precision/@type',
                  'unitCell': '/fleurOutput/numericalParameters/volumes/@unitCell',
                  'units': ['/fleurOutput/startDensityCharges/totalCharge/@units',
                            '/fleurOutput/scfLoop/readDensityCharges/totalCharge/@units'],
                  'user': '/fleurOutput/programVersion/compilationInfo/@user',
                  'vacuum1': ['/fleurOutput/startDensityCharges/spinDependentCharge/@vacuum1',
                              '/fleurOutput/scfLoop/readDensityCharges/spinDependentCharge/@vacuum1'],
                  'vacuum2': ['/fleurOutput/startDensityCharges/spinDependentCharge/@vacuum2',
                              '/fleurOutput/scfLoop/readDensityCharges/spinDependentCharge/@vacuum2'],
                  'value': ['/fleurOutput/startDensityCharges/totalCharge/@value',
                            '/fleurOutput/scfLoop/readDensityCharges/totalCharge/@value'],
                  'version': ['/fleurOutput/programVersion/@version',
                              '/fleurOutput/programVersion/gitInfo/@version'],
                  'weightScale': '/fleurOutput/numericalParameters/kPointList/@weightScale',
                  'z1': '/fleurOutput/numericalParameters/volumes/@z1',
                  'zone': ['/fleurOutput/startDateAndTime/@zone',
                           '/fleurOutput/endDateAndTime/@zone']},
 'attrib_types': {'Delta': 'float',
                  'F_x': 'float',
                  'F_y': 'float',
                  'F_z': 'float',
                  'J': 'float',
                  'No': 'int',
                  'Q-vec': 'int',
                  'U': 'float',
                  'atomType': 'int',
                  'atomicNumber': 'int',
                  'branch': 'string',
                  'branchHighest': 'float',
                  'branchLowest': 'float',
                  'comment': 'string',
                  'count': 'int',
                  'd': 'float',
                  'date': 'string',
                  'distance': 'float',
                  'eigValSum': 'float',
                  'energy': 'float',
                  'ev-sum': 'float',
                  'f': 'float',
                  'flag': 'string',
                  'fleurOutputVersion': 'string',
                  'host': 'string',
                  'ikpt': 'int',
                  'interstitial': 'float',
                  'j': 'float',
                  'jmtd': 'int',
                  'k_x': 'float',
                  'k_y': 'float',
                  'k_z': 'float',
                  'kinEnergy': 'float',
                  'l': 'int',
                  'lastCommitHash': 'string',
                  'link': 'string',
                  'lmaxd': 'int',
                  'logDerivMT': 'float',
                  'lostElectrons': 'float',
                  'memoryPerNode': 'string',
                  'moment': 'float',
                  'mpiProcesses': 'string',
                  'mtRadius': 'float',
                  'mtSpheres': 'float',
                  'mtVolume': 'float',
                  'n': 'int',
                  'n_hia': 'int',
                  'n_u': 'int',
                  'name': 'string',
                  'nat': 'int',
                  'ng2': 'int',
                  'ng3': 'int',
                  'nlotot': 'int',
                  'ntype': 'int',
                  'numbands': 'int',
                  'numberForCurrentRun': 'int',
                  'nvd': 'int',
                  'omegaTilda': 'float',
                  'ompThreads': 'string',
                  'overallNumber': 'int',
                  'p': 'float',
                  'q': 'int',
                  'qvectors': 'int',
                  's': 'float',
                  'spin': 'int',
                  'spinDownCharge': 'float',
                  'spinUpCharge': 'float',
                  'surfaceArea': 'float',
                  'time': 'string',
                  'total': 'float',
                  'type': 'string',
                  'uIndex': 'int',
                  'unit': 'string',
                  'unitCell': 'float',
                  'units': 'string',
                  'user': 'string',
                  'vacuum': 'int',
                  'vacuum1': 'float',
                  'vacuum2': 'float',
                  'value': 'float',
                  'version': 'string',
                  'vzIR': 'float',
                  'vzInf': 'float',
                  'weight': 'float',
                  'weightScale': 'float',
                  'x': 'float',
                  'y': 'float',
                  'z': 'float',
                  'z1': 'float',
                  'zone': 'string'},
 'basic_types': {'AdditionalCompilerFlagsType': {'base_types': ['string'],
                                                 'length': 'unbounded'},
                 'AtomPosType': {'base_types': ['string'], 'length': 3},
                 'BZIntegrationModeEnum': {'base_types': ['string'],
                                           'length': 1},
                 'CoreConfigEnum': {'base_types': ['string'], 'length': 1},
                 'CoreSpecEdgeEnum': {'base_types': ['string'], 'length': 1},
                 'CoreStateListType': {'base_types': ['string'],
                                       'length': 'unbounded'},
                 'DensityMatrixForType': {'base_types': ['string'],
                                          'length': 'unbounded'},
                 'DisplaceType': {'base_types': ['float'], 'length': 3},
                 'Double3DVecType': {'base_types': ['float'], 'length': 3},
                 'Double4DVecType': {'base_types': ['float'], 'length': 4},
                 'DoubleVecType': {'base_types': ['float'],
                                   'length': 'unbounded'},
                 'EParamSelectionEnum': {'base_types': ['string'], 'length': 1},
                 'EigenvaluesAtType': {'base_types': ['float'],
                                       'length': 'unbounded'},
                 'ElectronStateEnum': {'base_types': ['string'], 'length': 1},
                 'FleurBool4DVecType': {'base_types': ['switch'], 'length': 4},
                 'FleurBoolVecType': {'base_types': ['switch'],
                                      'length': 'unbounded'},
                 'FleurVersionType': {'base_types': ['string'], 'length': 1},
                 'ForceMixEnum': {'base_types': ['string'], 'length': 1},
                 'Integer3DVecType': {'base_types': ['int'], 'length': 3},
                 'Integer4DVecType': {'base_types': ['int'], 'length': 4},
                 'IntegerVecType': {'base_types': ['int'],
                                    'length': 'unbounded'},
                 'KPointListPurposeEnum': {'base_types': ['string'],
                                           'length': 1},
                 'KPointType': {'base_types': ['string'], 'length': 3},
                 'LatticeParameterType': {'base_types': ['float'], 'length': 1},
                 'ManualCutoffType': {'base_types': ['float', 'string'],
                                      'length': 1},
                 'ManualKKintgrCutoffType': {'base_types': ['float', 'string'],
                                             'length': 1},
                 'MixingEnum': {'base_types': ['string'], 'length': 1},
                 'NobleGasConfigEnum': {'base_types': ['string'], 'length': 1},
                 'NumBandsType': {'base_types': ['int', 'string'], 'length': 1},
                 'PositionType': {'base_types': ['float'], 'length': 3},
                 'RDMFTFunctionalEnum': {'base_types': ['string'], 'length': 1},
                 'SpecialPointType': {'base_types': ['string'], 'length': 3},
                 'SpinNumberType': {'base_types': ['int'], 'length': 1},
                 'String2DVecType': {'base_types': ['string'], 'length': 2},
                 'String3DVecType': {'base_types': ['string'], 'length': 3},
                 'StringVecType': {'base_types': ['string'],
                                   'length': 'unbounded'},
                 'TargetStructureClassType': {'base_types': ['string'],
                                              'length': 'unbounded'},
                 'TriaType': {'base_types': ['int'], 'length': 3},
                 'TripleFleurBool': {'base_types': ['string'], 'length': 1},
                 'ValenceStateListType': {'base_types': ['string'],
                                          'length': 'unbounded'},
                 'XCFunctionalEnum': {'base_types': ['string'], 'length': 1},
                 'ZeroToOneNumberType': {'base_types': ['float'], 'length': 1},
                 'kPointListTypeEnum': {'base_types': ['string'], 'length': 1}},
 'iteration_attrib_paths': {'Delta': '/onSiteExchangeSplitting/excSplit/@Delta',
                            'F_x': '/totalForcesOnRepresentativeAtoms/forceTotal/@F_x',
                            'F_y': '/totalForcesOnRepresentativeAtoms/forceTotal/@F_y',
                            'F_z': '/totalForcesOnRepresentativeAtoms/forceTotal/@F_z',
                            'J': '/ldaUDensityMatrix/densityMatrixFor/@J',
                            'U': '/ldaUDensityMatrix/densityMatrixFor/@U',
                            'atomType': ['/energyParameters/atomicEP/@atomType',
                                         '/energyParameters/heAtomicEP/@atomType',
                                         '/energyParameters/loAtomicEP/@atomType',
                                         '/energyParameters/heloAtomicEP/@atomType',
                                         '/valenceDensity/mtCharges/mtCharge/@atomType',
                                         '/allElectronCharges/mtCharges/mtCharge/@atomType',
                                         '/valenceDensity/mtCharges/mtJcharge/@atomType',
                                         '/allElectronCharges/mtCharges/mtJcharge/@atomType',
                                         '/coreStates/@atomType',
                                         '/magneticMomentsInMTSpheres/magneticMoment/@atomType',
                                         '/orbitalMagneticMomentsInMTSpheres/orbMagMoment/@atomType',
                                         '/onSiteExchangeSplitting/excSplit/@atomType',
                                         '/ldaUDensityMatrix/densityMatrixFor/@atomType',
                                         '/totalForcesOnRepresentativeAtoms/forceTotal/@atomType',
                                         '/totalEnergy/atomTypeDependentContributions/@atomType'],
                            'atomicNumber': '/coreStates/@atomicNumber',
                            'branch': ['/energyParameters/atomicEP/@branch',
                                       '/energyParameters/heAtomicEP/@branch',
                                       '/energyParameters/loAtomicEP/@branch',
                                       '/energyParameters/heloAtomicEP/@branch'],
                            'branchHighest': ['/energyParameters/atomicEP/@branchHighest',
                                              '/energyParameters/heAtomicEP/@branchHighest',
                                              '/energyParameters/loAtomicEP/@branchHighest',
                                              '/energyParameters/heloAtomicEP/@branchHighest'],
                            'branchLowest': ['/energyParameters/atomicEP/@branchLowest',
                                             '/energyParameters/heAtomicEP/@branchLowest',
                                             '/energyParameters/loAtomicEP/@branchLowest',
                                             '/energyParameters/heloAtomicEP/@branchLowest'],
                            'comment': '/totalEnergy/@comment',
                            'd': ['/valenceDensity/mtCharges/mtCharge/@d',
                                  '/allElectronCharges/mtCharges/mtCharge/@d',
                                  '/valenceDensity/mtCharges/mtJcharge/lowJ/@d',
                                  '/allElectronCharges/mtCharges/mtJcharge/lowJ/@d',
                                  '/valenceDensity/mtCharges/mtJcharge/highJ/@d',
                                  '/allElectronCharges/mtCharges/mtJcharge/highJ/@d'],
                            'distance': ['/ldaUDensityMatrixConvergence/distance/@distance',
                                         '/densityConvergence/chargeDensity/@distance',
                                         '/densityConvergence/overallChargeDensity/@distance',
                                         '/densityConvergence/spinDensity/@distance'],
                            'eigValSum': '/coreStates/@eigValSum',
                            'energy': '/coreStates/state/@energy',
                            'f': ['/valenceDensity/mtCharges/mtCharge/@f',
                                  '/allElectronCharges/mtCharges/mtCharge/@f',
                                  '/valenceDensity/mtCharges/mtJcharge/lowJ/@f',
                                  '/allElectronCharges/mtCharges/mtJcharge/lowJ/@f',
                                  '/valenceDensity/mtCharges/mtJcharge/highJ/@f',
                                  '/allElectronCharges/mtCharges/mtJcharge/highJ/@f'],
                            'ikpt': '/eigenvalues/eigenvaluesAt/@ikpt',
                            'interstitial': ['/valenceDensity/spinDependentCharge/@interstitial',
                                             '/allElectronCharges/spinDependentCharge/@interstitial'],
                            'j': '/coreStates/state/@j',
                            'k_x': '/eigenvalues/eigenvaluesAt/@k_x',
                            'k_y': '/eigenvalues/eigenvaluesAt/@k_y',
                            'k_z': '/eigenvalues/eigenvaluesAt/@k_z',
                            'kinEnergy': '/coreStates/@kinEnergy',
                            'l': ['/coreStates/state/@l',
                                  '/onSiteExchangeSplitting/excSplit/@l',
                                  '/ldaUDensityMatrix/densityMatrixFor/@l'],
                            'lostElectrons': '/coreStates/@lostElectrons',
                            'moment': ['/magneticMomentsInMTSpheres/magneticMoment/@moment',
                                       '/orbitalMagneticMomentsInMTSpheres/orbMagMoment/@moment'],
                            'mtSpheres': ['/valenceDensity/spinDependentCharge/@mtSpheres',
                                          '/allElectronCharges/spinDependentCharge/@mtSpheres'],
                            'n': '/coreStates/state/@n',
                            'name': '/timing/timer/@name',
                            'p': ['/valenceDensity/mtCharges/mtCharge/@p',
                                  '/allElectronCharges/mtCharges/mtCharge/@p',
                                  '/valenceDensity/mtCharges/mtJcharge/lowJ/@p',
                                  '/allElectronCharges/mtCharges/mtJcharge/lowJ/@p',
                                  '/valenceDensity/mtCharges/mtJcharge/highJ/@p',
                                  '/allElectronCharges/mtCharges/mtJcharge/highJ/@p'],
                            's': ['/valenceDensity/mtCharges/mtCharge/@s',
                                  '/allElectronCharges/mtCharges/mtCharge/@s'],
                            'spin': ['/energyParameters/atomicEP/@spin',
                                     '/energyParameters/heAtomicEP/@spin',
                                     '/energyParameters/loAtomicEP/@spin',
                                     '/energyParameters/heloAtomicEP/@spin',
                                     '/energyParameters/vacuumEP/@spin',
                                     '/eigenvalues/eigenvaluesAt/@spin',
                                     '/valenceDensity/mtCharges/@spin',
                                     '/allElectronCharges/mtCharges/@spin',
                                     '/valenceDensity/spinDependentCharge/@spin',
                                     '/allElectronCharges/spinDependentCharge/@spin',
                                     '/coreStates/@spin',
                                     '/ldaUDensityMatrix/densityMatrixFor/@spin',
                                     '/ldaUDensityMatrixConvergence/distance/@spin',
                                     '/densityConvergence/chargeDensity/@spin',
                                     '/densityConvergence/overallChargeDensity/@spin',
                                     '/densityConvergence/spinDensity/@spin'],
                            'spinDownCharge': ['/magneticMomentsInMTSpheres/magneticMoment/@spinDownCharge',
                                               '/orbitalMagneticMomentsInMTSpheres/orbMagMoment/@spinDownCharge'],
                            'spinUpCharge': ['/magneticMomentsInMTSpheres/magneticMoment/@spinUpCharge',
                                             '/orbitalMagneticMomentsInMTSpheres/orbMagMoment/@spinUpCharge'],
                            'total': ['/valenceDensity/mtCharges/mtCharge/@total',
                                      '/allElectronCharges/mtCharges/mtCharge/@total',
                                      '/valenceDensity/spinDependentCharge/@total',
                                      '/allElectronCharges/spinDependentCharge/@total'],
                            'uIndex': '/ldaUDensityMatrix/densityMatrixFor/@uIndex',
                            'unit': '/onSiteExchangeSplitting/excSplit/@unit',
                            'units': ['/energyParameters/@units',
                                      '/bandgap/@units',
                                      '/sumValenceSingleParticleEnergies/@units',
                                      '/FermiEnergy/@units',
                                      '/valenceDensity/totalCharge/@units',
                                      '/allElectronCharges/totalCharge/@units',
                                      '/totalEnergy/densityCoulombPotentialIntegral/@units',
                                      '/totalEnergy/densityEffectivePotentialIntegral/@units',
                                      '/totalEnergy/chargeDenXCDenIntegral/@units',
                                      '/totalEnergy/FockExchangeEnergyValence/@units',
                                      '/totalEnergy/FockExchangeEnergyCore/@units',
                                      '/totalEnergy/dftUCorrection/@units',
                                      '/totalEnergy/tkbTimesEntropy/@units',
                                      '/totalEnergy/freeEnergy/@units',
                                      '/totalEnergy/extrapolationTo0K/@units',
                                      '/totalEnergy/sumOfEigenvalues/coreElectrons/@units',
                                      '/totalEnergy/sumOfEigenvalues/valenceElectrons/@units',
                                      '/totalEnergy/atomTypeDependentContributions/electronNucleiInteractionDifferentMTs/@units',
                                      '/totalEnergy/atomTypeDependentContributions/MadelungTerm/@units',
                                      '/magneticMomentsInMTSpheres/@units',
                                      '/orbitalMagneticMomentsInMTSpheres/@units',
                                      '/totalForcesOnRepresentativeAtoms/@units',
                                      '/totalForcesOnRepresentativeAtoms/forceTotal/@units',
                                      '/totalEnergy/@units',
                                      '/totalEnergy/sumOfEigenvalues/@units',
                                      '/densityConvergence/@units',
                                      '/densityConvergence/chargeDensity/@units',
                                      '/densityConvergence/overallChargeDensity/@units',
                                      '/densityConvergence/spinDensity/@units',
                                      '/timing/@units',
                                      '/timing/timer/@units'],
                            'vacuum': '/energyParameters/vacuumEP/@vacuum',
                            'vacuum1': ['/valenceDensity/spinDependentCharge/@vacuum1',
                                        '/allElectronCharges/spinDependentCharge/@vacuum1'],
                            'vacuum2': ['/valenceDensity/spinDependentCharge/@vacuum2',
                                        '/allElectronCharges/spinDependentCharge/@vacuum2'],
                            'value': ['/energyParameters/atomicEP/@value',
                                      '/energyParameters/heAtomicEP/@value',
                                      '/energyParameters/loAtomicEP/@value',
                                      '/energyParameters/heloAtomicEP/@value',
                                      '/energyParameters/vacuumEP/@value',
                                      '/bandgap/@value',
                                      '/sumValenceSingleParticleEnergies/@value',
                                      '/FermiEnergy/@value',
                                      '/valenceDensity/totalCharge/@value',
                                      '/allElectronCharges/totalCharge/@value',
                                      '/totalEnergy/densityCoulombPotentialIntegral/@value',
                                      '/totalEnergy/densityEffectivePotentialIntegral/@value',
                                      '/totalEnergy/chargeDenXCDenIntegral/@value',
                                      '/totalEnergy/FockExchangeEnergyValence/@value',
                                      '/totalEnergy/FockExchangeEnergyCore/@value',
                                      '/totalEnergy/dftUCorrection/@value',
                                      '/totalEnergy/tkbTimesEntropy/@value',
                                      '/totalEnergy/freeEnergy/@value',
                                      '/totalEnergy/extrapolationTo0K/@value',
                                      '/totalEnergy/sumOfEigenvalues/coreElectrons/@value',
                                      '/totalEnergy/sumOfEigenvalues/valenceElectrons/@value',
                                      '/totalEnergy/atomTypeDependentContributions/electronNucleiInteractionDifferentMTs/@value',
                                      '/totalEnergy/atomTypeDependentContributions/MadelungTerm/@value',
                                      '/totalEnergy/@value',
                                      '/totalEnergy/sumOfEigenvalues/@value',
                                      '/timing/timer/@value'],
                            'vzIR': '/energyParameters/vacuumEP/@vzIR',
                            'vzInf': '/energyParameters/vacuumEP/@vzInf',
                            'weight': '/coreStates/state/@weight',
                            'x': '/totalForcesOnRepresentativeAtoms/forceTotal/@x',
                            'y': '/totalForcesOnRepresentativeAtoms/forceTotal/@y',
                            'z': '/totalForcesOnRepresentativeAtoms/forceTotal/@z'},
 'iteration_paths': {'FermiEnergy': '/FermiEnergy',
                     'FockExchangeEnergyCore': '/totalEnergy/FockExchangeEnergyCore',
                     'FockExchangeEnergyValence': '/totalEnergy/FockExchangeEnergyValence',
                     'MadelungTerm': '/totalEnergy/atomTypeDependentContributions/MadelungTerm',
                     'allElectronCharges': '/allElectronCharges',
                     'atomTypeDependentContributions': '/totalEnergy/atomTypeDependentContributions',
                     'atomicEP': '/energyParameters/atomicEP',
                     'bandgap': '/bandgap',
                     'chargeDenXCDenIntegral': '/totalEnergy/chargeDenXCDenIntegral',
                     'chargeDensity': '/densityConvergence/chargeDensity',
                     'compositeTimer': '/timing/compositeTimer',
                     'coreElectrons': '/totalEnergy/sumOfEigenvalues/coreElectrons',
                     'coreStates': '/coreStates',
                     'densityConvergence': '/densityConvergence',
                     'densityCoulombPotentialIntegral': '/totalEnergy/densityCoulombPotentialIntegral',
                     'densityEffectivePotentialIntegral': '/totalEnergy/densityEffectivePotentialIntegral',
                     'densityMatrixFor': '/ldaUDensityMatrix/densityMatrixFor',
                     'dftUCorrection': '/totalEnergy/dftUCorrection',
                     'distance': '/ldaUDensityMatrixConvergence/distance',
                     'eigenvalues': '/eigenvalues',
                     'eigenvaluesAt': '/eigenvalues/eigenvaluesAt',
                     'electronNucleiInteractionDifferentMTs': '/totalEnergy/atomTypeDependentContributions/electronNucleiInteractionDifferentMTs',
                     'energyParameters': '/energyParameters',
                     'excSplit': '/onSiteExchangeSplitting/excSplit',
                     'extrapolationTo0K': '/totalEnergy/extrapolationTo0K',
                     'forceTotal': '/totalForcesOnRepresentativeAtoms/forceTotal',
                     'freeEnergy': '/totalEnergy/freeEnergy',
                     'heAtomicEP': '/energyParameters/heAtomicEP',
                     'heloAtomicEP': '/energyParameters/heloAtomicEP',
                     'highJ': ['/valenceDensity/mtCharges/mtJcharge/highJ',
                               '/allElectronCharges/mtCharges/mtJcharge/highJ'],
                     'ldaUDensityMatrix': '/ldaUDensityMatrix',
                     'ldaUDensityMatrixConvergence': '/ldaUDensityMatrixConvergence',
                     'loAtomicEP': '/energyParameters/loAtomicEP',
                     'lowJ': ['/valenceDensity/mtCharges/mtJcharge/lowJ',
                              '/allElectronCharges/mtCharges/mtJcharge/lowJ'],
                     'magneticMoment': '/magneticMomentsInMTSpheres/magneticMoment',
                     'magneticMomentsInMTSpheres': '/magneticMomentsInMTSpheres',
                     'mtCharge': ['/valenceDensity/mtCharges/mtCharge',
                                  '/allElectronCharges/mtCharges/mtCharge'],
                     'mtCharges': ['/valenceDensity/mtCharges',
                                   '/allElectronCharges/mtCharges'],
                     'mtJcharge': ['/valenceDensity/mtCharges/mtJcharge',
                                   '/allElectronCharges/mtCharges/mtJcharge'],
                     'onSiteExchangeSplitting': '/onSiteExchangeSplitting',
                     'orbMagMoment': '/orbitalMagneticMomentsInMTSpheres/orbMagMoment',
                     'orbitalMagneticMomentsInMTSpheres': '/orbitalMagneticMomentsInMTSpheres',
                     'overallChargeDensity': '/densityConvergence/overallChargeDensity',
                     'spinDensity': '/densityConvergence/spinDensity',
                     'spinDependentCharge': ['/valenceDensity/spinDependentCharge',
                                             '/allElectronCharges/spinDependentCharge'],
                     'state': '/coreStates/state',
                     'sumOfEigenvalues': '/totalEnergy/sumOfEigenvalues',
                     'sumValenceSingleParticleEnergies': '/sumValenceSingleParticleEnergies',
                     'timer': '/timing/timer',
                     'timing': '/timing',
                     'tkbTimesEntropy': '/totalEnergy/tkbTimesEntropy',
                     'totalCharge': ['/valenceDensity/totalCharge',
                                     '/allElectronCharges/totalCharge'],
                     'totalEnergy': '/totalEnergy',
                     'totalForcesOnRepresentativeAtoms': '/totalForcesOnRepresentativeAtoms',
                     'vacuumEP': '/energyParameters/vacuumEP',
                     'valenceDensity': '/valenceDensity',
                     'valenceElectrons': '/totalEnergy/sumOfEigenvalues/valenceElectrons'},
 'simple_elements': {'additionalCompilerFlags': {'length': 'unbounded',
                                                 'type': ['string']},
                     'densityMatrixFor': {'length': 'unbounded',
                                          'type': ['string']},
                     'eigenvaluesAt': {'length': 'unbounded',
                                       'type': ['float']},
                     'kPoint': {'length': 3, 'type': ['string']},
                     'targetComputerArchitectures': {'length': 1,
                                                     'type': ['string']},
                     'targetStructureClass': {'length': 'unbounded',
                                              'type': ['string']}},
 'tag_order': {'Forcetheorem_SSDISP': 'Entry',
               'compositeTimer': ['compositeTimer', 'timer'],
               'coreStates': 'state',
               'densityConvergence': ['chargeDensity',
                                      'overallChargeDensity',
                                      'spinDensity'],
               'eigenvalues': 'eigenvaluesAt',
               'energyParameters': ['atomicEP',
                                    'heAtomicEP',
                                    'loAtomicEP',
                                    'heloAtomicEP',
                                    'vacuumEP'],
               'iteration': [[['energyParameters',
                               'eigenvalues',
                               'bandgap',
                               'sumValenceSingleParticleEnergies',
                               'FermiEnergy',
                               'valenceDensity',
                               'onSiteExchangeSplitting',
                               'coreStates',
                               'allElectronCharges',
                               'magneticMomentsInMTSpheres',
                               'orbitalMagneticMomentsInMTSpheres',
                               'totalEnergy',
                               'totalForcesOnRepresentativeAtoms',
                               'ldaUDensityMatrix',
                               'ldaUDensityMatrixConvergence',
                               'densityConvergence',
                               'timing'],
                              'Forcetheorem_Loop_SSDISP',
                              'Forcetheorem_Loop_DMI',
                              'Forcetheorem_Loop_MAE',
                              'Forcetheorem_Loop_JIJ'],
                             'Forcetheorem_SSDISP'],
               'kPointList': 'kPoint',
               'ldaUDensityMatrix': 'densityMatrixFor',
               'ldaUDensityMatrixConvergence': 'distance',
               'magneticMomentsInMTSpheres': 'magneticMoment',
               'mtCharges': ['mtCharge', 'mtJcharge'],
               'mtJcharge': ['lowJ', 'highJ'],
               'numericalParameters': ['atomsInCell',
                                       'basis',
                                       'density',
                                       'bands',
                                       'volumes',
                                       'kPointList'],
               'onSiteExchangeSplitting': 'excSplit',
               'orbitalMagneticMomentsInMTSpheres': 'orbMagMoment',
               'parallelSetup': ['openMP', 'mpi', 'mem'],
               'scfLoop': ['readDensityCharges', 'iteration'],
               'startDensityCharges': ['mtCharges',
                                       'spinDependentCharge',
                                       'totalCharge'],
               'timing': ['compositeTimer', 'timer'],
               'totalEnergy': ['sumOfEigenvalues',
                               'densityCoulombPotentialIntegral',
                               'densityEffectivePotentialIntegral',
                               'chargeDenXCDenIntegral',
                               'FockExchangeEnergyValence',
                               'FockExchangeEnergyCore',
                               'atomTypeDependentContributions',
                               'dftUCorrection',
                               'tkbTimesEntropy',
                               'freeEnergy',
                               'extrapolationTo0K'],
               'totalForcesOnRepresentativeAtoms': 'forceTotal',
               'volumes': 'mtVolume'},
 'tag_paths': {'Entry': '/fleurOutput/scfLoop/iteration/Forcetheorem_SSDISP/Entry',
               'Forcetheorem_Loop_DMI': '/fleurOutput/scfLoop/iteration/Forcetheorem_Loop_DMI',
               'Forcetheorem_Loop_JIJ': '/fleurOutput/scfLoop/iteration/Forcetheorem_Loop_JIJ',
               'Forcetheorem_Loop_MAE': '/fleurOutput/scfLoop/iteration/Forcetheorem_Loop_MAE',
               'Forcetheorem_Loop_SSDISP': '/fleurOutput/scfLoop/iteration/Forcetheorem_Loop_SSDISP',
               'Forcetheorem_SSDISP': '/fleurOutput/scfLoop/iteration/Forcetheorem_SSDISP',
               'additionalCompilerFlags': '/fleurOutput/programVersion/additionalCompilerFlags',
               'atomsInCell': '/fleurOutput/numericalParameters/atomsInCell',
               'bands': '/fleurOutput/numericalParameters/bands',
               'basis': '/fleurOutput/numericalParameters/basis',
               'compilationInfo': '/fleurOutput/programVersion/compilationInfo',
               'density': '/fleurOutput/numericalParameters/density',
               'endDateAndTime': '/fleurOutput/endDateAndTime',
               'fleurInput': '/fleurOutput/fleurInput',
               'fleurOutput': '/fleurOutput',
               'gitInfo': '/fleurOutput/programVersion/gitInfo',
               'highJ': ['/fleurOutput/startDensityCharges/mtCharges/mtJcharge/highJ',
                         '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge/highJ'],
               'iteration': '/fleurOutput/scfLoop/iteration',
               'kPoint': '/fleurOutput/numericalParameters/kPointList/kPoint',
               'kPointList': '/fleurOutput/numericalParameters/kPointList',
               'lowJ': ['/fleurOutput/startDensityCharges/mtCharges/mtJcharge/lowJ',
                        '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge/lowJ'],
               'mem': '/fleurOutput/parallelSetup/mem',
               'mpi': '/fleurOutput/parallelSetup/mpi',
               'mtCharge': ['/fleurOutput/startDensityCharges/mtCharges/mtCharge',
                            '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtCharge'],
               'mtCharges': ['/fleurOutput/startDensityCharges/mtCharges',
                             '/fleurOutput/scfLoop/readDensityCharges/mtCharges'],
               'mtJcharge': ['/fleurOutput/startDensityCharges/mtCharges/mtJcharge',
                             '/fleurOutput/scfLoop/readDensityCharges/mtCharges/mtJcharge'],
               'mtVolume': '/fleurOutput/numericalParameters/volumes/mtVolume',
               'numericalParameters': '/fleurOutput/numericalParameters',
               'openMP': '/fleurOutput/parallelSetup/openMP',
               'parallelSetup': '/fleurOutput/parallelSetup',
               'precision': '/fleurOutput/programVersion/precision',
               'programVersion': '/fleurOutput/programVersion',
               'readDensityCharges': '/fleurOutput/scfLoop/readDensityCharges',
               'scfLoop': '/fleurOutput/scfLoop',
               'spinDependentCharge': ['/fleurOutput/startDensityCharges/spinDependentCharge',
                                       '/fleurOutput/scfLoop/readDensityCharges/spinDependentCharge'],
               'startDateAndTime': '/fleurOutput/startDateAndTime',
               'startDensityCharges': '/fleurOutput/startDensityCharges',
               'targetComputerArchitectures': '/fleurOutput/programVersion/targetComputerArchitectures',
               'targetStructureClass': '/fleurOutput/programVersion/targetStructureClass',
               'totalCharge': ['/fleurOutput/startDensityCharges/totalCharge',
                               '/fleurOutput/scfLoop/readDensityCharges/totalCharge'],
               'volumes': '/fleurOutput/numericalParameters/volumes'},
 'tags_several': ['mtVolume',
                  'kPoint',
                  'iteration',
                  'Forcetheorem_Loop_SSDISP',
                  'Forcetheorem_Loop_DMI',
                  'Forcetheorem_Loop_MAE',
                  'Forcetheorem_Loop_JIJ',
                  'Entry',
                  'coreStates',
                  'atomicEP',
                  'heAtomicEP',
                  'loAtomicEP',
                  'heloAtomicEP',
                  'vacuumEP',
                  'eigenvaluesAt',
                  'mtCharges',
                  'spinDependentCharge',
                  'mtCharge',
                  'mtJcharge',
                  'state',
                  'magneticMoment',
                  'orbMagMoment',
                  'forceTotal',
                  'densityMatrixFor',
                  'excSplit',
                  'atomTypeDependentContributions',
                  'chargeDensity',
                  'distance',
                  'compositeTimer',
                  'timer']}
